//! The host constants the SDK reads, rendered into its `hostConstants.ts`: the cleartext client's,
//! and the EIP-712 domain type its production digests also hash. The test fails when the committed
//! file differs, so a change here reaches the SDK or fails CI.
//! `ZAMA_UPDATE_SDK_CONSTANTS=1` rewrites the file.

use anchor_lang::Discriminator;

use super::layout::{
    ENTRY_LEN, ENTRY_VALUE_OFFSET, HISTORY_RECORD_LEN, MAGIC, RECORDED, STORE_ACCOUNT_SIZE,
    STORE_HISTORY_COUNT_OFFSET, STORE_HISTORY_LEN, STORE_HISTORY_OFFSET, STORE_SECTION_OFFSET,
    STORE_SLOTS_OFFSET,
};
use super::value_len;
use crate::eip712::{CIPHERTEXT_VERIFICATION_TYPE, DOMAIN_TYPE};
use crate::events::FheExecutedEvent;
use crate::EVENT_VERSION;

const SDK_FILE: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../sdk/js-sdk/src/solana/cleartext/hostConstants.ts"
);
const UPDATE_ENV: &str = "ZAMA_UPDATE_SDK_CONSTANTS";

fn bytes(bytes: &[u8]) -> String {
    let list: Vec<String> = bytes.iter().map(u8::to_string).collect();
    format!("Uint8Array.of({})", list.join(", "))
}

fn text(bytes: &[u8]) -> &str {
    std::str::from_utf8(bytes).unwrap()
}

fn render() -> String {
    let input_value_lens: Vec<String> = (0..=u8::MAX)
        .filter_map(|fhe_type| Some(format!("{fhe_type}: {}", value_len(fhe_type).ok()?)))
        .collect();
    format!(
        "\
// Generated by `zama_host::cleartext::sdk_constants` from the host source; do not edit. Regenerate with
// `ZAMA_UPDATE_SDK_CONSTANTS=1 cargo test -p zama-host --features cleartext --lib sdk_constants` from solana/.

/** `cleartext::layout`: where the cleartext host keeps plaintexts inside an `EncryptedStore`. */
export const MAGIC = '{magic}';
export const ENTRY_LEN = {ENTRY_LEN};
export const ENTRY_VALUE_OFFSET = {ENTRY_VALUE_OFFSET};
export const RECORDED = {RECORDED};
export const STORE_SECTION_OFFSET = {STORE_SECTION_OFFSET};
export const STORE_SLOTS_OFFSET = {STORE_SLOTS_OFFSET};
export const STORE_HISTORY_COUNT_OFFSET = {STORE_HISTORY_COUNT_OFFSET};
export const STORE_HISTORY_OFFSET = {STORE_HISTORY_OFFSET};
export const STORE_HISTORY_LEN = {STORE_HISTORY_LEN};
export const HISTORY_RECORD_LEN = {HISTORY_RECORD_LEN};
export const STORE_ACCOUNT_SIZE = {STORE_ACCOUNT_SIZE};

/** `cleartext::value_len`: bytes one input value takes in `extraData`, per FHE type the host supports. */
export const INPUT_VALUE_LEN: Readonly<Partial<Record<number, number>>> = {{ {input_value_lens} }};

/** Anchor's `EVENT_IX_TAG_LE`, which heads every event the host emits by self-CPI. */
export const EVENT_IX_TAG = {event_ix_tag};
export const FHE_EXECUTED_EVENT_DISCRIMINATOR = {fhe_executed};
export const EVENT_VERSION = {EVENT_VERSION};

/** `eip712`: the domain type of every certificate the host verifies, and the input attestation's type. */
export const EIP712_DOMAIN_TYPE = '{domain_type}';
export const CIPHERTEXT_VERIFICATION_TYPE =
  '{ciphertext_verification_type}';
",
        magic = text(&MAGIC),
        input_value_lens = input_value_lens.join(", "),
        event_ix_tag = bytes(anchor_lang::event::EVENT_IX_TAG_LE),
        fhe_executed = bytes(FheExecutedEvent::DISCRIMINATOR),
        domain_type = text(DOMAIN_TYPE),
        ciphertext_verification_type = text(CIPHERTEXT_VERIFICATION_TYPE),
    )
}

#[test]
fn the_sdk_cleartext_constants_match_the_host() {
    let rendered = render();
    if std::env::var_os(UPDATE_ENV).is_some() {
        std::fs::write(SDK_FILE, &rendered).unwrap();
        return;
    }
    let committed = std::fs::read_to_string(SDK_FILE).unwrap_or_default();
    assert!(
        committed == rendered,
        "{SDK_FILE} is out of date; rewrite it with {UPDATE_ENV}=1 and commit it. Expected:\n{rendered}"
    );
}
