network:
  chainId: "54321"
  mnemonic: coyote sketch defense hover finger envelope celery urge panther venue
    verb cheese
port: 8546
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi
