name: listener
http_port: 8080

database:
  db_url: postgres://postgres:postgres@listener-postgres:5432/listener
  migration_max_attempts: 5
  pool:
    max_connections: 10
    min_connections: 2

broker:
  broker_type: redis
  broker_url: redis://listener-redis:6379

blockchain:
  type: evm
  chain_id: 1
  rpc_url: http://listener-erpc:4000/listener-indexer/evm/1
  network: ethereum-mainnet
  strategy:
    automatic_startup: true
    block_start_on_first_start: 24572795
    range_size: 100
    loop_delay_ms: 1000
    max_parallel_requests: 50
    block_fetcher: block_receipts
    # batch_receipts_size_range: 10
    compute_block: true
