[profile.default]
src = "src"
out = "artifacts"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "ds-test/=node_modules/@openzeppelin/foundry-upgrades/lib/solidity-stringutils/lib/ds-test/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    "solidity-stringutils/=node_modules/@openzeppelin/foundry-upgrades/lib/solidity-stringutils/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
