#!/usr/bin/env bash
#
# Start an anvil node with the cleartext v12 stack already on it, by loading pkg/state/genesis.json.
# Deploys nothing and compiles nothing. Ctrl-C stops the node.
#
# Usage: ./scripts/anvil-fast.sh [--port PORT] [--no-check]
#
#   --port PORT   anvil port (default: 8545)
#   --no-check    skip the integrity and smoke checks
#
# This is the fast counterpart to scripts/anvil.sh. Same node, same accounts, same stack — the difference
# is only how the stack gets there:
#
#   anvil.sh       compile pkg/src against freshly computed addresses, then deploy and verify  (~20 s)
#   anvil-fast.sh  anvil --init pkg/state/genesis.json                                         (instant)
#
# The genesis file is a snapshot of exactly what anvil.sh produces: 20 contracts with their code and
# storage, plus the deployer EOA carrying its post-deploy nonce. It is generated by
# `npm run generate:genesis`, which only writes it after the deploy it snapshots has passed the full
# verification in pkg/forge/script/VerifyFhevmDeploy.s.sol.
#
# ## Why this is a snapshot and not a shortcut
#
# `anvil --init` applies the genesis `alloc` *on top of* the accounts anvil derives from the mnemonic
# (apply_genesis in anvil's backend inserts the dev accounts first, then overlays the alloc). So the ten
# funded dev accounts are still there with their normal balances; only the addresses named in the alloc
# are touched. The mnemonic and derivation path below therefore have to match scripts/anvil.sh exactly, or
# the account indices a test expects will not line up.
#
# The deployer's nonce is part of the alloc on purpose. Both loaders apply `nonce.unwrap_or_default()`
# unconditionally, so an entry without one would silently reset it to 0 — and the next CREATE from that
# account would then collide with the already-present stack.
#
# ## Limits
#
# Only the canonical local stack: the addresses baked into the snapshot are the ones ZamaConfig.sol
# hardcodes for chain 31337, which come from the package mnemonic at account index 5 with a start nonce of
# 0. There is deliberately no --mnemonic or --account-index here; for anything else use scripts/deploy.sh,
# which computes addresses for the deployer you give it.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

PORT=8545
CHECK=1

while [ $# -gt 0 ]; do
    case "$1" in
        --port)
            [ $# -ge 2 ] || { echo "Error: --port requires a value." >&2; exit 1; }
            PORT="$2"; shift 2 ;;
        --port=*) PORT="${1#--port=}"; shift ;;
        --no-check) CHECK=0; shift ;;
        -h | --help) sed -n '2,10p' "${BASH_SOURCE[0]}"; exit 0 ;;
        *) echo "Error: unknown argument '$1'. Try --help." >&2; exit 1 ;;
    esac
done

cd "$PACKAGE_ROOT"

# shellcheck source=scripts/anvil-lib.sh
source "$SCRIPT_DIR/anvil-lib.sh"

require_tools anvil cast

GENESIS="pkg/state/genesis.json"
RPC_URL="http://127.0.0.1:${PORT}"

if [ ! -f "$GENESIS" ]; then
    echo "Error: $GENESIS is missing. Generate it with: npm run generate:genesis" >&2
    exit 1
fi

# The snapshot is byte-reproducible — balances and block metadata, the only things that move between
# runs, are normalised out of it — so this checks the contents, not just that the file downloaded intact.
if [ "$CHECK" -eq 1 ] && [ -f "${GENESIS}.sha256" ]; then
    if ! (cd "$(dirname "$GENESIS")" && shasum -a 256 -c "$(basename "$GENESIS").sha256" >/dev/null 2>&1); then
        echo "Error: $GENESIS does not match ${GENESIS}.sha256." >&2
        echo "       It has been edited by hand, or it is stale relative to the sources." >&2
        echo "       Regenerate with: npm run generate:genesis" >&2
        exit 1
    fi
    echo "🔒 $GENESIS matches its published sha256"
fi

ANVIL_PID=""
trap cleanup EXIT INT TERM

echo "⛓  anvil on ${RPC_URL} with the stack preloaded from $GENESIS"
load_generated_addresses_and_bootstrap
start_anvil --init "$GENESIS"

wait_for_node

if [ "$CHECK" -eq 1 ]; then
    echo ""
    echo "🔎 checking the preloaded stack"
    smoke_check || exit 1
fi

echo ""
report_stack

echo ""
enable_anvil_traces
echo "   anvil is still running on ${RPC_URL} — press Ctrl-C to stop."
wait "$ANVIL_PID"
