services:
  ####################### DATABASE SETUP #######################
  db:
    container_name: db
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  key-downloader:
    container_name: key-downloader
    image: busybox
    volumes:
      - keys-cache:/keys
    command: >
      sh -c "echo 'Starting key downloads...' &&
            wget http://s3-mock:9000/kms-public/kms/PUB/PublicKey/408d8cbaa51dece7f782fe04ba0b1c1d017b10880c538b7c72037468fe5c97ee -O /keys/pks &&
            echo 'Downloaded public key' &&
            wget http://s3-mock:9000/kms-public/kms/PUB/ServerKey/408d8cbaa51dece7f782fe04ba0b1c1d017b10880c538b7c72037468fe5c97ee -O /keys/sks &&
            echo 'Downloaded server key' &&
            wget http://s3-mock:9000/kms-public/kms/PUB/SnsKey/408d8cbaa51dece7f782fe04ba0b1c1d017b10880c538b7c72037468fe5c97ee -O /keys/sns_pk &&
            echo 'Downloaded SNS key' &&
            wget http://s3-mock:9000/kms-public/kms/PUB/CRS/a5fedad3fd734a598fb67452099229445cb68447198fb56f29bb64d98953d002 -O /keys/pp &&
            echo 'Downloaded PP key - All downloads complete'"
  db-migration:
    container_name: db-migration
    image: ghcr.io/zama-ai/fhevm-db-migration:f1ed378
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CHAIN_ID: ${CHAIN_ID}
      TENANT_API_KEY: ${TENANT_API_KEY}
      ACL_CONTRACT_ADDRESS: ${ACL_CONTRACT_ADDRESS}
      INPUT_VERIFIER_ADDRESS: ${INPUT_VERIFIER_ADDRESS}
    volumes:
      - keys-cache:/fhevm-keys
    depends_on:
      db:
        condition: service_healthy

  ####################### COPROCESSOR SERVICES #######################
  httpz-listener:
    container_name: "httpz-listener"
    image: ghcr.io/zama-ai/fhevm-coprocessor:f1ed378
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TENANT_API_KEY: ${TENANT_API_KEY}
      RPC_URL: ${RPC_URL}
    command:
      - fhevm_listener
      - --database-url=${DATABASE_URL}
      - --coprocessor-api-key=${TENANT_API_KEY}
      - --url=${RPC_URL}
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  gw-listener:
    container_name: "gw-listener"
    image: ghcr.io/zama-ai/fhevm-coprocessor:f1ed378
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GATEWAY_URL: ${GATEWAY_WS_URL}
      ZKPOK_MANAGER_ADDRESS: ${ZKPOK_MANAGER_ADDRESS}
    command:
      - gw_listener
      - --database-url=${DATABASE_URL}
      - --gw-url=${GATEWAY_WS_URL}
      - --zkpok-manager-address=${ZKPOK_MANAGER_ADDRESS}
      - --verify-proof-req-database-channel="event_zkpok_new_work"
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  tfhe-worker:
    container_name: tfhe-worker
    image: ghcr.io/zama-ai/fhevm-coprocessor:f1ed378
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./config/coprocessor/coprocessor.key:/usr/share/coprocessor.key
    command:
      - coprocessor
      - --database-url=$(DATABASE_URL)
      - --worker-polling-interval-ms=1000
      - --work-items-batch-size=10
      - --tenant-key-cache-size=32
      - --coprocessor-fhe-threads=8
      - --tokio-threads=4
      - --pg-pool-max-connections=10
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  zkproof-worker:
    container_name: "zkproof-worker"
    image: ghcr.io/zama-ai/fhevm-coprocessor:f1ed378
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command:
      - zkproof_worker
      - --database-url=${DATABASE_URL}
      - --pg-listen-channel="event_zkpok_new_work"
      - --pg-notify-channel="event_zkpok_computed"
      - --pg-polling-interval=5
      - --pg-pool-connections=5
      - --worker-thread-count=4
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  sns-worker:
    container_name: "sns-worker"
    image: ghcr.io/zama-ai/fhevm-coprocessor:f1ed378
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TENANT_API_KEY: ${TENANT_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_REGION: ${AWS_REGION}
    command:
      - sns_worker
      - --database-url=${DATABASE_URL}
      - --tenant-api-key=${TENANT_API_KEY}
      - --pg-listen-channels=["event_pbs_computations" "event_ciphertext_computed"]
      - --pg-notify-channel="event_ciphertext128_computed"
      - --work-items-batch-size=4
      - --pg-polling-interval=60
      - --pg-pool-connections=10
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  transaction-sender:
    container_name: "transaction-sender"
    image: ghcr.io/zama-ai/fhevm-coprocessor:f1ed378
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GATEWAY_URL: ${GATEWAY_URL}
      TX_SENDER_PRIVATE_KEY: ${TX_SENDER_PRIVATE_KEY}
      ZKPOK_MANAGER_ADDRESS: ${ZKPOK_MANAGER_ADDRESS}
      CIPHERTEXT_MANAGER_ADDRESS: ${CIPHERTEXT_MANAGER_ADDRESS}
    command:
      - transaction_sender
      - --database-url=${DATABASE_URL}
      - --database-pool-size=10
      - --database-polling-interval-secs=5
      - --verify-proof-resp-database-channel="event_zkpok_computed"
      - --add-ciphertexts-database-channel="event_ciphertexts_uploaded"
      - --verify-proof-resp-batch-limit=128
      - --verify-proof-resp-max-retries=15
      - --verify-proof-remove-after-max-retries
      - --ciphertext-manager-address=${CIPHERTEXT_MANAGER_ADDRESS}
      - --zkpok-manager-address=${ZKPOK_MANAGER_ADDRESS}
      - --gateway-url=${GATEWAY_URL}
      - --private-key=${TX_SENDER_PRIVATE_KEY}
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

volumes:
  db:
  keys-cache:
