services:
  ####################### DATABASE SETUP #######################
  db:
    container_name: db
    image: postgres:15.7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data

  key-downloader:
    container_name: key-downloader
    image: busybox
    volumes:
      - keys-cache:/keys
    environment:
      KMS_PUBLIC_KEY: ${KMS_PUBLIC_KEY}
      KMS_SERVER_KEY: ${KMS_SERVER_KEY}
      KMS_SNS_KEY: ${KMS_SNS_KEY}
      KMS_CRS_KEY: ${KMS_CRS_KEY}
    command: >
      sh -c "echo 'Starting key downloads...' &&
            wget $KMS_PUBLIC_KEY -O /keys/pks &&
            echo 'Downloaded public key' &&
            wget $KMS_SERVER_KEY -O /keys/sks &&
            echo 'Downloaded server key' &&
            wget $KMS_SNS_KEY -O /keys/sns_pk &&
            echo 'Downloaded SNS key' &&
            wget $KMS_CRS_KEY -O /keys/pp &&
            echo 'Downloaded PP key - All downloads complete'"

  db-migration:
    container_name: db-migration
    image: ghcr.io/zama-ai/fhevm-db-migration:9759b54
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CHAIN_ID: ${CHAIN_ID}
      TENANT_API_KEY: ${TENANT_API_KEY}
      ACL_CONTRACT_ADDRESS: ${ACL_CONTRACT_ADDRESS}
      INPUT_VERIFIER_ADDRESS: ${INPUT_VERIFIER_ADDRESS}
      KEY_ID: ${FHE_KEY_ID}
    volumes:
      - keys-cache:/fhevm-keys
    depends_on:
      db:
        condition: service_healthy
      key-downloader:
        condition: service_completed_successfully

  ####################### COPROCESSOR SERVICES #######################
  httpz-listener:
    container_name: "httpz-listener"
    image: ghcr.io/zama-ai/fhevm-coprocessor:57666aa
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TENANT_API_KEY: ${TENANT_API_KEY}
      RPC_URL: ${RPC_URL}
    command:
      - fhevm_listener
      - --database-url=${DATABASE_URL}
      - --coprocessor-api-key=${TENANT_API_KEY}
      - --url=${RPC_URL}
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  gw-listener:
    container_name: "gw-listener"
    image: ghcr.io/zama-ai/fhevm-coprocessor:57666aa
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GATEWAY_URL: ${GATEWAY_WS_URL}
      ZKPOK_MANAGER_ADDRESS: ${ZKPOK_MANAGER_ADDRESS}
    command:
      - gw_listener
      - --database-url=${DATABASE_URL}
      - --gw-url=${GATEWAY_WS_URL}
      - --zkpok-manager-address=${ZKPOK_MANAGER_ADDRESS}
      - --verify-proof-req-database-channel="event_zkpok_new_work"
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  tfhe-worker:
    container_name: tfhe-worker
    image: ghcr.io/zama-ai/fhevm-coprocessor:57666aa
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command:
      - coprocessor
      - --run-bg-worker
      - --database-url=${DATABASE_URL}
      - --pg-pool-max-connections=10
      - --worker-polling-interval-ms=1000
      - --work-items-batch-size=10
      - --tenant-key-cache-size=32
      - --coprocessor-fhe-threads=8
      - --tokio-threads=4
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  zkproof-worker:
    container_name: "zkproof-worker"
    image: ghcr.io/zama-ai/fhevm-coprocessor:57666aa
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command:
      - zkproof_worker
      - --database-url=${DATABASE_URL}
      - --pg-listen-channel="event_zkpok_new_work"
      - --pg-notify-channel="event_zkpok_computed"
      - --pg-polling-interval=5
      - --pg-pool-connections=5
      - --worker-thread-count=4
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  sns-worker:
    container_name: "sns-worker"
    image: ghcr.io/zama-ai/fhevm-coprocessor:57666aa
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TENANT_API_KEY: ${TENANT_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
      AWS_REGION: ${AWS_REGION}
    command:
      - sns_worker
      - --database-url=${DATABASE_URL}
      - --tenant-api-key=${TENANT_API_KEY}
      - --pg-listen-channels=["event_pbs_computations" "event_ciphertext_computed"]
      - --pg-notify-channel="event_ciphertext128_computed"
      - --work-items-batch-size=4
      - --pg-polling-interval=60
      - --pg-pool-connections=10
      - --bucket-name-ct64=ct64
      - --bucket-name-ct128=ct128
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

  transaction-sender:
    container_name: "transaction-sender"
    image: ghcr.io/zama-ai/fhevm-coprocessor:57666aa
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GATEWAY_URL: ${GATEWAY_URL}
      GATEWAY_WS_URL: ${GATEWAY_WS_URL}
      TX_SENDER_PRIVATE_KEY: ${TX_SENDER_PRIVATE_KEY}
      ZKPOK_MANAGER_ADDRESS: ${ZKPOK_MANAGER_ADDRESS}
      CIPHERTEXT_MANAGER_ADDRESS: ${CIPHERTEXT_MANAGER_ADDRESS}
      ACL_MANAGER_ADDRESS: ${ACL_MANAGER_ADDRESS}
    command:
      - transaction_sender
      - --database-url=${DATABASE_URL}
      - --gateway-url=${GATEWAY_WS_URL}
      - --private-key=${TX_SENDER_PRIVATE_KEY}
      - --ciphertext-manager-address=${CIPHERTEXT_MANAGER_ADDRESS}
      - --zkpok-manager-address=${ZKPOK_MANAGER_ADDRESS}
      - --acl-manager-address=${ACL_MANAGER_ADDRESS}
      - --database-pool-size=10
      - --database-polling-interval-secs=5
      - --verify-proof-resp-database-channel="event_zkpok_computed"
      - --add-ciphertexts-database-channel="event_ciphertexts_uploaded"
      - --verify-proof-resp-batch-limit=128
      - --verify-proof-resp-max-retries=15
      - --verify-proof-remove-after-max-retries
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully

volumes:
  db:
  keys-cache:
