services:
  layer2-node:
    container_name: layer2-node
    image: ghcr.io/foundry-rs/foundry:stable
    environment:
      MNEMONIC: ${MNEMONIC}
    entrypoint:
      [
        "anvil",
        "--block-time",
        "0.5",
        "--host",
        "0.0.0.0",
        "--port",
        "8546",
        "--chain-id",
        "54321",
        "--accounts",
        "15",
        "--mnemonic",
        "${MNEMONIC}"
      ]
    ports:
      - "8546:8546"
  
  layer2-sc-deploy:
    container_name: layer2-sc-deploy
    image: ghcr.io/zama-ai/gateway-l2/sc-bundle:01ab6c6
    environment:
      - HARDHAT_NETWORK=staging
    volumes:
      - ./config/env/.env.staging.layer2:/app/.env
    command: [ "bash", "/app/deploy-gateway-contracts.sh"]
    depends_on:
      layer2-node:
        condition: service_started

  layer2-sc-add-network:
    container_name: layer2-sc-add-network
    image: ghcr.io/zama-ai/gateway-l2/sc-bundle:01ab6c6
    environment:
      - HARDHAT_NETWORK=staging
    volumes:
      - ./config/env/.env.staging.layer2:/app/.env
    command: [ "bash", "/app/add-httpz-networks.sh"]
    depends_on:
      layer2-sc-deploy:
        condition: service_completed_successfully
