services:
  s3-mock:
      container_name: s3-mock
      image: quay.io/minio/minio
      ports:
        - "9000:9000"
        - "9001:9001"
      entrypoint: >
        minio server /data --console-address ":9001"
      environment:
        MINIO_ROOT_USER: zamadmin
        MINIO_ROOT_PASSWORD: zamadmin
      healthcheck:
        test: [ "CMD", "mc", "ready", "local" ]
        interval: 1s
        timeout: 10s
        retries: 10

  # Minio client to create access keys
  s3-mock-setup:
    container_name: s3-mock-setup
    image: quay.io/minio/mc
    environment:
      MINIO_ROOT_USER: zamadmin
      MINIO_ROOT_PASSWORD: zamadmin
      ACCESS_KEY: fhevm-access-key
      SECRET_KEY: fhevm-access-secret-key
      MINIO_ENDPOINT: "http://s3-mock:9000"
    # entrypoint: > 
    #     /bin/sh -c " tail -f /dev/null"
    entrypoint: >
      /bin/sh -c "
        sleep 1 &&
        mc alias set myminio $${MINIO_ENDPOINT} $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
        mc admin user add myminio $${ACCESS_KEY} $${SECRET_KEY} &&
        mc admin policy attach myminio readwrite --user $${ACCESS_KEY} &&
        echo $${ACCESS_KEY} &&
        echo $${SECRET_KEY} &&
        echo $${ACCESS_KEY} > /minio_secrets/access_key &&
        echo $${SECRET_KEY} > /minio_secrets/secret_key &&
        cat /minio_secrets/access_key &&
        cat /minio_secrets/secret_key &&
        mc mb --with-lock --ignore-existing myminio/kms-public &&
        mc anonymous set public myminio/kms-public
      "
    volumes:
      - minio_secrets:/minio_secrets
    depends_on:
      s3-mock:
        condition: service_healthy

  s3-mock-keys-loader:
    container_name: s3-mock-keys-loader
    image: debian:stable-slim
    command: ["/load-keys.sh"]
    volumes:
      - ./config/kms-keys:/keys
      - ./config/load-keys.sh:/load-keys.sh
    depends_on:
      s3-mock-setup:
        condition: service_completed_successfully
volumes:
  minio_secrets: