// Generates contracts/E2ECoprocessorConfigLocal.sol from the host contract addresses in the
// environment, so a single test-suite image can target any deployment (the addresses come from
// the pod's env, e.g. the `<chain>-sc-addresses` ConfigMaps) without patching the file with sed.
//
// Opt-in: runs only when E2E_COPROCESSOR_CONFIG_FROM_ENV=true. Otherwise the committed file (or
// the one written by the fhevm CLI for the local stack) is left untouched.
//
// Usage: npx ts-node --transpile-only scripts/generate-coprocessor-config.ts [--no-compile]
import dotenv from 'dotenv';
import { ZeroAddress, getAddress } from 'ethers';
import { writeFileSync } from 'fs';
import { resolve } from 'path';

const ENABLE_FLAG = 'E2E_COPROCESSOR_CONFIG_FROM_ENV';
const OUTPUT_PATH = resolve(__dirname, '..', 'contracts', 'E2ECoprocessorConfigLocal.sol');

// Same dotenv resolution as hardhat.config.ts. Values already in the environment win.
dotenv.config({ path: resolve(__dirname, '..', process.env.DOTENV_CONFIG_PATH || './.env') });

// Must match _getCleartextConfig() in the committed contracts/E2ECoprocessorConfigLocal.sol.
const CLEARTEXT_CONFIG = {
  acl: '0x50157CFfD6bBFA2DECe204a89ec419c23ef5755D',
  coprocessor: '0xe3a9105a3a932253A70F126eb1E3b589C643dD24',
  kmsVerifier: '0x901F8942346f7AB3a01F6D7613119Bca447Bb030',
};

// CoprocessorAddress is the FHEVMExecutor, hence FHEVM_EXECUTOR_CONTRACT_ADDRESS.
const REQUIRED_VARS = {
  acl: 'ACL_CONTRACT_ADDRESS',
  coprocessor: 'FHEVM_EXECUTOR_CONTRACT_ADDRESS',
  kmsVerifier: 'KMS_VERIFIER_CONTRACT_ADDRESS',
} as const;

type CoprocessorAddresses = Record<keyof typeof REQUIRED_VARS, string>;

const fail = (errors: string[]): never => {
  console.error('Failed to generate E2ECoprocessorConfigLocal.sol:');
  for (const error of errors) console.error(`  - ${error}`);
  console.error('The file was not modified.');
  process.exit(1);
};

const readAddresses = (): CoprocessorAddresses => {
  const errors: string[] = [];
  const addresses: Partial<CoprocessorAddresses> = {};

  for (const [key, name] of Object.entries(REQUIRED_VARS) as [keyof CoprocessorAddresses, string][]) {
    const value = process.env[name]?.trim();
    if (!value) {
      errors.push(`${name} is not set`);
      continue;
    }
    let address: string;
    try {
      // getAddress also normalizes to the EIP-55 checksum that solc requires for address literals.
      address = getAddress(value);
    } catch {
      errors.push(`${name} is not a valid address (or has a bad checksum): ${value}`);
      continue;
    }
    if (address === ZeroAddress) {
      errors.push(`${name} is the zero address`);
      continue;
    }
    addresses[key] = address;
  }

  if (errors.length) fail(errors);
  return addresses as CoprocessorAddresses;
};

const renderConfigLiteral = ({ acl, coprocessor, kmsVerifier }: CoprocessorAddresses) =>
  [
    'CoprocessorConfig({',
    `                ACLAddress: ${acl},`,
    `                CoprocessorAddress: ${coprocessor},`,
    `                KMSVerifierAddress: ${kmsVerifier}`,
    '            })',
  ].join('\n');

const renderSolidity = (addresses: CoprocessorAddresses) => `// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTO-GENERATED by scripts/generate-coprocessor-config.ts from ${Object.values(REQUIRED_VARS).join(', ')}.
// Do not edit by hand: regenerated by run-tests.sh when ${ENABLE_FLAG}=true.

import {CoprocessorConfig, FHE} from "@fhevm/solidity/lib/FHE.sol";

library DefaultCoprocessorConfig {
    function getConfig() internal view returns (CoprocessorConfig memory config) {
        if (block.chainid == 31337) {
            config = _getCleartextConfig();
        } else {
            config = _getConfig();
        }
    }

    function _getConfig() internal pure returns (CoprocessorConfig memory) {
        return
            ${renderConfigLiteral(addresses)};
    }

    function _getCleartextConfig() internal pure returns (CoprocessorConfig memory) {
        return
            ${renderConfigLiteral(CLEARTEXT_CONFIG)};
    }
}

contract E2ECoprocessorConfig {
    constructor() {
        FHE.setCoprocessor(DefaultCoprocessorConfig.getConfig());
    }
}
`;

const main = () => {
  if (process.env[ENABLE_FLAG] !== 'true') {
    console.log(`${ENABLE_FLAG} is not 'true': keeping the existing E2ECoprocessorConfigLocal.sol.`);
    return;
  }

  // Without compilation the tests would run stale bytecode that still holds the old addresses.
  if (process.argv.includes('--no-compile')) {
    fail([`${ENABLE_FLAG}=true needs compilation, but --no-compile was given`]);
  }

  const solidity = renderSolidity(readAddresses());
  writeFileSync(OUTPUT_PATH, solidity);
  console.log(`Generated ${OUTPUT_PATH}:\n${solidity}`);
};

main();
