services:
  gateway-sc-deploy:
    container_name: gateway-sc-deploy
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    command:
      - npx hardhat task:deployAllGatewayContracts
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app

  gateway-sc-upgrade:
    container_name: gateway-sc-upgrade
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    command:
      - sh /app/gateway-compat-upgrade.sh
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/compat/gateway-upgrade-from:/app/generated-upgrade-from:ro
      - ../scripts/gateway-compat-upgrade.sh:/app/gateway-compat-upgrade.sh:ro

  gateway-sc-add-network:
    container_name: gateway-sc-add-network
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    command:
      - npx hardhat task:addHostChainsToGatewayConfig --use-internal-proxy-address true
    depends_on:
      gateway-sc-deploy:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because all contracts
    # are compiled, and most of them import these addresses.
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app

  gateway-sc-add-pausers:
    container_name: gateway-sc-add-pausers
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    command:
      - npx hardhat task:addGatewayPausers ${GATEWAY_ADD_PAUSERS_INTERNAL_FLAG} true
    depends_on:
      gateway-sc-add-network:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because the PauserSet
    # contract is compiled, and it imports these addresses.
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app

  gateway-sc-trigger-keygen:
    container_name: gateway-sc-trigger-keygen
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    # Using test parameters (--params-type 1) is currently not possible at it can make the random
    # tests fail with a high probability (1/2 chance), so we instead use default parameters (--params-type 0).
    # See https://github.com/zama-ai/fhevm-internal/issues/685
    command:
      - npx hardhat task:triggerKeygen --params-type 0 --use-internal-proxy-address true
    depends_on:
      gateway-sc-add-pausers:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because all contracts
    # are compiled, and most of them import these addresses.
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app

  gateway-sc-trigger-crsgen:
    container_name: gateway-sc-trigger-crsgen
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    # Using test parameters (--params-type 1) is currently not possible for keygen (see above), and
    # CRS parameters must be of the same type as the keygen parameters.
    # See https://github.com/zama-ai/fhevm-internal/issues/685
    command:
      - npx hardhat task:triggerCrsgen --params-type 0 --max-bit-length 2048 --use-internal-proxy-address true
    depends_on:
      gateway-sc-trigger-keygen:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because all contracts
    # are compiled, and most of them import these addresses.
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app
