services:
  gateway-deploy-mocked-zama-oft:
    container_name: gateway-deploy-mocked-zama-oft
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-mocked-payment.env
    command:
      - npx hardhat task:deployMockedZamaOFT


  gateway-set-relayer-mocked-payment:
    container_name: gateway-set-relayer-mocked-payment
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-mocked-payment.env
    command:
      - npx hardhat task:setTxSenderMockedPayment
    depends_on:
      gateway-deploy-mocked-zama-oft:
        condition: service_completed_successfully
