services:
  gateway-sc-deploy:
    container_name: gateway-sc-deploy
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    command:
      - npx hardhat task:deployAllGatewayContracts
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app

  gateway-sc-add-network:
    container_name: gateway-sc-add-network
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    command:
      - npx hardhat task:addHostChainsToGatewayConfig --use-internal-proxy-address true
    depends_on:
      gateway-sc-deploy:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because all contracts
    # are compiled, and most of them import these addresses.
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app

  gateway-sc-add-pausers:
    container_name: gateway-sc-add-pausers
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:${GATEWAY_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/gateway-sc.env
    command:
      - npx hardhat task:addGatewayPausers ${GATEWAY_ADD_PAUSERS_INTERNAL_FLAG} true
    depends_on:
      gateway-sc-add-network:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because the PauserSet
    # contract is compiled, and it imports these addresses.
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/gateway:/app/addresses  # workdir in gateway's Dockerfile is /app
