services:
  host-node:
    container_name: host-node
    image: ghcr.io/foundry-rs/foundry:v1.3.5
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/host-node.env
    entrypoint:
      - anvil
      - --block-time
      - "1"
      - --host
      - 0.0.0.0
      - --port
      - "${HOST_NODE_PORT:-8545}"
      - --chain-id
      - "${HOST_NODE_CHAIN_ID:-12345}"
      - --accounts
      - "120"
      - --mnemonic
      - "${MNEMONIC}"
      # Reduce number of slots in an epoch to consider transaction as finalized ASAP.
      # A tx is generally considered finalized after two epochs.
      - --slots-in-an-epoch
      - "1"
    ports:
      - "${HOST_NODE_PORT:-8545}:${HOST_NODE_PORT:-8545}"
