services:
  host-sc-deploy:
    container_name: host-sc-deploy
    image: ghcr.io/zama-ai/fhevm/host-contracts:${HOST_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/host-sc.env
    command:
      - npx hardhat task:deployAllHostContracts
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/${HOST_ADDRESS_DIR:-host}:/app/addresses  # workdir in host's Dockerfile is /app

  host-sc-compat-upgrade:
    container_name: host-sc-compat-upgrade
    image: ghcr.io/zama-ai/fhevm/host-contracts:${HOST_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/host-sc.env
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/${HOST_ADDRESS_DIR:-host}:/app/addresses  # workdir in host's Dockerfile is /app
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/compat/host-previous-contracts:/app/previous-contracts:ro

  host-sc-add-pausers:
    container_name: host-sc-add-pausers
    image: ghcr.io/zama-ai/fhevm/host-contracts:${HOST_VERSION}
    env_file:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/env/host-sc.env
    command:
      - npx hardhat task:addHostPausers ${HOST_ADD_PAUSERS_INTERNAL_FLAG} true
    depends_on:
      host-sc-deploy:
        condition: service_completed_successfully
    # Addresses needs to be mounted even though we don't use them in the task because the PauserSet
    # contract is compiled, and it imports these addresses.
    volumes:
      - ${FHEVM_STATE_DIR:-../../../.fhevm}/runtime/addresses/${HOST_ADDRESS_DIR:-host}:/app/addresses  # workdir in host's Dockerfile is /app
