services:
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    # Note: we need to set maxmemory policy to noeviction in order to avoid
    # automatic removal of keys which would cause unexpected errors in BullMQ
    command: redis-server --save 20 1 --loglevel warning --maxmemory-policy noeviction
    volumes:
      - cache:/data

  postgres:
    image: postgres:17-alpine
    restart: always
    container_name: console-db
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-console}
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  relayer-db:
    image: postgres:17-alpine
    restart: always
    container_name: relayer-db
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-relayer}
    ports:
      - "5433:5432"
    volumes:
      - relayer-db:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: console-aws
    restart: always
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-central-1}
    volumes:
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Here we mount our setup file so it will be executed when
      # the container start
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh

  relayer-db-init:
    environment:
      - DATABASE_URL=postgres://postgres:postgres@relayer-db:5432/relayer
      - RUST_LOG=debug
    image: rust:1.85
    entrypoint: >
      /bin/sh -c "cargo install diesel_cli && cd /app/lib && diesel setup && diesel migration run --migration-dir /app/lib/migrations && touch /tmp/done && sleep 65 && exit 0 "
    healthcheck:
      test: [ "CMD", "test", "-f", "/tmp/done" ]
      interval: 5s
      timeout: 1s
      retries: 240
      start_period: 60s
    working_dir: /app
    volumes: 
      - ./apps/relayer:/app


volumes:
  cache:
  postgres:
  localstack:
  relayer-db:
