# Run commands for the console services
name: console
services:
  relayer:
    environment:
      - RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__FHE_PUBLIC_KEY__DATA_ID=${RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__FHE_PUBLIC_KEY__DATA_ID:-fhe-public-key-data-id}
      - RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__FHE_PUBLIC_KEY__URL=${RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__FHE_PUBLIC_KEY__URL:-}
      - RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__CRS__DATA_ID=${RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__CRS__DATA_ID:-crs-data-id}
      - RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__CRS__URL=${RELAYER_STANDALONE_RELAYER_CONFIGURATION__KEY_URL__CRS__URL:-}
      - RELAYER_STANDALONE_RELAYER_CONFIGURATION__HTTP_PORT=${RELAYER_STANDALONE_RELAYER_CONFIGURATION__HTTP_PORT:-}
      - RELAYER_STANDALONE_RELAYER_CONFIGURATION__HTTP_HOSTNAME=${RELAYER_STANDALONE_RELAYER_CONFIGURATION__HTTP_HOSTNAME:-}
    ports:
      - "4324:4324"
