# Run commands for the console services
name: console
services:
  back:
    image: local/console/back:${DOCKER_TAG:-latest}
    container_name: console-back
    environment:
      - RUN_MODE=prod
    # We need to add fhevm settings
    volumes:
      - type: bind
        target: /prod-wrkspc/config/prod.yaml
        source: ${PWD}/apps/back/config/compose.yaml
    env_file:
      - ./apps/back/.env.compose
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:3005/healthcheck"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    ports:
      - "3005:3005"
    networks:
      - console-net

  front:
    image: local/console/front:${DOCKER_TAG:-latest}
    container_name: console-front
    env_file:
      - ./apps/front/.env.compose
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8001"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    ports:
      - "8001:8080"
    networks:
      - console-net
    volumes:
      - type: bind
        target: /usr/share/nginx/html/scripts/env.js
        source: ${PWD}/apps/front/src/public/scripts/env.compose.js
    depends_on:
      back:
        condition: service_started

  relayer:
    image: local/console/relayer:latest
    container_name: console-relayer
    env_file:
      - ./apps/relayer/.env.compose
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
    build:
      context: ../apps/relayer/fhevm-relayer
      dockerfile: ../../apps/relayer/fhevm-relayer/Dockerfile
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        cat /config.yaml &&
        /bin/server --config-file /config.yaml
    networks:
      - fhevm_default
      - console-net
    volumes:
      - type: bind
        target: /config.yaml
        source: ${PWD}/apps/relayer/fhevm-relayer-compose.yaml
    ports:
      - "3001:3000"
      - "9898:9898"

# It uses an already created docker-network
networks:
  console-net:
    name: console-net
  fhevm_default:
    name: fhevm_default
    external: true
