# "External" services needed to run the Console
name: console-infra
services:
  console_postgres:
    image: postgres:17-alpine
    restart: always
    container_name: console-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-console-db}
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - console_postgres:/var/lib/postgresql/data
    networks:
      - console-net

volumes:
  console_postgres:

# It creates an isolated docker-network
networks:
  console-net:
    name: console-net
