# Names to target built images
services:
  back-migrate:
    image: ghcr.io/zama-ai/console/back:${DOCKER_TAG:-latest}

  orchestrator-migrate:
    image: ghcr.io/zama-ai/console/orchestrator:${DOCKER_TAG:-latest}

  web3-migrate:
    image: ghcr.io/zama-ai/console/web3:${DOCKER_TAG:-latest}
