# Build docker compose
services:
  back:
    image: local/console/back:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile

  front:
    image: local/console/front:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile

  relayer:
    image: local/console/relayer:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/relayer/Dockerfile
