# Build docker compose
services:
  back:
    image: zws_local/console/back:${DOCKER_TAG-latest}
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile

  email:
    image: zws_local/console/email:${DOCKER_TAG-latest}
    build:
      context: .
      dockerfile: ./docker/email/Dockerfile

  front:
    image: zws_local/console/front:${DOCKER_TAG-latest}
    build:
      context: .
      # This doesn't work because vite is a devDependency
      # Updated Dockerfile to use temp http-server to serve SPA
      dockerfile: ./docker/front/Dockerfile

  orchestrator:
    image: zws_local/console/orchestrator:${DOCKER_TAG-latest}
    build:
      context: .
      dockerfile: ./docker/orchestrator/Dockerfile

  web3:
    image: zws_local/console/web3:${DOCKER_TAG-latest}
    build:
      context: .
      dockerfile: ./docker/web3/Dockerfile

  relayer:
    image: zws_local/console/relayer:${DOCKER_TAG-latest}
    build:
      context: ./apps/relayer/
      dockerfile: ../../docker/relayer/Dockerfile
