# Names to target built images
services:
  back-migrate:
    image: ghcr.io/zama-zws/console/back:${DOCKER_TAG:-latest}

  back:
    image: ghcr.io/zama-zws/console/back:${DOCKER_TAG:-latest}

  email:
    image: ghcr.io/zama-zws/console/email:${DOCKER_TAG:-latest}

  front:
    image: ghcr.io/zama-zws/console/front:${DOCKER_TAG:-latest}

  orchestrator-migrate:
    image: ghcr.io/zama-zws/console/orchestrator:${DOCKER_TAG:-latest}

  orchestrator:
    image: ghcr.io/zama-zws/console/orchestrator:${DOCKER_TAG:-latest}

  web3-migrate:
    image: ghcr.io/zama-zws/console/web3:${DOCKER_TAG:-latest}

  web3:
    image: ghcr.io/zama-zws/console/web3:${DOCKER_TAG:-latest}

  relayer:
    image: ghcr.io/zama-zws/console/relayer:${DOCKER_TAG:-latest}
