# Run commands for the console services
# fhevm relayer
services:
  relayer:
    image: ghcr.io/zama-ai/fhevm-relayer:latest
    container_name: fhevm-console-relayer
    env_file:
      - ./apps/relayer/.env.fhevm.relayer.compose
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
    build:
      context: ../apps/relayer/fhevm-relayer
      dockerfile: ../../apps/relayer/fhevm-relayer/Dockerfile
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      cat /config.yaml &&
      /bin/server --config-file /config.yaml
    networks:
      - fhevm_default
      - console-net
    volumes:
      - type: bind
        target: /config.yaml
        source: ${PWD}/apps/relayer/fhevm-relayer-compose.yaml
    ports:
      - "3001:3000"
      - "9898:9898"
    depends_on:
      # NOTE: we can't provide a dependency on the fhevm stack components
      # since they are launched independently but the blockchain nodes are required
      local_aws:
        condition: service_healthy
      relayer-migrate:
        condition: service_completed_successfully

# It uses an already created docker-network
networks:
  console-net:
    name: console-net
  fhevm_default:
    name: fhevm_default
    external: true
