services:
  tests-e2e-debug:
    container_name: console-tests-e2e-debug
    image: ghcr.io/zama-ai/fhevm-test-suite/e2e-new:${TESTS_VERSION:-8c8de11}
    env_file:
      - ./external/httpz-test-suite/fhevm/env/staging/.env.tests.local
    environment:
      - RELAYER_URL=${RELAYER_URL:-http://console-back:3005}
    command:
      - tail -f /dev/null
    networks:
      - fhevm_default
      - console-net


networks:
  console-net:
    name: console-net
    external: true
  fhevm_default:
    name: fhevm_default
    external: true

