# Run commands for the console services
name: console
services:

  back:
    image: zws_local/console/back:${DOCKER_TAG:-latest}
    container_name: console-back
    depends_on:
      local_redis:
        condition: service_healthy
      local_aws:
        condition: service_healthy
      back-migrate:
        condition: service_completed_successfully
    # These vars will be populated from fhevm containers
    environment:
      - CRS_URLS=${CRS_URLS}
      - KEY_URLS=${KEY_URLS}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    env_file:
      - ./apps/back/.env.compose
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3005/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "3005:3005"
    networks:
      - console-net

  email:
    image: zws_local/console/email:${DOCKER_TAG:-latest}
    container_name: console-email
    env_file:
      - ./apps/email/.env.compose
    # This returns 404 error because it's not implemented yet
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:8002"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      - console-net
    depends_on:
      local_aws:
        condition: service_healthy

  front:
    image: zws_local/console/front:${DOCKER_TAG:-latest}
    container_name: console-front
    env_file:
      - ./apps/front/.env.compose
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8001"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    ports:
      - "8001:8080" 
    networks:
      - console-net
    depends_on:
      back:
        condition: service_started

  orchestrator:
    image: zws_local/console/orchestrator:${DOCKER_TAG:-latest}
    container_name: console-orchestrator
    depends_on:
      local_aws:
        condition: service_healthy
      orchestrator-migrate:
        condition: service_completed_successfully
    env_file:
      - ./apps/orchestrator/.env.compose
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    # This returns 404 error because it's not implemented yet
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:3001"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      - console-net

  web3:
    image: zws_local/console/web3:${DOCKER_TAG:-latest}
    container_name: console-web3
    depends_on:
      local_aws:
        condition: service_healthy
      web3-migrate:
        condition: service_completed_successfully
    env_file:
      - ./apps/web3/.env.compose
    # This returns 404 error because it's not implemented yet
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://localhost:3002"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
    networks:
      - console-net

  relayer:
    image: zws_local/console/relayer:latest
    container_name: console-relayer
    env_file:
      - ./apps/relayer/.env.compose
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
    build:
      context: ../apps/relayer/
      dockerfile: ../../docker/relayer/Dockerfile
    command: 
      - "/bin/server"
      - "--config-file"
      - "/config.toml" 
      - "--config-file"
      - "/compose/host.toml" 
      - "--config-file"
      - "/compose/gateway.toml" 
    networks:
      - fhevm_default
      - console-net
    volumes:
      - type: bind
        target: /config.toml
        source: ${PWD}/apps/relayer/compose.toml
      - type: bind
        target: /compose/
        source: ${PWD}/apps/relayer/compose/
    depends_on:
      # NOTE: we can't provide a dependency on the fhevm stack components
      # but the blockchain nodes are required
      local_aws:
        condition: service_healthy
      relayer-migrate:
        condition: service_completed_successfully

# It uses an already created docker-network
networks:
  console-net:
    name: console-net
  fhevm_default:
    name: fhevm_default
    external: true
