# "External" services needed to run the Console
name: console-infra
services:
  local_redis:
    image: redis:7.4-alpine
    restart: always
    container_name: console-redis
    ports:
      - "6379:6379"
    # Note: we need to set maxmemory policy to noeviction in order to avoid
    # automatic removal of keys which would cause unexpected errors in BullMQ
    command: redis-server --save 20 1 --loglevel warning --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - cache:/data
    networks:
      - console-net
  console_postgres:
    image: postgres:17-alpine
    restart: always
    container_name: console-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-console-db}
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - console_postgres:/var/lib/postgresql/data
    networks:
      - console-net

  local_aws:
    image: localstack/localstack:latest
    container_name: console-aws
    restart: always
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=sqs,ses,s3 # I need S3 to store the sent emails
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-central-1}
    volumes:
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Here we mount our setup file so it will be executed when
      # the container start
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    networks:
      - console-net
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/done"]
      interval: 5s
      timeout: 1s
      retries: 240
      start_period: 60s

  relayer_postgres:
    image: postgres:17-alpine
    restart: always
    container_name: relayer-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-relayer-db}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - relayer_postgres:/var/lib/postgresql/data
    networks:
      - console-net

volumes:
  cache:
  console_postgres:
  relayer_postgres:
  localstack:

# It creates an isolated docker-network
networks:
  console-net:
    name: console-net
