services:
  postgres:
    image: postgres:17-alpine
    restart: always
    container_name: console-db-test
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-console}
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:latest
    container_name: console-aws-test
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-central-1}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Here we mount our setup file so it will be executed when
      # the container start
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
