packages:
  - "apps/*"
  - "packages/*"

syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true

# documentation: https://pnpm.io/catalogs
catalog:
  typescript: "5.6.2"
  eslint: "9.13.0"
  globals: 16.2.0
  nestjs-pino: "4.3.0"
  pino: "9.6.0"
  pino-http: "10.4.0"
  pino-pretty: "13.0.0"
  prettier: "3.4.0"
  # `prisma` and `@prisma/client` must be the same version
  prisma: "6.9.0"
  "@prisma/client": "6.9.0"
  "@ssut/nestjs-sqs": "3.0.1"
  unplugin-swc: "1.5.1"
  vite-tsconfig-paths: "5.1.3"
  zod: "3.24.2"
  # Nest JS
  "@nestjs/schematics": "11.0.5"
  "@nestjs/testing": "11.1.1"
  "@nestjs/common": "11.1.1"
  "@nestjs/core": "11.1.1"
  "@nestjs/config": "4.0.2"
  "@nestjs/graphql": "13.1.0"
  "@nestjs/apollo": "13.1.0"
  "@nestjs/jwt": "11.0.0"
  "@nestjs/passport": "11.0.5"
  "@nestjs/platform-express": "11.1.1"
  "reflect-metadata": "0.1.13"
  nestjs-cls: 5.4.3

  # Development and testing
  vitest: 3.2.1
  "@faker-js/faker": "9.8.0"
