[profile.default]
libs = ["dependencies"]
optimizer = true
optimizer_runs = 800
via_ir = false
src = "src"
out = "out"
allow_paths = ["../../.."]
fs_permissions = [
    { access = "read", path = "out" },
    { access = "read", path = "../../.." },
    { access = "write", path = "../test/fheTest" },
    { access = "write", path = "src/latest/host-contracts/addresses" },
    { access = "write", path = "src/v0.12.0/host-contracts/addresses" },
    { access = "write", path = "src/v0.13.0/host-contracts/addresses" },
]
remappings = [
    "forge-std/=dependencies/forge-std-1.11.0/src/",
    "encrypted-types/=dependencies/@encrypted-types-0.0.4/",
    "@openzeppelin-contracts-5.1.0/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin-contracts-upgradeable-5.1.0/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@fhevm/solidity/=../../../library-solidity/",
]

[rpc_endpoints]
mainnet = "https://ethereum-rpc.publicnode.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[lint]
exclude_lints = [
    "unsafe-typecast", 
    "incorrect-shift", 
    "mixed-case-variable", 
    "mixed-case-function", 
    "named-struct-fields", 
    "screaming-snake-case-const",
    "pascal-case-struct",
    "asm-keccak256",
    "unwrapped-modifier-logic",
    "unsafe-cheatcode"
]

[dependencies]
forge-std = "1.11.0"
"@encrypted-types" = "0.0.4"
"@openzeppelin-contracts" = "5.1.0"
"@openzeppelin-contracts-upgradeable" = "5.1.0"

[profile.v12]
remappings = [
    "forge-std/=dependencies/forge-std-1.11.0/src/",
    "encrypted-types/=dependencies/@encrypted-types-0.0.4/",
    "@openzeppelin-contracts-5.1.0/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin-contracts-upgradeable-5.1.0/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@fhevm/solidity/=../../../library-solidity/",
    "@fhevm/host-contracts/=./src/v0.12.0/host-contracts/",
    "@fhevm/cleartext/=./src/v0.12.0/cleartext/",
    "@fhevm/host-contracts-0.12.0/=./src/v0.12.0/host-contracts/",
    "@fhevm/cleartext-0.12.0/=./src/v0.12.0/cleartext/",
]

[profile.v13]
remappings = [
    "forge-std/=dependencies/forge-std-1.11.0/src/",
    "encrypted-types/=dependencies/@encrypted-types-0.0.4/",
    "@openzeppelin-contracts-5.1.0/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin-contracts-upgradeable-5.1.0/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@fhevm/solidity/=../../../library-solidity/",
    "@fhevm/host-contracts/=./src/v0.13.0/host-contracts/",
    "@fhevm/cleartext/=./src/v0.13.0/cleartext/",
    "@fhevm/host-contracts-0.13.0/=./src/v0.13.0/host-contracts/",
    "@fhevm/cleartext-0.13.0/=./src/v0.13.0/cleartext/",
]
