prometheus-postgres-exporter:
  image:
    registry: hub.zama.org/cgr
    repository: zama.ai/prometheus-postgres-exporter
    # if not set appVersion field from Chart.yaml is used
    #tag: ""
    pullPolicy: IfNotPresent
    pullSecrets:
      - registry-credentials
  serviceMonitor:
    enabled: true
    interval: 30s
    multipleTarget:
      enabled: true
      sharedAuthModule:
        enabled: true
        name: "shared"
      targets:
        - endpoint: coprocessor-database.coproc.svc.cluster.local
          name: coprocessor-database
          port: 5432
          databaseName: postgres
  config:
    existingSecret:
      enabled: true
      name: "postgres-exporter-config"
      key: "postgres_exporter.yml"
    extraArgs:
      - --extend.query-path=/etc/postgres_exporter/queries.yaml
  extraVolumes:
    - name: custom-queries
      configMap:
        name: coprocessor-postgres-exporter-queries
  extraVolumeMounts:
    - name: custom-queries
      mountPath: /etc/postgres_exporter/queries.yaml
      subPath: queries.yaml
      readOnly: true
