name: "test-deploy"
services:
  chain:
    container_name: test-chain
    image: ghcr.io/foundry-rs/foundry:stable
    environment:
      - MNEMONIC=${MNEMONIC:-adapt mosquito move limb mobile illegal tree voyage juice mosquito burger raise father hope layer}
    entrypoint: >
      /bin/sh -c "
      anvil --block-time 1 --host 0.0.0.0 --port 8756 --chain-id 123456 --accounts 15 --mnemonic \"$${MNEMONIC}\"
      "
    ports:
      - "8756:8756"

  gateway-sc-deploy:
    image: ghcr.io/zama-ai/fhevm/gateway-contracts:v0.7.0-rc0
    container_name: fhevm-gateway-sc-deploy-mock
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - RPC_URL=http://test-chain:8756
      - MNEMONIC=${MNEMONIC:-adapt mosquito move limb mobile illegal tree voyage juice mosquito burger raise father hope layer}
      - DEPLOYER_PRIVATE_KEY=${DEPLOYER_PRIVATE_KEY:-0x8355bb293b8714a06b972bfe692d1bd9f24235c1f4007ae0be285d398b0bba2f}
      - CHAIN_ID=123456
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      printenv &&
      npx hardhat task:deployAllContracts &&
      touch /tmp/done &&
      sleep 30 &&
      exit 0
      "
    depends_on:
      chain:
        condition: service_started
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/done"]
      interval: 3s
      timeout: 1s
      retries: 300
      start_period: 20s

