/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as introspection from "./introspection";
export type { introspection };
import type * as math from "./math";
export type { math };
