[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
confidential_token = "9Sbhx7VF6vAGdYApPikwHgJ68Z367Au2tTyw9FpBxnAh"
confidential_token_receiver = "55pb9LouMGGfFMLkRWCLEkk6cZMP34oFgHhmsfSMAkpK"
zama_host = "BXsiKq6Jg4vgdBqSd75NbMbKaB7WFKK48NVXx4zoeLsW"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"

[hooks]
