[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
confidential_token = "AYevU3R9B94fYWRkiyeecWahoRZwv6jorZsizyheiU7k"
zama_host = "4TU1nKdM6cfPRctp5ziwCfDB2VRLaV6yGGgR6KpZGc7C"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
