use std::net::TcpListener;

use aws_config::BehaviorVersion;
use aws_sdk_kms::types::{KeySpec, KeyUsageType};
use testcontainers::{core::WaitFor, runners::AsyncRunner, ContainerAsync, GenericImage, ImageExt};

pub fn pick_free_port() -> u16 {
    TcpListener::bind("127.0.0.1:0")
        .unwrap()
        .local_addr()
        .unwrap()
        .port()
}

/// Default port for MinIO (used for S3 by sns-worker tests).
pub const MINIO_PORT: u16 = 9000;

/// Default port for local-kms.
pub const LOCAL_KMS_PORT: u16 = 8080;

pub struct TestContainer {
    pub container: ContainerAsync<GenericImage>,
    pub host_port: u16,
}

/// Starts a MinIO container for S3 operations (sns-worker tests).
pub async fn start_minio() -> anyhow::Result<TestContainer> {
    let host_port = pick_free_port();
    let container = GenericImage::new("minio/minio", "latest")
        .with_exposed_port(MINIO_PORT.into())
        .with_wait_for(WaitFor::message_on_stderr("API:"))
        .with_mapped_port(host_port, MINIO_PORT.into())
        .with_env_var("MINIO_ROOT_USER", "minioadmin")
        .with_env_var("MINIO_ROOT_PASSWORD", "minioadmin")
        .with_cmd(["server", "/data", "--console-address", ":9001"])
        .start()
        .await?;
    Ok(TestContainer {
        container,
        host_port,
    })
}

/// Starts a local-kms container for KMS operations (transaction-sender tests).
pub async fn start_local_kms() -> anyhow::Result<TestContainer> {
    let host_port = pick_free_port();
    let container = GenericImage::new("nsmithuk/local-kms", "latest")
        .with_exposed_port(LOCAL_KMS_PORT.into())
        .with_wait_for(WaitFor::message_on_stderr("Local KMS started"))
        .with_mapped_port(host_port, LOCAL_KMS_PORT.into())
        .with_env_var("PORT", LOCAL_KMS_PORT.to_string())
        .with_env_var("KMS_REGION", "us-east-1")
        .start()
        .await?;
    Ok(TestContainer {
        container,
        host_port,
    })
}

/// Creates a KMS client pointing to the given port.
pub async fn create_kms_client(host_port: u16) -> anyhow::Result<aws_sdk_kms::Client> {
    let endpoint_url = format!("http://localhost:{}", host_port);
    std::env::set_var("AWS_ENDPOINT_URL", &endpoint_url);
    std::env::set_var("AWS_REGION", "us-east-1");
    std::env::set_var("AWS_ACCESS_KEY_ID", "test");
    std::env::set_var("AWS_SECRET_ACCESS_KEY", "test");
    let aws_conf = aws_config::load_defaults(BehaviorVersion::latest()).await;
    let aws_kms_client = aws_sdk_kms::Client::new(&aws_conf);
    Ok(aws_kms_client)
}

/// Creates an AWS KMS signing key (secp256k1) and returns the key ID.
/// The key material is generated by the KMS service.
pub async fn create_kms_signing_key(
    aws_kms_client: &aws_sdk_kms::Client,
) -> anyhow::Result<String> {
    let out = aws_kms_client
        .create_key()
        .key_spec(KeySpec::EccSecgP256K1)
        .key_usage(KeyUsageType::SignVerify)
        .send()
        .await?;
    Ok(out.key_metadata.unwrap().key_id().to_string())
}
