// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTOGENERATED by `npm run generate:local-host-bytecode` via `cast interface`.
// DO NOT EDIT — your changes will be overwritten. See internal/generateLocalHostBytecode.ts.

interface IERC1967Proxy {
    error AddressEmptyCode(address target);
    error ERC1967InvalidImplementation(address implementation);
    error ERC1967NonPayable();
    error FailedCall();

    event Upgraded(address indexed implementation);

    fallback() external payable;
}
