// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTOGENERATED by `npm run generate:local-host-bytecode` via `cast interface`.
// DO NOT EDIT — your changes will be overwritten. See internal/generateLocalHostBytecode.ts.

import {FheType} from "../../../../src/contracts/shared/FheType.sol";

interface IHCULimit {

    error AddressEmptyCode(address target);
    error AlreadyBlockHCUWhitelisted(address account);
    error CallerMustBeFHEVMExecutorContract();
    error ERC1967InvalidImplementation(address implementation);
    error ERC1967NonPayable();
    error FailedCall();
    error HCUBlockLimitExceeded();
    error HCUPerBlockBelowMaxPerTx();
    error HCUTransactionDepthLimitExceeded();
    error HCUTransactionLimitExceeded();
    error InvalidInitialization();
    error InvalidZeroHandle();
    error MaxHCUPerTxBelowDepth();
    error NotBlockHCUWhitelisted(address account);
    error NotHostOwner(address sender);
    error NotInitializing();
    error NotInitializingFromEmptyProxy();
    error OnlyScalarOperationsAreSupported();
    error UUPSUnauthorizedCallContext();
    error UUPSUnsupportedProxiableUUID(bytes32 slot);
    error UnsupportedOperation();

    event BlockHCUWhitelistAdded(address indexed account);
    event BlockHCUWhitelistRemoved(address indexed account);
    event HCUPerBlockSet(uint48 hcuPerBlock);
    event Initialized(uint64 version);
    event MaxHCUDepthPerTxSet(uint48 maxHCUDepthPerTx);
    event MaxHCUPerTxSet(uint48 maxHCUPerTx);
    event Upgraded(address indexed implementation);

    function UPGRADE_INTERFACE_VERSION() external view returns (string memory);
    function addToBlockHCUWhitelist(address account) external;
    function checkHCUForCast(FheType resultType, bytes32 ct, bytes32 result, address caller) external;
    function checkHCUForFheAdd(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheBitAnd(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheBitOr(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheBitXor(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheDiv(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheEq(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheGe(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheGt(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheIsIn(
        FheType valueType,
        bytes32 value,
        bytes32[] memory values,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheLe(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheLt(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheMax(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheMin(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheMul(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheNe(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheNeg(FheType resultType, bytes32 ct, bytes32 result, address caller) external;
    function checkHCUForFheNot(FheType resultType, bytes32 ct, bytes32 result, address caller) external;
    function checkHCUForFheRand(FheType resultType, bytes32 result, address caller) external;
    function checkHCUForFheRandBounded(FheType resultType, bytes32 result, address caller) external;
    function checkHCUForFheRem(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheRotl(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheRotr(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheShl(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheShr(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheSub(
        FheType resultType,
        bytes1 scalarByte,
        bytes32 lhs,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForFheSum(FheType resultType, bytes32[] memory values, bytes32 result, address caller) external;
    function checkHCUForIfThenElse(
        FheType resultType,
        bytes32 lhs,
        bytes32 middle,
        bytes32 rhs,
        bytes32 result,
        address caller
    ) external;
    function checkHCUForTrivialEncrypt(FheType resultType, bytes32 result, address caller) external;
    function getBlockMeter() external view returns (uint48 blockNumber, uint48 usedHCU);
    function getFHEVMExecutorAddress() external view returns (address);
    function getGlobalHCUCapPerBlock() external view returns (uint48);
    function getMaxHCUDepthPerTx() external view returns (uint48);
    function getMaxHCUPerTx() external view returns (uint48);
    function getVersion() external pure returns (string memory);
    function initializeFromEmptyProxy(uint48 hcuCapPerBlock, uint48 maxHCUDepthPerTx, uint48 maxHCUPerTx) external;
    function isBlockHCUWhitelisted(address account) external view returns (bool);
    function proxiableUUID() external view returns (bytes32);
    function reinitializeV3() external;
    function removeFromBlockHCUWhitelist(address account) external;
    function setHCUPerBlock(uint48 hcuPerBlock) external;
    function setMaxHCUDepthPerTx(uint48 maxHCUDepthPerTx) external;
    function setMaxHCUPerTx(uint48 maxHCUPerTx) external;
    function upgradeToAndCall(address newImplementation, bytes memory data) external payable;
}
