services:

  orchestrator:
    image: ghcr.io/zama-zws/zws-orchestrator:latest
    build:
      context: ..
      dockerfile: ./docker/orchestrator/Dockerfile

  back:
    image: ghcr.io/zama-zws/zws-back:latest
    build:
      context: ..
      dockerfile: ./docker/back/Dockerfile

  front:
    image: ghcr.io/zama-ai/zws-front:latest
    build:
      context: ..
      dockerfile: ./docker/front/Dockerfile

  email:
    image: ghcr.io/zama-ai/zws-email:latest
    build:
      context: ..
      dockerfile: ./docker/email/Dockerfile

  web3:
    image: ghcr.io/zama-ai/zws-web3:latest
    build:
      context: ..
      dockerfile: ./docker/web3/Dockerfile

  relayer:
    image: ghcr.io/zama-ai/zws-relayer:latest
    build:
      context: ../apps/relayer/
      dockerfile: ../../docker/relayer/Dockerfile
