{{- if .Values.txSender.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coprocessor-tx-sender
    app.kubernetes.io/name: {{ include "txSenderName" . }}
  name: {{ include "txSenderName" . }}
spec:
  replicas: {{ .Values.txSender.replicas }}
  selector:
    matchLabels:
      app: coprocessor-tx-sender
  {{- if .Values.txSender.updateStrategy }}
  strategy:
    {{- toYaml .Values.txSender.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: coprocessor-tx-sender
        app.kubernetes.io/name: {{ include "txSenderName" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
      {{- with .Values.txSender.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.txSender.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.txSender.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.txSender.serviceAccountName }}
      serviceAccountName: {{ .Values.txSender.serviceAccountName }}
      {{- end }}
      containers:
        - name: coprocessor-tx-sender
          image: {{ .Values.txSender.image.name }}:{{ .Values.txSender.image.tag }}
          command: ["transaction_sender"]
          args:
            - --database-url=$(DATABASE_URL)
            - --gateway-url=$(GATEWAY_URL)
            - --input-verification-address=$(INPUT_VERIFICATION_ADDRESS)
            - --ciphertext-commits-address=$(CIPHERTEXT_COMMITS_ADDRESS)
            {{- if .Values.txSender.wallet.awsKms.enabled }}
            - --signer-type=aws-kms
            - --aws-kms-key-id=$(TX_SENDER_AWS_KMS_KEY_ID)
            {{- else }}
            - --signer-type=private-key
            - --private-key=$(TX_SENDER_PRIVATE_KEY)
            {{- end }}
            - --health-check-port={{ .Values.txSender.ports.healthcheck }}
            - --metrics-addr=0.0.0.0:{{ .Values.txSender.ports.metrics }}
            - --log-level={{ .Values.txSender.args.logLevel }}
            - --service-name={{ .Values.txSender.args.serviceName }}
            - --database-pool-size={{ .Values.txSender.args.databasePoolSize }}
            - --database-polling-interval-secs={{ .Values.txSender.args.databasePollingIntervalSecs }}
            - --verify-proof-resp-database-channel={{ .Values.txSender.args.verifyProofRespDatabaseChannel }}
            - --add-ciphertexts-database-channel={{ .Values.txSender.args.addCiphertextsDatabaseChannel }}
            - --allow-handle-database-channel={{ .Values.txSender.args.allowHandleDatabaseChannel }}
            - --verify-proof-resp-batch-limit={{ .Values.txSender.args.verifyProofRespBatchLimit }}
            - --verify-proof-resp-max-retries={{ .Values.txSender.args.verifyProofRespMaxRetries }}
            {{- if .Values.txSender.args.verifyProofRemoveAfterMaxRetries }}
            - --verify-proof-remove-after-max-retries
            {{- end }}
            - --add-ciphertexts-batch-limit={{ .Values.txSender.args.addCiphertextsBatchLimit }}
            - --allow-handle-batch-limit={{ .Values.txSender.args.allowHandleBatchLimit }}
            - --allow-handle-max-retries={{ .Values.txSender.args.allowHandleMaxRetries }}
            - --add-ciphertexts-max-retries={{ .Values.txSender.args.addCiphertextsMaxRetries }}
            - --error-sleep-initial-secs={{ .Values.txSender.args.errorSleepInitialSecs }}
            - --error-sleep-max-secs={{ .Values.txSender.args.errorSleepMaxSecs }}
            - --txn-receipt-timeout-secs={{ .Values.txSender.args.txnReceiptTimeoutSecs }}
            - --review-after-unlimited-retries={{ .Values.txSender.args.reviewAfterUnlimitedRetries }}
            - --provider-max-retries={{ .Values.txSender.args.providerMaxRetries }}
            - --provider-retry-interval={{ .Values.txSender.args.providerRetryInterval }}
            - --health-check-timeout={{ .Values.txSender.args.healthCheckTimeout }}
            - --gas-limit-overprovision-percent={{ .Values.txSender.args.gasLimitOverprovisionPercent }}
            - --graceful-shutdown-timeout={{ .Values.txSender.args.gracefulShutdownTimeout }}
            - --metric-host-txn-latency={{ .Values.txSender.args.metricHostTxnLatency }}
            - --metric-zkproof-txn-latency={{ .Values.txSender.args.metricZkproofTxnLatency }}
            - --gauge-update-interval-secs={{ .Values.txSender.args.gaugeUpdateIntervalSecs }}
            {{- with .Values.txSender.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.commonConfig.databaseUrl | quote }}
            - name: GATEWAY_URL
              value: {{ .Values.commonConfig.gatewayUrl | quote }}
            - name: INPUT_VERIFICATION_ADDRESS
              value: {{ .Values.commonConfig.gatewayContractAddresses.inputVerification | quote }}
            - name: CIPHERTEXT_COMMITS_ADDRESS
              value: {{ .Values.commonConfig.gatewayContractAddresses.ciphertextCommits | quote }}
            {{- if .Values.txSender.wallet.awsKms.enabled }}
            - name: TX_SENDER_AWS_KMS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.txSender.wallet.awsKms.configmap.name | quote }}
                  key: {{ .Values.txSender.wallet.awsKms.configmap.key | quote }}
            {{- else }}
            - name: TX_SENDER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.txSender.wallet.secret.name | quote }}
                  key: {{ .Values.txSender.wallet.secret.key | quote }}
            {{- end }}
          {{- if default .Values.commonConfig.tracing.enabled .Values.txSender.tracing.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.commonConfig.tracing.endpoint | quote }}
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- end }}
          {{- with .Values.commonConfig.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.txSender.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range $portName, $portValue := .Values.txSender.ports }}
            - name: {{ $portName }}
              containerPort: {{ $portValue }}
              protocol: TCP
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.txSender.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.txSender.resources.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.txSender.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.txSender.resources.limits.memory | default "512Mi" }}
          {{- if and .Values.txSender.probes .Values.txSender.probes.liveness.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.txSender.probes.liveness "enabled") | nindent 12 }}
          {{- end }}
          {{- if and .Values.txSender.probes .Values.txSender.probes.readiness.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.txSender.probes.readiness "enabled") | nindent 12 }}
          {{- end }}
{{- end -}}
