{{- range $i, $chain := .Values.chains }}
{{- if (($chain.hostListener).enabled) }}
{{- $useLegacyName := $chain.hostListener.useLegacyName | default false -}}
{{- $deploymentName := ternary (printf "%s-host-listener" $.Release.Name) (printf "%s-host-listener-%s" $.Release.Name $chain.name) $useLegacyName -}}
{{- $appLabel := ternary "coprocessor-host-listener" (printf "coprocessor-host-listener-%s" $chain.name) $useLegacyName -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $appLabel }}
    app.kubernetes.io/name: {{ $deploymentName }}
  name: {{ $deploymentName }}
spec:
  ports:
    - name: metrics
      port: {{ $.Values.hostListenerShared.ports.metrics }}
      targetPort: metrics
    - name: healthcheck
      port: {{ $.Values.hostListenerShared.ports.healthcheck }}
      targetPort: healthcheck
  selector:
    app: {{ $appLabel }}
    app.kubernetes.io/name: {{ $deploymentName }}
  type: ClusterIP
{{- end }}
{{- end }}
