{{- range $i, $chain := .Values.chains }}
{{- if and (($chain.hostListenerCatchupOnly).enabled) $.Values.hostListenerCatchupOnlyShared.serviceMonitor.enabled }}
{{- $useLegacyName := $chain.hostListenerCatchupOnly.useLegacyName | default false -}}
{{- $deploymentName := ternary (printf "%s-host-listener-catchup-only" $.Release.Name) (printf "%s-host-listener-catchup-only-%s" $.Release.Name $chain.name) $useLegacyName -}}
{{- $appLabel := ternary "coprocessor-host-listener-catchup-only" (printf "coprocessor-host-listener-catchup-only-%s" $chain.name) $useLegacyName -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ $appLabel }}
    app.kubernetes.io/name: {{ $deploymentName }}
  name: {{ $deploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ $appLabel }}
      app.kubernetes.io/name: {{ $deploymentName }}
  endpoints:
  - port: metrics
{{- end }}
{{- end }}
