{{- range $i, $chain := .Values.chains }}
{{- if and (($chain.listenerConsumer).enabled) $.Values.listenerConsumerShared.serviceMonitor.enabled }}
{{- $useLegacyName := $chain.listenerConsumer.useLegacyName | default false -}}
{{- $deploymentName := ternary (printf "%s-listener-consumer" $.Release.Name) (printf "%s-listener-consumer-%s" $.Release.Name $chain.name) $useLegacyName -}}
{{- $appLabel := ternary "coprocessor-listener-consumer" (printf "coprocessor-listener-consumer-%s" $chain.name) $useLegacyName -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ $appLabel }}
    app.kubernetes.io/name: {{ $deploymentName }}
  name: {{ $deploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ $appLabel }}
      app.kubernetes.io/name: {{ $deploymentName }}
  endpoints:
  - port: metrics
{{- end }}
{{- end }}
