{{- if .Values.txSender.enabled -}}
{{- $disabled := default (list) .Values.txSender.disabledArgs -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coprocessor-tx-sender
    app.kubernetes.io/name: {{ include "txSenderName" . }}
  name: {{ include "txSenderName" . }}
spec:
  replicas: {{ .Values.txSender.replicas }}
  selector:
    matchLabels:
      app: coprocessor-tx-sender
  {{- if .Values.txSender.updateStrategy }}
  strategy:
    {{- toYaml .Values.txSender.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: coprocessor-tx-sender
        app.kubernetes.io/name: {{ include "txSenderName" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
      {{- with .Values.txSender.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.txSender.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.txSender.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.txSender.serviceAccountName }}
      serviceAccountName: {{ .Values.txSender.serviceAccountName }}
      {{- end }}
      containers:
        - name: coprocessor-tx-sender
          image: {{ .Values.txSender.image.name }}:{{ .Values.txSender.image.tag }}
          command: ["transaction_sender"]
          args:
            {{- if not (has "database-url" $disabled) }}
            - --database-url=$(DATABASE_URL)
            {{- end }}
            {{- if not (has "gateway-url" $disabled) }}
            - --gateway-url=$(GATEWAY_URL)
            {{- end }}
            {{- if not (has "input-verification-address" $disabled) }}
            - --input-verification-address=$(INPUT_VERIFICATION_ADDRESS)
            {{- end }}
            {{- if not (has "ciphertext-commits-address" $disabled) }}
            - --ciphertext-commits-address=$(CIPHERTEXT_COMMITS_ADDRESS)
            {{- end }}
            {{- if not (has "multichain-acl-address" $disabled) }}
            - --multichain-acl-address=$(MULTICHAIN_ACL_ADDRESS)
            {{- end }}
            {{- if not (has "signer-type" $disabled) }}
            {{- if .Values.txSender.wallet.awsKms.enabled }}
            - --signer-type=aws-kms
            {{- else }}
            - --signer-type=private-key
            {{- end }}
            {{- end }}
            {{- if and (not .Values.txSender.wallet.awsKms.enabled) (not (has "private-key" $disabled)) }}
            - --private-key=$(TX_SENDER_PRIVATE_KEY)
            {{- end }}
            {{- if not (has "health-check-port" $disabled) }}
            - --health-check-port={{ .Values.txSender.ports.healthcheck }}
            {{- end }}
            {{- if not (has "metrics-addr" $disabled) }}
            - --metrics-addr=0.0.0.0:{{ .Values.txSender.ports.metrics }}
            {{- end }}
            {{- with .Values.txSender.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            {{- with .Values.commonConfig.databaseUser }}
            - name: DATABASE_USER
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- with .Values.commonConfig.databasePassword }}
            - name: DATABASE_PASSWORD
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- with .Values.commonConfig.databaseEndpoint }}
            - name: DATABASE_ENDPOINT
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            - name: DATABASE_URL
              value: {{ .Values.commonConfig.databaseUrl | quote }}
            {{- with .Values.commonConfig.gatewayUrl }}
            - name: GATEWAY_URL
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- with .Values.commonConfig.gatewayContractAddresses.inputVerification }}
            - name: INPUT_VERIFICATION_ADDRESS
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- with .Values.commonConfig.gatewayContractAddresses.ciphertextCommits }}
            - name: CIPHERTEXT_COMMITS_ADDRESS
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- with .Values.commonConfig.gatewayContractAddresses.multichainAcl }}
            - name: MULTICHAIN_ACL_ADDRESS
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
            {{- if .Values.txSender.wallet.awsKms.enabled }}
            - name: AWS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.txSender.wallet.awsKms.configmap.name | quote }}
                  key: {{ .Values.txSender.wallet.awsKms.configmap.key | quote }}
            {{- else if .Values.txSender.wallet.secret.value }}
            - name: TX_SENDER_PRIVATE_KEY
              value: {{ .Values.txSender.wallet.secret.value | quote }}
            {{- else }}
            - name: TX_SENDER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.txSender.wallet.secret.name | quote }}
                  key: {{ .Values.txSender.wallet.secret.key | quote }}
            {{- end }}
          {{- if default .Values.commonConfig.tracing.enabled .Values.txSender.tracing.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.commonConfig.tracing.endpoint | quote }}
            - name: OTEL_SERVICE_NAME
              {{- if .Values.txSender.tracing.service }}
              value: {{ .Values.txSender.tracing.service | quote }}
              {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
              {{- end }}
          {{- end }}
          {{- with .Values.commonConfig.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.txSender.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range $portName, $portValue := .Values.txSender.ports }}
            - name: {{ $portName }}
              containerPort: {{ $portValue }}
              protocol: TCP
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.txSender.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.txSender.resources.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.txSender.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.txSender.resources.limits.memory | default "512Mi" }}
          {{- if and .Values.txSender.probes .Values.txSender.probes.liveness.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.txSender.probes.liveness "enabled") | nindent 12 }}
          {{- end }}
          {{- if and .Values.txSender.probes .Values.txSender.probes.readiness.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.txSender.probes.readiness "enabled") | nindent 12 }}
          {{- end }}
{{- end -}}
