{{- if .Values.hostListenerCatchupOnly.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coprocessor-host-listener-catchup-only
    app.kubernetes.io/name: {{ include "hostListenerCatchupOnlyName" . }}
  name: {{ include "hostListenerCatchupOnlyName" . }}
spec:
  replicas: {{ .Values.hostListenerCatchupOnly.replicas }}
  selector:
    matchLabels:
      app: coprocessor-host-listener-catchup-only
  {{- if .Values.hostListenerCatchupOnly.updateStrategy }}
  strategy:
    {{- toYaml .Values.hostListenerCatchupOnly.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: coprocessor-host-listener-catchup-only
        app.kubernetes.io/name: {{ include "hostListenerCatchupOnlyName" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
      {{- with .Values.hostListenerCatchupOnly.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostListenerCatchupOnly.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostListenerCatchupOnly.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.hostListenerCatchupOnly.serviceAccountName }}
      serviceAccountName: {{ .Values.hostListenerCatchupOnly.serviceAccountName }}
      {{- end }}
      containers:
        - name: coprocessor-host-listener-catchup-only
          image: {{ .Values.hostListenerCatchupOnly.image.name }}:{{ .Values.hostListenerCatchupOnly.image.tag }}
          command: ["host_listener"]
          args:
            - --database-url=$(DATABASE_URL)
            - --url=$(ETHEREUM_RPC_URL)
            - --acl-contract-address=$(ACL_CONTRACT_ADDRESS)
            - --tfhe-contract-address=$(FHEVM_EXECUTOR_CONTRACT_ADDRESS)
            - --health-port={{ .Values.hostListenerCatchupOnly.ports.healthcheck }}
            - --dependent-ops-max-per-chain={{ int .Values.commonConfig.dependentOpsMaxPerChain }}
            - --log-level={{ .Values.hostListenerCatchupOnly.args.logLevel }}
            - --initial-block-time={{ .Values.hostListenerCatchupOnly.args.initialBlockTime }}
            - --dependence-cache-size={{ .Values.hostListenerCatchupOnly.args.dependenceCacheSize }}
            - --reorg-maximum-duration-in-blocks={{ .Values.hostListenerCatchupOnly.args.reorgMaximumDurationInBlocks }}
            - --service-name={{ .Values.hostListenerCatchupOnly.args.serviceName }}
            - --catchup-finalization-in-blocks={{ .Values.hostListenerCatchupOnly.args.catchupFinalizationInBlocks }}
            {{- if .Values.hostListenerCatchupOnly.args.onlyCatchupLoop }}
            - --only-catchup-loop
            {{- end }}
            - --end-at-block={{ .Values.hostListenerCatchupOnly.args.endAtBlock }}
            - --catchup-loop-sleep-secs={{ .Values.hostListenerCatchupOnly.args.catchupLoopSleepSecs }}
            {{- with .Values.hostListenerCatchupOnly.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.commonConfig.databaseUrl | quote }}
            - name: ETHEREUM_RPC_URL
              value: {{ .Values.commonConfig.hostChainWsUrl | quote }}
            - name: ACL_CONTRACT_ADDRESS
              value: {{ .Values.commonConfig.aclContractAddress | quote }}
            - name: FHEVM_EXECUTOR_CONTRACT_ADDRESS
              value: {{ .Values.commonConfig.fhevmExecutorContractAddress | quote }}
          {{- if default .Values.commonConfig.tracing.enabled .Values.hostListenerCatchupOnly.tracing.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.commonConfig.tracing.endpoint | quote }}
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- end }}
          {{- with .Values.commonConfig.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.hostListenerCatchupOnly.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range $portName, $portValue := .Values.hostListenerCatchupOnly.ports }}
            - name: {{ $portName }}
              containerPort: {{ $portValue }}
              protocol: TCP
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.hostListenerCatchupOnly.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.hostListenerCatchupOnly.resources.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.hostListenerCatchupOnly.resources.limits.cpu | default "500m" }}
              memory: {{ .Values.hostListenerCatchupOnly.resources.limits.memory | default "512Mi" }}
          {{- if and .Values.hostListenerCatchupOnly.probes .Values.hostListenerCatchupOnly.probes.liveness.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.hostListenerCatchupOnly.probes.liveness "enabled") | nindent 12 }}
          {{- end }}
          {{- if and .Values.hostListenerCatchupOnly.probes .Values.hostListenerCatchupOnly.probes.readiness.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.hostListenerCatchupOnly.probes.readiness "enabled") | nindent 12 }}
          {{- end }}
{{- end -}}
