{{- range $i, $chain := .Values.chains }}
{{- if (($chain.hostListenerCatchupOnly).enabled) }}
{{- $deploymentName := ternary (printf "%s-host-listener-catchup-only" $.Release.Name) (printf "%s-host-listener-catchup-only-%s" $.Release.Name $chain.name) (eq $i 0) -}}
{{- $appLabel := ternary "coprocessor-host-listener-catchup-only" (printf "coprocessor-host-listener-catchup-only-%s" $chain.name) (eq $i 0) -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $appLabel }}
    app.kubernetes.io/name: {{ $deploymentName }}
  name: {{ $deploymentName }}
spec:
  ports:
    - name: metrics
      port: {{ $.Values.hostListenerCatchupOnly.ports.metrics }}
      targetPort: metrics
    - name: healthcheck
      port: {{ $.Values.hostListenerCatchupOnly.ports.healthcheck }}
      targetPort: healthcheck
  selector:
    app: {{ $appLabel }}
    app.kubernetes.io/name: {{ $deploymentName }}
  type: ClusterIP
{{- end }}
{{- end }}
