// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

// AUTOGENERATED by `npm run generate:local-host-bytecode`.
// DO NOT EDIT — your changes will be overwritten. See internal/generateLocalHostBytecode.ts.
//
// The localhost stack's identity: the account it is deployed from, the addresses that account produces,
// and the order that produces them. Pairs with LocalHostBytecode.sol, which is compiled against exactly
// these addresses — the two files are halves of one artifact and must be regenerated together.
//
// ACL_ADDRESS, FHEVM_EXECUTOR_ADDRESS and KMS_VERIFIER_ADDRESS are the three values
// library-solidity/config/ZamaConfig.sol compiles into every dApp inheriting its localhost config
// (RULES.md rules 15 and 17), which is why none of this may drift.

/// @dev BIP-39 mnemonic the local stack is deployed with.
string constant MNEMONIC = "adapt mosquito move limb mobile illegal tree voyage juice mosquito burger raise father hope layer";

/// @dev Account index derived from MNEMONIC that deploys the stack (path m/44'/60'/0'/0/5).
uint32 constant DEPLOYER_ADDRESS_INDEX = 5;

/// @dev The deploying account. Must be at nonce DEPLOYER_START_NONCE when the sequence begins.
address constant DEPLOYER_ADDRESS = 0x8B8f5091f8b9817EF69cFC1E8B2f721BafF60DF4;

/// @dev Nonce the sequence starts from — the deployer must have sent no transaction yet.
uint64 constant DEPLOYER_START_NONCE = 0;

/// @dev Contracts created at each nonce, in deploy order.
///   nonce  0  0x34e3eD8472e409dbF8FDf933cA996DC75e4Be126  EmptyUUPSProxyACL
///   nonce  1  0x50157CFfD6bBFA2DECe204a89ec419c23ef5755D  ACL_ADDRESS
///   nonce  2  0xCD3ab3bd6bcc0c0bf3E27912a92043e817B1cf69  EmptyUUPSProxy (shared implementation)
///   nonce  3  0xe3a9105a3a932253A70F126eb1E3b589C643dD24  FHEVM_EXECUTOR_ADDRESS
///   nonce  4  0x901F8942346f7AB3a01F6D7613119Bca447Bb030  KMS_VERIFIER_ADDRESS
///   nonce  5  0x36772142b74871f255CbD7A3e89B401d3e45825f  INPUT_VERIFIER_ADDRESS
///   nonce  6  0x233ff88A48c172d29F675403e6A8e302b0F032D9  HCU_LIMIT_ADDRESS
///   nonce  7  0x44aA028fd264C76BF4A8f8B4d8A5272f6AE25CAc  PROTOCOL_CONFIG_ADDRESS
///   nonce  8  0x216be43148dB537BeddBC268163deb1a802b5553  KMS_GENERATION_ADDRESS
///   nonce  9  0xded0D2a71268DC12622BdD1b55d68a1CB5662327  CLEARTEXT_ARITHMETIC_ADDRESS
///   nonce 10  0x6933Afcf0F4bCE1A611baD0A6FaafF0337a7ba1E  CLEARTEXT_DB_ADDRESS
///   nonce 11  0x590e3330386Fa042843773541aaBb3a45EC3164D  PAUSER_SET_ADDRESS

address constant ACL_ADDRESS = 0x50157CFfD6bBFA2DECe204a89ec419c23ef5755D;
address constant FHEVM_EXECUTOR_ADDRESS = 0xe3a9105a3a932253A70F126eb1E3b589C643dD24;
address constant KMS_VERIFIER_ADDRESS = 0x901F8942346f7AB3a01F6D7613119Bca447Bb030;
address constant INPUT_VERIFIER_ADDRESS = 0x36772142b74871f255CbD7A3e89B401d3e45825f;
address constant HCU_LIMIT_ADDRESS = 0x233ff88A48c172d29F675403e6A8e302b0F032D9;
address constant PROTOCOL_CONFIG_ADDRESS = 0x44aA028fd264C76BF4A8f8B4d8A5272f6AE25CAc;
address constant KMS_GENERATION_ADDRESS = 0x216be43148dB537BeddBC268163deb1a802b5553;
address constant PAUSER_SET_ADDRESS = 0x590e3330386Fa042843773541aaBb3a45EC3164D;
address constant CLEARTEXT_ARITHMETIC_ADDRESS = 0xded0D2a71268DC12622BdD1b55d68a1CB5662327;
address constant CLEARTEXT_DB_ADDRESS = 0x6933Afcf0F4bCE1A611baD0A6FaafF0337a7ba1E;
