[package]
name = "gateway-stress"
version = "0.15.0"
edition = "2024"

[dependencies]
fhevm_gateway_bindings = { path = "../../gateway-contracts/rust_bindings", default-features = false }
user-decryption-signature = { path = "../../shared/user-decryption-signature" }

alloy = { version = "2.2.0", default-features = false, features = [
    "essentials",
    "json-rpc",
    "reqwest-rustls-tls",
    "std",
    "provider-ws",
    "signer-aws",
    "signer-mnemonic",
] }
anyhow = "1.0.104"
async-trait = { version = "0.1.91", default-features = false }
clap = { version = "4.6.4", features = ["cargo", "derive"] }
config = { version = "0.15.25", default-features = false, features = ["toml"] }
csv = { version = "1.4.0", default-features = false }
futures = { version = "0.3.33", default-features = false }
humantime = "2.4.0"
humantime-serde = "1.1.1"
indicatif = { version = "0.18.6", default-features = true, features = [
    "tokio",
] }
rustls = "0.23.42"
serde = { version = "1.0.229", default-features = false, features = [
    "derive",
    "std",
] }
serde_json = { version = "1.0.151", default-features = false, features = [
    "std",
] }
sqlx = { version = "0.8.6", default-features = false, features = [
    "chrono",
    "derive",
    "macros",
    "postgres",
    "runtime-tokio",
    "time",
    "tls-rustls",
] }
tokio = { version = "1.53.1", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "sync",
] }
tokio-util = "0.7.19"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", default-features = true, features = [
    "env-filter",
] }
rand = "0.10.2"
