export const DEMO_APY_PERCENT = 7;
export const DEMO_RATE_WINDOW_DAYS = 30;
export const DEMO_TARGET_PRICE_NUMERATOR = 107n;
export const DEMO_TARGET_PRICE_DENOMINATOR = 100n;
export const DEMO_TARGET_SHARE_PRICE =
  Number(DEMO_TARGET_PRICE_NUMERATOR) / Number(DEMO_TARGET_PRICE_DENOMINATOR);
