/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HTTPPublicDecryptInterface extends Interface {
  getFunction(
    nameOrSignature: "xAddress" | "xBool" | "xUint32"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "xAddress", values?: undefined): string;
  encodeFunctionData(functionFragment: "xBool", values?: undefined): string;
  encodeFunctionData(functionFragment: "xUint32", values?: undefined): string;

  decodeFunctionResult(functionFragment: "xAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xUint32", data: BytesLike): Result;
}

export interface HTTPPublicDecrypt extends BaseContract {
  connect(runner?: ContractRunner | null): HTTPPublicDecrypt;
  waitForDeployment(): Promise<this>;

  interface: HTTPPublicDecryptInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  xAddress: TypedContractMethod<[], [string], "view">;

  xBool: TypedContractMethod<[], [string], "view">;

  xUint32: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "xAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "xBool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "xUint32"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
