/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  E2ECoprocessorConfig,
  E2ECoprocessorConfigInterface,
} from "../../../contracts/E2ECoprocessorConfigLocal.sol/E2ECoprocessorConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061002d61002261003260201b60201c565b6100d860201b60201c565b610260565b61003a6101fd565b60405180606001604052807350157cffd6bbfa2dece204a89ec419c23ef5755d73ffffffffffffffffffffffffffffffffffffffff16815260200173e3a9105a3a932253a70f126eb1e3b589c643dd2473ffffffffffffffffffffffffffffffffffffffff16815260200173901f8942346f7ab3a01f6d7613119bca447bb03073ffffffffffffffffffffffffffffffffffffffff16815250905090565b6100e7816100ea60201b60201c565b50565b60006100fa6101d560201b60201c565b905081600001518160000160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555081602001518160010160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555081604001518160020160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505050565b60007f9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e4649700905090565b6040518060600160405280600073ffffffffffffffffffffffffffffffffffffffff168152602001600073ffffffffffffffffffffffffffffffffffffffff168152602001600073ffffffffffffffffffffffffffffffffffffffff1681525090565b603f8061026e6000396000f3fe6080604052600080fdfea264697066735822122000724455da26f543a4b848088987eb1a058fa28f6703c0b0705091fe1f11a7bb64736f6c63430008180033";

type E2ECoprocessorConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: E2ECoprocessorConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class E2ECoprocessorConfig__factory extends ContractFactory {
  constructor(...args: E2ECoprocessorConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      E2ECoprocessorConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): E2ECoprocessorConfig__factory {
    return super.connect(runner) as E2ECoprocessorConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): E2ECoprocessorConfigInterface {
    return new Interface(_abi) as E2ECoprocessorConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): E2ECoprocessorConfig {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as E2ECoprocessorConfig;
  }
}
