name: "[PR] Helm Chart Lint"

on:
  pull_request:
    branches: ['*']
    paths:
      - 'charts/**'
      - '.github/workflows/helm-lint.yml'
jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Lint
        uses: WyriHaximus/github-action-helm3@fc4ba26e75cf5d08182c6ce3b72623c8bfd7272b # v3.1.0
        with:
          exec: helm lint charts/*