//! The normative Connector-authorization vector set: generator and runner in one place.
//!
//! The set is owned by this file and committed as JSON next to the schema every other
//! implementation includes. Generation and checking share one code path — the tests build the set
//! in memory and compare it against the committed file, and the same build is written to disk when
//! the update gate is set:
//!
//! ```text
//! bash solana/scripts/update-connector-auth-vectors.sh
//! ```
//!
//! There is no separate generator binary, for the reason PR1 recorded: a generator that is not the
//! runner drifts from it, and then the committed file agrees with neither.
//!
//! ## What this set is for, and what it is not for
//!
//! Every record here is also covered by a Rust test in this suite, so for this implementation the
//! set adds review value rather than pinning value: it is generated by the same builders the tests
//! use. What it does add is a statement of the host policy that can be read, reviewed and consumed
//! outside Rust — the SDK can check its pre-checks against the window, scope, budget and
//! deployment records, and a future host implementation has a table of expected outcomes to
//! converge on rather than a suite to reimplement.
//!
//! Two disciplines are enforced on the set itself:
//!
//! * a rejecting record is derived from an accepted one by exactly one documented mutation, and the
//!   runner checks that the base is authorized — so "this request is rejected" cannot be passing
//!   for an unrelated reason;
//! * every rule in the dictionary is exercised by some record, and every rule some record declares
//!   is one the Connector actually produces. Both directions, or a regeneration could quietly drop
//!   a class.

mod solana_support;

#[allow(dead_code)]
#[path = "../../../../solana/test-fixtures/connector-auth/connector_auth_vectors.rs"]
mod schema;

use kms_worker::core::solana::{
    delegation::DelegationFailure,
    deployment::{DeploymentFailure, SOLANA_CHAIN_TYPE_BIT},
    encrypted_value_account::EncryptedValueAccountFailure,
    failure::{AuthorizationFailure, FailureClass as ConnectorClass},
    handle_binding::HandleBindingFailure,
    kms_pair::{KmsPairFailure, KmsPairValidator},
    pipeline::{AuthorizationContext, authorize_request},
    request::{
        MAX_REQUEST_HANDLES, RequestFormError, SolanaHandleEntryWire, SolanaUserDecryptRequest,
        SolanaUserDecryptRequestWire,
    },
    snapshot::SnapshotAccount,
    watermark::{WatermarkFailure, WindowFailure, permit_invalidation_address},
};
use kms_worker::core::solana_acl::SolanaPubkeyBytes;
use schema::{
    CONNECTOR_AUTH_VECTOR_SCHEMA, ConnectorAuthVector, ConnectorAuthVectorFile, Deployment,
    FailureClass, KmsPairStatus, Observation, RecordedAccount, VectorResult, WireHandleEntry,
    WirePermit, WireRequest, from_hex, rule, to_hex,
};
use solana_support::*;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use zama_solana_acl::{MmrProof, historical_access_leaf_commitment};
use zama_solana_permit::PermitWireFields;
use zama_solana_request::{decode_solana_request, encode_solana_request};

/// Setting this rewrites the committed file from the in-memory build.
const UPDATE_ENV: &str = "ZAMA_UPDATE_CONNECTOR_AUTH_VECTORS";

/// The observation every record is authorized at, unless it says otherwise.
const OBSERVED_SLOT: u64 = 500;
/// The name the transport-key table gives the one key this set uses.
const TRANSPORT_KEY_NAME: &str = "reference-transport-key";

fn vector_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../solana/test-fixtures/connector-auth/connector_auth_v1.json")
}

// ---------------------------------------------------------------------------
// A scenario: a request, the state it is authorized against, and the expected outcome
// ---------------------------------------------------------------------------

struct Scenario {
    name: &'static str,
    comment: &'static str,
    result: VectorResult,
    rule: Option<&'static str>,
    class: Option<FailureClass>,
    derived_from: Option<&'static str>,
    mutation: Option<&'static str>,
    request: SolanaUserDecryptRequestWire,
    world: World,
    now: u64,
    kms_pair_status: KmsPairStatus,
}

impl Scenario {
    /// An accepted record.
    fn accepted(
        name: &'static str,
        comment: &'static str,
        request: SolanaUserDecryptRequestWire,
        world: World,
    ) -> Self {
        Self {
            name,
            comment,
            result: VectorResult::Valid,
            rule: None,
            class: None,
            derived_from: None,
            mutation: None,
            request,
            world,
            now: NOW_INSIDE_WINDOW,
            kms_pair_status: KmsPairStatus::Servable,
        }
    }

    /// A rejecting record, derived from an accepted one by one mutation.
    ///
    /// Eight arguments, deliberately: name, comment, base, mutation, rule, class, request, state
    /// are exactly what a record is, and grouping some of them into a struct would move the
    /// argument list into the call site without making it shorter. The same suppression is used by
    /// the permit crate for the same reason.
    #[allow(clippy::too_many_arguments)]
    fn rejected(
        name: &'static str,
        comment: &'static str,
        derived_from: &'static str,
        mutation: &'static str,
        rule: &'static str,
        class: FailureClass,
        request: SolanaUserDecryptRequestWire,
        world: World,
    ) -> Self {
        Self {
            name,
            comment,
            result: VectorResult::Invalid,
            rule: Some(rule),
            class: Some(class),
            derived_from: Some(derived_from),
            mutation: Some(mutation),
            request,
            world,
            now: NOW_INSIDE_WINDOW,
            kms_pair_status: KmsPairStatus::Servable,
        }
    }

    fn at_time(mut self, now: u64) -> Self {
        self.now = now;
        self
    }

    fn with_kms_status(mut self, status: KmsPairStatus) -> Self {
        self.kms_pair_status = status;
        self
    }

    fn recorded_as_acceptable(mut self, comment: &'static str) -> Self {
        self.result = VectorResult::Acceptable;
        self.comment = comment;
        self
    }
}

// ---------------------------------------------------------------------------
// The set
// ---------------------------------------------------------------------------

/// The reference direct request: the signer's own live handle, in a signed domain.
fn reference_direct() -> (
    Wallet,
    EncryptedValueAccountFixture,
    [u8; 32],
    SolanaUserDecryptRequestWire,
    World,
) {
    let wallet = Wallet::new(1);
    let live = handle(0x10, FHE_TYPE_UINT64);
    let encrypted_value_account = EncryptedValueAccountFixture::new(live, &[wallet.pubkey()]);
    let request = RequestBuilder::new(&wallet)
        .direct_current(&encrypted_value_account, live)
        .wire();
    let world = World::at_slot(OBSERVED_SLOT)
        .with_encrypted_value_account(&encrypted_value_account)
        .with_watermark(wallet.pubkey(), 0);
    (wallet, encrypted_value_account, live, request, world)
}

/// The reference delegated request: a handle the delegator owns, used by the signer.
fn reference_delegated() -> (
    Wallet,
    Wallet,
    EncryptedValueAccountFixture,
    [u8; 32],
    DelegationFixture,
    SolanaUserDecryptRequestWire,
    World,
) {
    let signer = Wallet::new(1);
    let delegator = Wallet::new(2);
    let live = handle(0x20, FHE_TYPE_UINT64);
    let encrypted_value_account = EncryptedValueAccountFixture::new(live, &[delegator.pubkey()]);
    let delegation = DelegationFixture::live(delegator.pubkey(), signer.pubkey(), OBSERVED_SLOT);
    let request = RequestBuilder::new(&signer)
        .delegated_current(&encrypted_value_account, live, delegator.pubkey())
        .wire();
    let world = World::at_slot(OBSERVED_SLOT)
        .with_encrypted_value_account(&encrypted_value_account)
        .with_watermark(signer.pubkey(), 0)
        .with_delegation(&delegation);
    (
        signer,
        delegator,
        encrypted_value_account,
        live,
        delegation,
        request,
        world,
    )
}

/// An encrypted value account whose handle was replaced once, and the proof of the sealed leaf.
fn replaced_encrypted_value_account(
    tag: u8,
    subject: SolanaPubkeyBytes,
) -> (EncryptedValueAccountFixture, [u8; 32], MmrProof) {
    let sealed = handle(tag, FHE_TYPE_UINT64);
    let mut encrypted_value_account = EncryptedValueAccountFixture::new(sealed, &[subject]);
    encrypted_value_account.update(handle(tag.wrapping_add(1), FHE_TYPE_UINT64));
    let proof = encrypted_value_account.proof(0);
    (encrypted_value_account, sealed, proof)
}

fn accepting_scenarios() -> Vec<Scenario> {
    let mut out = Vec::new();

    let (wallet, _encrypted_value_account, _live, request, world) = reference_direct();
    out.push(Scenario::accepted(
        "direct-current",
        "The reference request: the signer names their own live handle, is a current member of its \
         encrypted value account, and the encrypted value account's domain is in the signed scope.",
        request,
        world,
    ));

    let (_signer, _delegator, _encrypted_value_account, _live, _delegation, request, world) =
        reference_delegated();
    out.push(Scenario::accepted(
        "delegated-current",
        "A handle owned by a delegator, used by the signer under a live delegation for the \
         encrypted value account's authority. The authorized subject is the delegator.",
        request,
        world,
    ));

    // The same request, authorized by the delegator's wildcard row instead: no row exists for this
    // encrypted value account's authority at all.
    let (
        wildcard_signer,
        wildcard_delegator,
        wildcard_encrypted_value_account,
        wildcard_live,
        _,
        _,
        _,
    ) = reference_delegated();
    let wildcard_row = DelegationFixture::live_wildcard(
        wildcard_delegator.pubkey(),
        wildcard_signer.pubkey(),
        OBSERVED_SLOT,
    );
    out.push(Scenario::accepted(
        "delegated-via-wildcard-row",
        "A delegator grants across every authority of theirs with one row carrying the reserved \
         sentinel instead of an encrypted value account authority. It authorizes an encrypted \
         value account that has no authority-specific row, exactly as the EVM ACL's wildcard \
         delegation does. The consequence is part of the rule: revoking the authority-specific \
         row does not stop a delegate who holds this one.",
        RequestBuilder::new(&wildcard_signer)
            .delegated_current(
                &wildcard_encrypted_value_account,
                wildcard_live,
                wildcard_delegator.pubkey(),
            )
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&wildcard_encrypted_value_account)
            .with_watermark(wildcard_signer.pubkey(), 0)
            .with_delegation(&wildcard_row),
    ));

    let (encrypted_value_account, sealed, proof) =
        replaced_encrypted_value_account(0x30, wallet.pubkey());
    out.push(Scenario::accepted(
        "historical-after-handle-update",
        "The handle has been replaced, and the leaf sealed for the signer at that moment proves \
         the access. No new wallet signature is involved: proofs live outside the permit.",
        RequestBuilder::new(&wallet)
            .historical(&encrypted_value_account, sealed, wallet.pubkey(), &proof, 1)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    // Two handle updates, a proof of the first leaf, then a third update that does not merge
    // the proof's peak.
    let first = handle(0x40, FHE_TYPE_UINT64);
    let mut drifted = EncryptedValueAccountFixture::new(first, &[wallet.pubkey()]);
    drifted.update(handle(0x41, FHE_TYPE_UINT64));
    drifted.update(handle(0x42, FHE_TYPE_UINT64));
    let drifted_proof = drifted.proof(0);
    let claimed_before_append = drifted.encrypted_value.leaf_count;
    drifted.update(handle(0x43, FHE_TYPE_UINT64));
    out.push(Scenario::accepted(
        "historical-proof-predating-a-non-merging-append",
        "The proof was built against an earlier leaf count and the append that followed left its \
         peak alone, so it still verifies. Verification comes first and age alone is not a failure: \
         rejecting this would fail valid proofs after every write.",
        RequestBuilder::new(&wallet)
            .historical(
                &drifted,
                first,
                wallet.pubkey(),
                &drifted_proof,
                claimed_before_append,
            )
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&drifted)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let foreign_domain: SolanaPubkeyBytes = [0x61; 32];
    let permissive_handle = handle(0x50, FHE_TYPE_UINT64);
    let permissive_encrypted_value_account = EncryptedValueAccountFixture::in_domain(
        foreign_domain,
        AUTHORITY,
        LABEL,
        permissive_handle,
        &[wallet.pubkey()],
    );
    out.push(Scenario::accepted(
        "permissive-scope-foreign-domain",
        "An empty signed domain list is permissive: the domain rule is skipped entirely, so an \
         encrypted value account of any domain is in scope. Membership still has to hold.",
        RequestBuilder::new(&wallet)
            .permit(PermitBuilder::new(wallet.pubkey()).permissive())
            .direct_current(&permissive_encrypted_value_account, permissive_handle)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&permissive_encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let repeated = handle(0x60, FHE_TYPE_UINT64);
    let repeated_encrypted_value_account =
        EncryptedValueAccountFixture::new(repeated, &[wallet.pubkey()]);
    out.push(Scenario::accepted(
        "duplicate-handle",
        "Naming the same handle twice is legal: each occurrence counts toward the budget, is \
         authorized independently, and is bound at its own position by the response.",
        RequestBuilder::new(&wallet)
            .direct_current(&repeated_encrypted_value_account, repeated)
            .direct_current(&repeated_encrypted_value_account, repeated)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&repeated_encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    // A mixed batch: the signer's own handle plus handles of two different delegators.
    let signer = Wallet::new(1);
    let first_delegator = Wallet::new(2);
    let second_delegator = Wallet::new(3);
    let own = handle(0x70, FHE_TYPE_UINT64);
    let own_encrypted_value_account = EncryptedValueAccountFixture::new(own, &[signer.pubkey()]);
    // Distinct labels give distinct encrypted value IDs and therefore distinct encrypted value
    // accounts. Note which byte is picked: `LABEL` already begins with `b'b'`, so reaching for that
    // letter here would silently give this encrypted value account the default one's address, one
    // account would overwrite the other in the world, and the record would stop being a mixed batch
    // at all.
    let mut label_a = LABEL;
    label_a[0] = b'a';
    let mut label_b = LABEL;
    label_b[0] = b'c';
    let handle_a = handle(0x71, FHE_TYPE_UINT64);
    let handle_b = handle(0x72, FHE_TYPE_UINT64);
    let encrypted_value_account_a = EncryptedValueAccountFixture::in_domain(
        DOMAIN,
        AUTHORITY,
        label_a,
        handle_a,
        &[first_delegator.pubkey()],
    );
    let encrypted_value_account_b = EncryptedValueAccountFixture::in_domain(
        DOMAIN,
        AUTHORITY,
        label_b,
        handle_b,
        &[second_delegator.pubkey()],
    );
    let delegation_a =
        DelegationFixture::live(first_delegator.pubkey(), signer.pubkey(), OBSERVED_SLOT);
    let delegation_b =
        DelegationFixture::live(second_delegator.pubkey(), signer.pubkey(), OBSERVED_SLOT);
    assert_eq!(
        BTreeSet::from([
            own_encrypted_value_account.account_key,
            encrypted_value_account_a.account_key,
            encrypted_value_account_b.account_key
        ])
        .len(),
        3,
        "the three encrypted value accounts of the mixed batch must be three accounts, or the record is not the \
         batch it claims to be"
    );
    out.push(Scenario::accepted(
        "mixed-direct-and-two-delegators",
        "One request freely mixes a direct entry with entries from two different delegators. There \
         is no per-request mode and no separate delegated route.",
        RequestBuilder::new(&signer)
            .direct_current(&own_encrypted_value_account, own)
            .delegated_current(
                &encrypted_value_account_a,
                handle_a,
                first_delegator.pubkey(),
            )
            .delegated_current(
                &encrypted_value_account_b,
                handle_b,
                second_delegator.pubkey(),
            )
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&own_encrypted_value_account)
            .with_encrypted_value_account(&encrypted_value_account_a)
            .with_encrypted_value_account(&encrypted_value_account_b)
            .with_watermark(signer.pubkey(), 0)
            .with_delegation(&delegation_a)
            .with_delegation(&delegation_b),
    ));

    // Many handles in one request. There is no limit here to sit on the boundary of — the request
    // budget is enforced on chain, before the request exists — so the count is a plain number,
    // large enough that the read plan covers many accounts at once.
    const MANY_HANDLES: u16 = 32;
    let mut many_builder = RequestBuilder::new(&wallet);
    let mut many_world = World::at_slot(OBSERVED_SLOT).with_watermark(wallet.pubkey(), 0);
    for index in 0..MANY_HANDLES {
        let mut label = LABEL;
        label[0..2].copy_from_slice(&index.to_be_bytes());
        let mut bytes = handle(0x80, FHE_TYPE_UINT64);
        bytes[0..2].copy_from_slice(&index.to_be_bytes());
        let encrypted_value_account = EncryptedValueAccountFixture::in_domain(
            DOMAIN,
            AUTHORITY,
            label,
            bytes,
            &[wallet.pubkey()],
        );
        many_builder = many_builder.direct_current(&encrypted_value_account, bytes);
        many_world = many_world.with_encrypted_value_account(&encrypted_value_account);
    }
    out.push(Scenario::accepted(
        "many-handles-in-one-request",
        "One request naming many handles of many encrypted value accounts. No layer of the Connector caps the \
         count: the system-wide decryption budget is summed and enforced by the Gateway entry \
         point on chain, so a request that exists has already passed it.",
        many_builder.wire(),
        many_world,
    ));

    let (absent_wallet, absent_encrypted_value_account, absent_live, absent_request, _) =
        reference_direct();
    out.push(Scenario::accepted(
        "absent-invalidation-record",
        "A user who has never revoked anything has no invalidation record, and its absence reads as \
         a watermark of zero rather than as a missing initialisation step.",
        {
            let _ = (absent_live, &absent_encrypted_value_account);
            absent_request
        },
        World::at_slot(OBSERVED_SLOT).with_encrypted_value_account(&absent_encrypted_value_account),
    ));
    let _ = absent_wallet;

    let (prefunded_wallet, prefunded_encrypted_value_account, _, prefunded_request, _) =
        reference_direct();
    let (prefunded_key, _) = invalidation_address(prefunded_wallet.pubkey());
    out.push(Scenario::accepted(
        "prefunded-invalidation-address",
        "The invalidation address of a user who has never revoked, holding the account a bare \
         transfer leaves behind: System-program-owned and empty. Every address in this path is \
         derivable by anyone, so this is the same \"the host program never wrote here\" observation \
         as no account at all, and it is not the user's choice which of the two they are presented \
         as. An implementation that reads it any other way sells a terminal denial of a user's \
         every request for the price of one transfer.",
        prefunded_request,
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&prefunded_encrypted_value_account)
            .with_account(prefunded_key, prefunded_account()),
    ));

    // The recorded weakness: a permit pre-signed with a start later than a revocation survives it.
    let (weak_wallet, weak_encrypted_value_account, weak_live, _, _) = reference_direct();
    let revocation_before_the_start = DEFAULT_START - 100;
    out.push(
        Scenario::accepted(
            "future-start-permit-outliving-a-revocation",
            "",
            RequestBuilder::new(&weak_wallet)
                .direct_current(&weak_encrypted_value_account, weak_live)
                .wire(),
            World::at_slot(OBSERVED_SLOT)
                .with_encrypted_value_account(&weak_encrypted_value_account)
                .with_watermark(weak_wallet.pubkey(), revocation_before_the_start),
        )
        .recorded_as_acceptable(
            "The permit's window opens after a revocation that was performed before it opened, so \
             the revocation does not reach it and the request is authorized. This is a recorded \
             weakness of the watermark design, accepted for parity with the EVM path and filed as \
             a follow-up for both — not a property this set endorses.",
        ),
    );

    out
}

fn deployment_and_permit_state_scenarios() -> Vec<Scenario> {
    let mut out = Vec::new();
    let (wallet, encrypted_value_account, live, _, world) = reference_direct();

    out.push(Scenario::rejected(
        "wrong-host-program",
        "A permit signed for another host program authorizes nothing here, even on the right \
         cluster.",
        "direct-current",
        "the permit's verifying program id is replaced with another program",
        rule::DEPLOYMENT_PROGRAM_MISMATCH,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .permit(PermitBuilder::new(wallet.pubkey()).deployment_pair([0x55; 32], CHAIN_ID))
            .direct_current(&encrypted_value_account, live)
            .wire(),
        world.clone(),
    ));

    let other_chain = SOLANA_CHAIN_TYPE_BIT | 0xdead_beef;
    let other_chain_handle = handle_on_chain(0x11, FHE_TYPE_UINT64, other_chain);
    let other_chain_encrypted_value_account =
        EncryptedValueAccountFixture::new(other_chain_handle, &[wallet.pubkey()]);
    out.push(Scenario::rejected(
        "wrong-host-chain-id",
        "A permit signed for another cluster authorizes nothing here, even under the same program \
         id — which is why the cluster is signed at all.",
        "direct-current",
        "the permit's chain id, and the chain id embedded in its handle, name another cluster",
        rule::DEPLOYMENT_CHAIN_ID_MISMATCH,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .permit(PermitBuilder::new(wallet.pubkey()).deployment_pair(PROGRAM_ID, other_chain))
            .direct_current(&other_chain_encrypted_value_account, other_chain_handle)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&other_chain_encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let foreign_chain = SOLANA_CHAIN_TYPE_BIT | 0x1234;
    out.push(Scenario::rejected(
        "mixed-embedded-chain-ids",
        "Handles of one request must embed one chain id. A mixed batch is refused rather than \
         resolved by taking the first handle as the truth.",
        "direct-current",
        "a second entry is appended whose handle embeds another cluster",
        rule::MIXED_EMBEDDED_CHAIN_IDS,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .direct_current(&encrypted_value_account, live)
            .entry(
                handle_on_chain(0x12, FHE_TYPE_UINT64, foreign_chain),
                wallet.pubkey(),
                encrypted_value_account.encrypted_value_id(),
                0,
                Vec::new(),
            )
            .wire(),
        world.clone(),
    ));

    let elsewhere = handle_on_chain(0x13, FHE_TYPE_UINT64, foreign_chain);
    let elsewhere_encrypted_value_account =
        EncryptedValueAccountFixture::new(elsewhere, &[wallet.pubkey()]);
    out.push(Scenario::rejected(
        "handle-of-another-cluster",
        "Handles agreeing among themselves is not enough: every embedded chain id must equal the \
         signed one, or the request is about another cluster's ciphertexts.",
        "direct-current",
        "the entry's handle embeds another cluster while the permit still names this one",
        rule::EMBEDDED_CHAIN_ID_MISMATCH,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .direct_current(&elsewhere_encrypted_value_account, elsewhere)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&elsewhere_encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let (_, _, _, expired_request, expired_world) = reference_direct();
    out.push(
        Scenario::rejected(
            "expired-permit",
            "The validity window has closed. No later observation makes a permit younger.",
            "direct-current",
            "the request is authorized after the permit's window ends",
            rule::WINDOW_EXPIRED,
            FailureClass::Terminal,
            expired_request,
            expired_world,
        )
        .at_time(DEFAULT_START + DEFAULT_DURATION + 1),
    );

    let (_, _, _, early_request, early_world) = reference_direct();
    out.push(
        Scenario::rejected(
            "not-yet-valid-permit",
            "The window has not opened. Transient, because this is the one rejection that the \
             passage of time repairs on its own.",
            "direct-current",
            "the request is authorized before the permit's window starts",
            rule::WINDOW_NOT_YET_VALID,
            FailureClass::Transient,
            early_request,
            early_world,
        )
        .at_time(DEFAULT_START - 1),
    );

    let (_, invalidated_encrypted_value_account, _, invalidated_request, _) = reference_direct();
    out.push(Scenario::rejected(
        "invalidated-permit",
        "The permit started before its signer's last revocation, so it is dead permanently. This is \
         the mechanism behind revoking every outstanding signature with one transaction.",
        "direct-current",
        "the signer's invalidation record holds a watermark above the permit's start",
        rule::PERMIT_INVALIDATED,
        FailureClass::Terminal,
        invalidated_request,
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&invalidated_encrypted_value_account)
            .with_watermark(Wallet::new(1).pubkey(), DEFAULT_START + 1),
    ));

    let (_, foreign_record_encrypted_value_account, _, foreign_record_request, _) =
        reference_direct();
    let (watermark_key, _) = permit_invalidation_address(PROGRAM_ID, Wallet::new(1).pubkey());
    out.push(Scenario::rejected(
        "invalidation-record-of-another-user",
        "The invalidation record's contents are checked against the address it was read from: a \
         record naming another user is refused rather than read as that user's watermark, and \
         refused rather than read as zero.",
        "direct-current",
        "the signer's invalidation address holds a record naming a different user",
        rule::WATERMARK_RECORD_INVALID,
        FailureClass::Terminal,
        foreign_record_request,
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&foreign_record_encrypted_value_account)
            .with_account(
                watermark_key,
                invalidation_account(Wallet::new(9).pubkey(), DEFAULT_START),
            ),
    ));

    let (_, _, _, destroyed_request, destroyed_world) = reference_direct();
    out.push(
        Scenario::rejected(
            "destroyed-kms-epoch",
            "Governance destroyed the epoch the permit signed. Transient, and deliberately so: the \
             Connector learns about the pair from a single boolean that is true only when the epoch \
             is active and belongs to the signed context, so a destroyed epoch is indistinguishable \
             from one that is not active yet. The request is retried within the attempt budget and \
             never succeeds — inherited behaviour of the pair validation the EVM path shares, not a \
             decision of the Solana path, and fail-closed either way.",
            "direct-current",
            "the KMS management state reports the signed epoch as destroyed",
            rule::KMS_PAIR_UNSERVABLE,
            FailureClass::Transient,
            destroyed_request,
            destroyed_world,
        )
        .with_kms_status(KmsPairStatus::EpochDestroyed),
    );

    let (_, _, _, pending_request, pending_world) = reference_direct();
    out.push(
        Scenario::rejected(
            "not-yet-active-kms-epoch",
            "The epoch exists but is not active yet. The reference case of the transient outcome, \
             and the reason the two records around it share both its rule and its class: all three \
             arrive as the same boolean.",
            "direct-current",
            "the KMS management state reports the signed epoch as not active yet",
            rule::KMS_PAIR_UNSERVABLE,
            FailureClass::Transient,
            pending_request,
            pending_world,
        )
        .with_kms_status(KmsPairStatus::EpochNotYetActive),
    );

    let (_, _, _, other_context_request, other_context_world) = reference_direct();
    out.push(
        Scenario::rejected(
            "kms-epoch-of-another-context",
            "The signed epoch belongs to a different context, so the pair will never be servable — \
             and it is transient for the same reason as the destroyed epoch: the view returns one \
             boolean, and no view exposes the epoch's context on its own.",
            "direct-current",
            "the KMS management state reports the signed epoch as belonging to another context",
            rule::KMS_PAIR_UNSERVABLE,
            FailureClass::Transient,
            other_context_request,
            other_context_world,
        )
        .with_kms_status(KmsPairStatus::EpochOfAnotherContext),
    );

    out
}

fn request_form_scenarios() -> Vec<Scenario> {
    let mut out = Vec::new();
    let (wallet, encrypted_value_account, live, _, world) = reference_direct();

    out.push(Scenario::rejected(
        "empty-handle-list",
        "A request naming no handles has nothing to authorize and nothing for a response to bind.",
        "direct-current",
        "the handle list is emptied",
        rule::EMPTY_HANDLES,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet).wire(),
        world.clone(),
    ));

    let mut past_cap = RequestBuilder::new(&wallet);
    for _ in 0..=MAX_REQUEST_HANDLES {
        past_cap = past_cap.direct_current(&encrypted_value_account, live);
    }
    out.push(Scenario::rejected(
        "handle-list-past-the-cap",
        "Every rule is evaluated against one atomic account snapshot, and a standard RPC node \
         serves at most 100 accounts per call — in the worst case three per entry plus the \
         signer's invalidation record, so the list is capped at 33. The Gateway refuses a longer \
         request at admission, before the fee; the Connector rejects it too, so the snapshot's \
         readability is its own invariant rather than an assumption about the contract upstream. \
         Duplicates count: the cap is on the list, not on the distinct handles in it.",
        "direct-current",
        "the live handle is repeated until the list is one entry past the cap",
        rule::TOO_MANY_HANDLES,
        FailureClass::Terminal,
        past_cap.wire(),
        world.clone(),
    ));

    let (proof_encrypted_value_account, sealed, proof) =
        replaced_encrypted_value_account(0x90, wallet.pubkey());
    let proof_world = World::at_slot(OBSERVED_SLOT)
        .with_encrypted_value_account(&proof_encrypted_value_account)
        .with_watermark(wallet.pubkey(), 0);

    let mut trailing = borsh::to_vec(&proof).expect("a proof serializes");
    trailing.extend_from_slice(&[0xde, 0xad]);
    out.push(Scenario::rejected(
        "access-proof-with-trailing-bytes",
        "A proof followed by extra bytes is refused — unlike an account followed by extra bytes, \
         which is legal. Two byte strings for one proof would leave two implementations \
         disagreeing about whether they hold the same request.",
        "historical-after-handle-update",
        "two bytes are appended to the entry's access proof",
        rule::ACCESS_PROOF_TRAILING_BYTES,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .entry(
                sealed,
                wallet.pubkey(),
                proof_encrypted_value_account.encrypted_value_id(),
                1,
                trailing,
            )
            .wire(),
        proof_world.clone(),
    ));

    let oversized = MmrProof {
        leaf_index: 0,
        siblings: vec![[0; 32]; 65],
    };
    out.push(Scenario::rejected(
        "access-proof-with-too-many-siblings",
        "The sibling count is bounded by what the tree can produce, so an untrusted request cannot \
         make the decoder allocate an arbitrary list.",
        "historical-after-handle-update",
        "the entry's access proof carries one sibling more than the tree's height ceiling",
        rule::ACCESS_PROOF_TOO_MANY_SIBLINGS,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .historical(
                &proof_encrypted_value_account,
                sealed,
                wallet.pubkey(),
                &oversized,
                1,
            )
            .wire(),
        proof_world.clone(),
    ));

    out.push(Scenario::rejected(
        "malformed-access-proof",
        "Bytes that are not a proof at all are refused as a form error, before any state is read.",
        "historical-after-handle-update",
        "the entry's access proof is replaced with three arbitrary bytes",
        rule::ACCESS_PROOF_MALFORMED,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .entry(
                sealed,
                wallet.pubkey(),
                proof_encrypted_value_account.encrypted_value_id(),
                1,
                vec![0xff, 0xff, 0xff],
            )
            .wire(),
        proof_world,
    ));

    let _ = (encrypted_value_account, live);
    out
}

fn encrypted_value_account_scenarios() -> Vec<Scenario> {
    let mut out = Vec::new();
    let (wallet, encrypted_value_account, live, request, _) = reference_direct();

    out.push(Scenario::rejected(
        "missing-encrypted-value-account",
        "The encrypted value account does not exist at this observation. Transient by nature: the account \
         may simply not have reached the observed commitment yet.",
        "direct-current",
        "the encrypted value account is removed from the observation",
        rule::ENCRYPTED_VALUE_ACCOUNT_ABSENT,
        FailureClass::Transient,
        request.clone(),
        World::at_slot(OBSERVED_SLOT).with_watermark(wallet.pubkey(), 0),
    ));

    let mut foreign_owner = encrypted_value_account.account();
    foreign_owner.owner = [0xee; 32];
    out.push(Scenario::rejected(
        "encrypted-value-account-owned-by-another-program",
        "Program ownership is the sole trust anchor: an account with impeccable contents under \
         another program's ownership proves nothing.",
        "direct-current",
        "the encrypted value account's owner is replaced with another program",
        rule::ENCRYPTED_VALUE_ACCOUNT_FOREIGN_OWNER,
        FailureClass::Terminal,
        request.clone(),
        World::at_slot(OBSERVED_SLOT)
            .with_account(encrypted_value_account.account_key, foreign_owner)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let delegation =
        DelegationFixture::live(Wallet::new(2).pubkey(), wallet.pubkey(), OBSERVED_SLOT);
    out.push(Scenario::rejected(
        "delegation-record-as-encrypted-value-account",
        "A host-owned account of another type is caught by the discriminator rather than by what \
         its bytes happen to mean when read as an encrypted value account.",
        "direct-current",
        "the encrypted value account address holds a delegation record instead",
        rule::ENCRYPTED_VALUE_ACCOUNT_WRONG_TYPE,
        FailureClass::Terminal,
        request.clone(),
        World::at_slot(OBSERVED_SLOT)
            .with_account(encrypted_value_account.account_key, delegation.account())
            .with_watermark(wallet.pubkey(), 0),
    ));

    let full = encrypted_value_account.account();
    let truncated = SnapshotAccount {
        owner: PROGRAM_ID,
        data: full.data[..full.data.len() - 8].to_vec(),
    };
    out.push(Scenario::rejected(
        "encrypted-value-account-with-a-truncated-body",
        "A body cut short is not the same thing as a body followed by extra bytes: the first cannot \
         be read, the second is an account with room to spare.",
        "direct-current",
        "eight bytes are removed from the end of the encrypted value account",
        rule::ENCRYPTED_VALUE_ACCOUNT_MALFORMED,
        FailureClass::Terminal,
        request.clone(),
        World::at_slot(OBSERVED_SLOT)
            .with_account(encrypted_value_account.account_key, truncated)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let another_app = EncryptedValueAccountFixture::in_domain(
        DOMAIN,
        [0x33; 32],
        LABEL,
        live,
        &[wallet.pubkey()],
    );
    out.push(Scenario::rejected(
        "encrypted-value-account-deriving-another-id",
        "The account's own fields must reproduce the identity that was claimed. This is the \
         backstop that makes a substituted encrypted value account a rejection rather than a redirection.",
        "direct-current",
        "the encrypted value account address holds an encrypted value account of another authority",
        rule::ENCRYPTED_VALUE_ID_MISMATCH,
        FailureClass::Terminal,
        request,
        World::at_slot(OBSERVED_SLOT)
            .with_account(encrypted_value_account.account_key, another_app.account())
            .with_watermark(wallet.pubkey(), 0),
    ));

    let unsigned_domain_handle = handle(0x14, FHE_TYPE_UINT64);
    let unsigned_domain_encrypted_value_account = EncryptedValueAccountFixture::in_domain(
        [0x62; 32],
        AUTHORITY,
        LABEL,
        unsigned_domain_handle,
        &[wallet.pubkey()],
    );
    out.push(Scenario::rejected(
        "handle-of-an-unsigned-domain",
        "With a non-empty signed scope, every entry's encrypted value account domain must be in it. The domain \
         tested is the encrypted value account's — a request has no field for it.",
        "direct-current",
        "the entry names an encrypted value account whose domain is outside the signed scope",
        rule::DOMAIN_NOT_ALLOWED,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .direct_current(&unsigned_domain_encrypted_value_account, unsigned_domain_handle)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&unsigned_domain_encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    out
}

fn handle_binding_scenarios() -> Vec<Scenario> {
    let mut out = Vec::new();
    let wallet = Wallet::new(1);
    let stranger = Wallet::new(9);

    let replaced = handle(0xa0, FHE_TYPE_UINT64);
    let mut moved_on = EncryptedValueAccountFixture::new(replaced, &[wallet.pubkey()]);
    moved_on.update(handle(0xa1, FHE_TYPE_UINT64));
    out.push(Scenario::rejected(
        "replaced-current-handle",
        "A current-mode entry whose handle is no longer current fails, and is not quietly answered \
         with whatever is current instead. The same handle remains reachable as historical access.",
        "direct-current",
        "the encrypted value account's current handle moves on before the observation",
        rule::HANDLE_NOT_CURRENT,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .direct_current(&moved_on, replaced)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&moved_on)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let live = handle(0xa2, FHE_TYPE_UINT64);
    let others_encrypted_value_account =
        EncryptedValueAccountFixture::new(live, &[stranger.pubkey()]);
    out.push(Scenario::rejected(
        "subject-outside-the-current-members",
        "Current access requires membership of the encrypted value account's current subject set, and the set is \
         the account's rather than the request's.",
        "direct-current",
        "the encrypted value account's subject set names somebody else",
        rule::SUBJECT_NOT_A_MEMBER,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .direct_current(&others_encrypted_value_account, live)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&others_encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    let (sealed_encrypted_value_account, sealed, _) =
        replaced_encrypted_value_account(0xb0, wallet.pubkey());
    let sealed_world = World::at_slot(OBSERVED_SLOT)
        .with_encrypted_value_account(&sealed_encrypted_value_account)
        .with_watermark(wallet.pubkey(), 0);

    out.push(Scenario::rejected(
        "leaf-index-beyond-the-leaf-count",
        "A position the encrypted value account does not have is refused before any hashing: there is nothing for \
         the proof to be a proof of. From the outside this is an inclusion failure like any other, \
         and it is classified like one — by the leaf count the request claims. Here the claim is \
         at or above the observed count, which is what a proof service running ahead of this \
         observation looks like, so the answer is to retry rather than to rebuild.",
        "historical-after-handle-update",
        "the proof names a leaf index equal to the observed leaf count",
        rule::INCLUSION_PROOF_DOES_NOT_VERIFY,
        FailureClass::Retryable,
        RequestBuilder::new(&wallet)
            .historical(
                &sealed_encrypted_value_account,
                sealed,
                wallet.pubkey(),
                &MmrProof {
                    leaf_index: sealed_encrypted_value_account.encrypted_value.leaf_count,
                    siblings: Vec::new(),
                },
                1,
            )
            .wire(),
        sealed_world.clone(),
    ));

    // The four substitutions of the leaf commitment. Each seals a leaf that is genuine except in
    // one value, and each must fail: together they show all four values are inside the commitment.
    for (name, comment, mutation, commitment) in [
        (
            "leaf-commitment-for-another-encrypted-value-account",
            "A leaf sealed for another encrypted value account authorizes nothing here.",
            "the sealed leaf commits to another encrypted value account",
            historical_access_leaf_commitment([0x99; 32], 0, sealed, wallet.pubkey()),
        ),
        (
            "leaf-commitment-for-another-subject",
            "A leaf sealed for another subject authorizes only that subject.",
            "the sealed leaf commits to another subject",
            historical_access_leaf_commitment(
                EncryptedValueAccountFixture::new(sealed, &[wallet.pubkey()]).account_key,
                0,
                sealed,
                stranger.pubkey(),
            ),
        ),
        (
            "leaf-commitment-for-another-handle",
            "A leaf sealed for another handle authorizes only that handle.",
            "the sealed leaf commits to another handle",
            historical_access_leaf_commitment(
                EncryptedValueAccountFixture::new(sealed, &[wallet.pubkey()]).account_key,
                0,
                handle(0xbe, FHE_TYPE_UINT64),
                wallet.pubkey(),
            ),
        ),
        (
            "leaf-commitment-at-another-position",
            "A leaf whose committed position is not the position it occupies authorizes nothing.",
            "the sealed leaf commits to leaf index one while occupying index zero",
            historical_access_leaf_commitment(
                EncryptedValueAccountFixture::new(sealed, &[wallet.pubkey()]).account_key,
                1,
                sealed,
                wallet.pubkey(),
            ),
        ),
    ] {
        let mut substituted = EncryptedValueAccountFixture::new(sealed, &[wallet.pubkey()]);
        substituted.append(commitment);
        out.push(Scenario::rejected(
            name,
            comment,
            "historical-after-handle-update",
            mutation,
            rule::INCLUSION_PROOF_DOES_NOT_VERIFY,
            FailureClass::Retryable,
            RequestBuilder::new(&wallet)
                .historical(
                    &substituted,
                    sealed,
                    wallet.pubkey(),
                    &substituted.proof(0),
                    substituted.encrypted_value.leaf_count,
                )
                .wire(),
            World::at_slot(OBSERVED_SLOT)
                .with_encrypted_value_account(&substituted)
                .with_watermark(wallet.pubkey(), 0),
        ));
    }

    let public_handle = handle(0xc0, FHE_TYPE_UINT64);
    let mut public_encrypted_value_account =
        EncryptedValueAccountFixture::new(public_handle, &[wallet.pubkey()]);
    public_encrypted_value_account.mark_public();
    public_encrypted_value_account.update(handle(0xc1, FHE_TYPE_UINT64));
    out.push(Scenario::rejected(
        "public-decrypt-leaf-as-historical-access",
        "Public decryptability is a separate flow with its own leaf domain. Its leaf says nothing \
         about any subject and must not double as evidence that one held the handle.",
        "historical-after-handle-update",
        "the proof is of a public-decrypt leaf rather than a historical-access leaf",
        rule::INCLUSION_PROOF_DOES_NOT_VERIFY,
        FailureClass::Retryable,
        RequestBuilder::new(&wallet)
            .historical(
                &public_encrypted_value_account,
                public_handle,
                wallet.pubkey(),
                &public_encrypted_value_account.proof(0),
                public_encrypted_value_account.encrypted_value.leaf_count,
            )
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&public_encrypted_value_account)
            .with_watermark(wallet.pubkey(), 0),
    ));

    // A proof invalidated by an append that merged its peak: claimed count below the observed one.
    let merged = handle(0xd2, FHE_TYPE_UINT64);
    let mut merging =
        EncryptedValueAccountFixture::new(handle(0xd0, FHE_TYPE_UINT64), &[wallet.pubkey()]);
    merging.update(handle(0xd1, FHE_TYPE_UINT64));
    merging.update(merged);
    merging.update(handle(0xd3, FHE_TYPE_UINT64));
    let stale_proof = merging.proof(2);
    let claimed = merging.encrypted_value.leaf_count;
    merging.update(handle(0xd4, FHE_TYPE_UINT64));
    out.push(Scenario::rejected(
        "proof-predating-a-merging-append",
        "The append merged the proof's peak, so the sibling path it carries no longer exists. The \
         claimed count is below the observed one, which is what tells the client to rebuild rather \
         than to retry.",
        "historical-proof-predating-a-non-merging-append",
        "an append that merges the proof's peak happens before the observation",
        rule::INCLUSION_PROOF_DOES_NOT_VERIFY,
        FailureClass::Terminal,
        RequestBuilder::new(&wallet)
            .historical(&merging, merged, wallet.pubkey(), &stale_proof, claimed)
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&merging)
            .with_watermark(wallet.pubkey(), 0),
    ));

    // The observation behind the proof service: the proof is of state this observation has not seen.
    let ahead_handle = handle(0xe2, FHE_TYPE_UINT64);
    let mut behind =
        EncryptedValueAccountFixture::new(handle(0xe0, FHE_TYPE_UINT64), &[wallet.pubkey()]);
    behind.update(handle(0xe1, FHE_TYPE_UINT64));
    behind.update(ahead_handle);
    let mut ahead = behind.clone();
    ahead.update(handle(0xe3, FHE_TYPE_UINT64));
    ahead.update(handle(0xe4, FHE_TYPE_UINT64));
    out.push(Scenario::rejected(
        "proof-ahead-of-the-observation",
        "The proof service observed more state than this observation did. The claimed count is not \
         below the observed one, so the same request is worth repeating from a later observation — \
         and will succeed once the view catches up.",
        "historical-proof-predating-a-non-merging-append",
        "the observation holds an earlier state than the one the proof was built against",
        rule::INCLUSION_PROOF_DOES_NOT_VERIFY,
        FailureClass::Retryable,
        RequestBuilder::new(&wallet)
            .historical(
                &ahead,
                ahead_handle,
                wallet.pubkey(),
                &ahead.proof(1),
                ahead.encrypted_value.leaf_count,
            )
            .wire(),
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&behind)
            .with_watermark(wallet.pubkey(), 0),
    ));

    out
}

fn delegation_scenarios() -> Vec<Scenario> {
    let mut out = Vec::new();
    let (signer, delegator, encrypted_value_account, live, delegation, request, world) =
        reference_delegated();
    let base_world = || {
        World::at_slot(OBSERVED_SLOT)
            .with_encrypted_value_account(&encrypted_value_account)
            .with_watermark(signer.pubkey(), 0)
    };

    out.push(Scenario::rejected(
        "missing-delegation",
        "No delegation record at the canonical address for the tuple, so the delegated entry has \
         nothing standing behind it.",
        "delegated-current",
        "the delegation record is removed from the observation",
        rule::DELEGATION_ABSENT,
        FailureClass::Terminal,
        request.clone(),
        base_world(),
    ));

    let mut revoked = delegation;
    revoked.revoked = true;
    out.push(Scenario::rejected(
        "revoked-delegation",
        "The delegator revoked it. Subsequent requests stop immediately, while the signer's own \
         permit remains valid — two independent levers, one per party.",
        "delegated-current",
        "the delegation record is marked revoked",
        rule::DELEGATION_REVOKED,
        FailureClass::Terminal,
        request.clone(),
        base_world().with_delegation(&revoked),
    ));

    let mut expired = delegation;
    expired.expiration_slot = OBSERVED_SLOT - 1;
    out.push(Scenario::rejected(
        "expired-delegation",
        "Expiry is measured against the observed slot, not against a local clock.",
        "delegated-current",
        "the delegation's expiration slot falls below the observed slot",
        rule::DELEGATION_EXPIRED,
        FailureClass::Terminal,
        request.clone(),
        base_world().with_delegation(&expired),
    ));

    let mut from_the_future = delegation;
    from_the_future.last_update_slot = OBSERVED_SLOT + 1;
    out.push(Scenario::rejected(
        "delegation-newer-than-the-observation",
        "A record written after the observation is not part of the state this authorization saw. \
         Accepting it would mean authorizing from two points in time at once.",
        "delegated-current",
        "the delegation's last update slot is above the observed slot",
        rule::DELEGATION_NEWER_THAN_OBSERVATION,
        FailureClass::Terminal,
        request.clone(),
        base_world().with_delegation(&from_the_future),
    ));

    let (expected_key, _) = delegation.address();
    let mut other_tuple =
        DelegationFixture::live(Wallet::new(9).pubkey(), signer.pubkey(), OBSERVED_SLOT);
    other_tuple.encrypted_value_account_authority = AUTHORITY;
    out.push(Scenario::rejected(
        "delegation-record-of-another-tuple",
        "A record sitting at the canonical address while naming a different tuple is refused: the \
         address alone is not taken as proof of what the record says.",
        "delegated-current",
        "the delegation address holds a record naming another delegator",
        rule::DELEGATION_TUPLE_MISMATCH,
        FailureClass::Terminal,
        request.clone(),
        base_world().with_account(expected_key, other_tuple.account()),
    ));

    let mut foreign = delegation.account();
    foreign.owner = [0xee; 32];
    out.push(Scenario::rejected(
        "delegation-record-owned-by-another-program",
        "Only the host program grants delegations; an account under another program's ownership is \
         not one.",
        "delegated-current",
        "the delegation record's owner is replaced with another program",
        rule::DELEGATION_FOREIGN_OWNER,
        FailureClass::Terminal,
        request.clone(),
        base_world().with_account(expected_key, foreign),
    ));

    out.push(Scenario::rejected(
        "encrypted-value-account-record-as-delegation",
        "A host-owned account of another type at the delegation address is caught by its \
         discriminator, the mirror of the same substitution against an encrypted value account.",
        "delegated-current",
        "the delegation address holds an encrypted value account instead",
        rule::DELEGATION_WRONG_ACCOUNT_TYPE,
        FailureClass::Terminal,
        request.clone(),
        base_world().with_account(expected_key, encrypted_value_account.account()),
    ));

    // Both rows exist and neither is live. The authority-specific row alone would report "revoked", which
    // would send the delegator to a row that was not the only thing standing in the way.
    let mut revoked_wildcard =
        DelegationFixture::live_wildcard(delegator.pubkey(), signer.pubkey(), OBSERVED_SLOT);
    revoked_wildcard.revoked = true;
    out.push(Scenario::rejected(
        "no-live-delegation-row",
        "The delegator holds both an authority-specific row and a wildcard row, and both are revoked. The \
         rejection names both reasons: either row could have authorized this entry on its own, so \
         naming one of them would describe half of the state the delegate has to fix.",
        "delegated-current",
        "both the authority-specific and the wildcard delegation rows are marked revoked",
        rule::DELEGATION_NO_LIVE_GRANT,
        FailureClass::Terminal,
        request.clone(),
        base_world()
            .with_delegation(&revoked)
            .with_delegation(&revoked_wildcard),
    ));

    let _ = (delegator, live, world);
    out
}

fn scenarios() -> Vec<Scenario> {
    let mut out = accepting_scenarios();
    out.extend(deployment_and_permit_state_scenarios());
    out.extend(request_form_scenarios());
    out.extend(encrypted_value_account_scenarios());
    out.extend(handle_binding_scenarios());
    out.extend(delegation_scenarios());
    out
}

// ---------------------------------------------------------------------------
// Recording and replaying
// ---------------------------------------------------------------------------

fn record_of(scenario: &Scenario) -> ConnectorAuthVector {
    let permit = &scenario.request.permit;
    ConnectorAuthVector {
        name: scenario.name.to_owned(),
        comment: scenario.comment.to_owned(),
        result: scenario.result,
        rule: scenario.rule.map(str::to_owned),
        class: scenario.class,
        derived_from: scenario.derived_from.map(str::to_owned),
        mutation: scenario.mutation.map(str::to_owned),
        request: WireRequest {
            permit: WirePermit {
                user_pubkey: to_hex(&permit.user_pubkey),
                transport_key: TRANSPORT_KEY_NAME.to_owned(),
                allowed_acl_domain_keys: permit
                    .allowed_acl_domain_keys
                    .iter()
                    .map(|key| to_hex(key))
                    .collect(),
                start_timestamp: permit.start_timestamp.to_string(),
                duration_seconds: permit.duration_seconds.to_string(),
                verifying_program_id: to_hex(&permit.verifying_program_id),
                chain_id: permit.chain_id.to_string(),
                extra_data: to_hex(&permit.extra_data),
            },
            signature: to_hex(&scenario.request.signature),
            handles: scenario
                .request
                .handles
                .iter()
                .map(|entry| WireHandleEntry {
                    handle: to_hex(&entry.handle),
                    subject: to_hex(&entry.subject),
                    encrypted_value_id: to_hex(&entry.encrypted_value_id),
                    proof_leaf_count: entry.proof_leaf_count.to_string(),
                    access_proof: to_hex(&entry.access_proof),
                })
                .collect(),
            // The canonical bytes of the same request: what the gateway event carries
            // opaquely. Recorded from the canonical encoder so every consumer of this set
            // can verify its own codec in both directions against the typed fields above.
            solana_request: to_hex(
                &encode_solana_request(&scenario.request).expect("the scenario request serializes"),
            ),
        },
        observation: Observation {
            observed_slot: scenario.world.slot.to_string(),
            now_unix_seconds: scenario.now.to_string(),
            kms_pair_status: scenario.kms_pair_status,
            accounts: scenario
                .world
                .accounts()
                .map(|(key, account)| RecordedAccount {
                    pubkey: to_hex(key),
                    owner: to_hex(&account.owner),
                    data: to_hex(&account.data),
                })
                .collect(),
        },
    }
}

fn build_file() -> ConnectorAuthVectorFile {
    let scenarios = scenarios();
    let transport_key = scenarios
        .first()
        .map(|scenario| scenario.request.permit.transport_key.clone())
        .expect("the set is not empty");
    for scenario in &scenarios {
        assert_eq!(
            scenario.request.permit.transport_key, transport_key,
            "record '{}' uses a second transport key; the table would need another entry",
            scenario.name
        );
    }

    ConnectorAuthVectorFile {
        schema: CONNECTOR_AUTH_VECTOR_SCHEMA.to_owned(),
        description: "Connector-layer authorization vectors for Solana user decryption: the host \
                      policy applied to a request against a recorded observation of host state."
            .to_owned(),
        regenerate_with: "bash solana/scripts/update-connector-auth-vectors.sh".to_owned(),
        deployment: Deployment {
            verifying_program_id: to_hex(&PROGRAM_ID),
            genesis_hash: to_hex(&GENESIS_HASH),
            chain_id_decimal: CHAIN_ID.to_string(),
            chain_id_hex: format!("{CHAIN_ID:#018x}"),
            chain_id_be_bytes: to_hex(&CHAIN_ID.to_be_bytes()),
            chain_id_derivation: "deployment-time rule: chain_id = 0x8000000000000000 | \
                                  (be_u64(SHA-256(\"zama-solana-chain-id-v1\" || genesis_hash)[0..8]) \
                                  & 0x7fffffffffffffff), applied once per cluster and configured \
                                  everywhere. Nothing in the authorization path recomputes it, so \
                                  this set's pair is a synthetic cluster: the chain id below is not \
                                  the rule applied to the genesis hash below, and no check reads \
                                  the genesis hash at all. Vectors for the rule itself live with \
                                  the permit fixtures."
                .to_owned(),
        },
        transport_keys: BTreeMap::from([(TRANSPORT_KEY_NAME.to_owned(), to_hex(&transport_key))]),
        vectors: scenarios.iter().map(record_of).collect(),
    }
}

/// A validator that answers with whatever the record declares.
struct DeclaredKmsPair(KmsPairStatus);

impl KmsPairValidator for DeclaredKmsPair {
    async fn validate_pair(
        &self,
        _kms_context_id: &SolanaPubkeyBytes,
        _kms_epoch_id: &SolanaPubkeyBytes,
    ) -> Result<(), KmsPairFailure> {
        match self.0 {
            KmsPairStatus::Servable => Ok(()),
            KmsPairStatus::ContextUnknown => Err(KmsPairFailure::ContextUnknown),
            KmsPairStatus::ContextDestroyed => Err(KmsPairFailure::ContextDestroyed),
            // A record describes the management state; the Connector learns about all three of
            // these from one boolean and cannot tell which applies. The collapse belongs here, in
            // the adapter, rather than in the record — the world is more precise than the view of
            // it, and the set says so by keeping both.
            KmsPairStatus::EpochNotYetActive
            | KmsPairStatus::EpochOfAnotherContext
            | KmsPairStatus::EpochDestroyed => Err(KmsPairFailure::PairNotServable),
        }
    }
}

/// What the Connector made of a record.
#[derive(Debug, PartialEq, Eq)]
enum Outcome {
    Authorized,
    Rejected(&'static str, FailureClass),
}

/// The Connector's mapping from its own failure onto this set's rule names and classes.
///
/// Panics for failures this set does not cover, rather than inventing a name for them: the permit
/// layer has its own set, and a snapshot divergence cannot arise from a record that carries one
/// observation.
fn rule_name(failure: &AuthorizationFailure) -> &'static str {
    match failure {
        AuthorizationFailure::Form(form) => match form {
            RequestFormError::EmptyHandles => rule::EMPTY_HANDLES,
            RequestFormError::TooManyHandles { .. } => rule::TOO_MANY_HANDLES,
            RequestFormError::AccessProofMalformed { .. } => rule::ACCESS_PROOF_MALFORMED,
            RequestFormError::AccessProofTrailingBytes { .. } => rule::ACCESS_PROOF_TRAILING_BYTES,
            RequestFormError::AccessProofTooManySiblings { .. } => {
                rule::ACCESS_PROOF_TOO_MANY_SIBLINGS
            }
            RequestFormError::Permit(_)
            | RequestFormError::SignatureWidth { .. }
            | RequestFormError::EntryIdentityWidth { .. } => {
                panic!("the permit set covers this layer: {form}")
            }
        },
        AuthorizationFailure::SignatureMismatch | AuthorizationFailure::UnusableUserPubkey => {
            panic!("the permit set covers the signature rule")
        }
        AuthorizationFailure::Deployment(deployment) => match deployment {
            DeploymentFailure::ProgramIdMismatch { .. } => rule::DEPLOYMENT_PROGRAM_MISMATCH,
            DeploymentFailure::ChainIdMismatch { .. } => rule::DEPLOYMENT_CHAIN_ID_MISMATCH,
            DeploymentFailure::MixedEmbeddedChainIds { .. } => rule::MIXED_EMBEDDED_CHAIN_IDS,
            DeploymentFailure::EmbeddedChainIdMismatch { .. } => rule::EMBEDDED_CHAIN_ID_MISMATCH,
        },
        AuthorizationFailure::Window(window) => match window {
            WindowFailure::NotYetValid { .. } => rule::WINDOW_NOT_YET_VALID,
            WindowFailure::Expired { .. } => rule::WINDOW_EXPIRED,
        },
        AuthorizationFailure::Watermark(watermark) => match watermark {
            WatermarkFailure::Invalidated { .. } => rule::PERMIT_INVALIDATED,
            WatermarkFailure::NotAnInvalidationRecord { .. }
            | WatermarkFailure::RecordNamesAnotherUser { .. }
            | WatermarkFailure::ForeignOwner { .. } => rule::WATERMARK_RECORD_INVALID,
            WatermarkFailure::Snapshot(_) => panic!("a record carries one observation"),
        },
        AuthorizationFailure::KmsPair(_) => rule::KMS_PAIR_UNSERVABLE,
        AuthorizationFailure::Snapshot(_) => panic!("a record carries one observation"),
        AuthorizationFailure::EncryptedValueAccount { source, .. } => match source {
            EncryptedValueAccountFailure::Absent { .. } => rule::ENCRYPTED_VALUE_ACCOUNT_ABSENT,
            EncryptedValueAccountFailure::ForeignOwner { .. } => {
                rule::ENCRYPTED_VALUE_ACCOUNT_FOREIGN_OWNER
            }
            EncryptedValueAccountFailure::WrongAccountType { .. } => {
                rule::ENCRYPTED_VALUE_ACCOUNT_WRONG_TYPE
            }
            EncryptedValueAccountFailure::Malformed { .. } => {
                rule::ENCRYPTED_VALUE_ACCOUNT_MALFORMED
            }
            EncryptedValueAccountFailure::EncryptedValueIdMismatch { .. } => {
                rule::ENCRYPTED_VALUE_ID_MISMATCH
            }
            EncryptedValueAccountFailure::Snapshot(_) => panic!("a record carries one observation"),
        },
        AuthorizationFailure::HandleBinding { source, .. } => match source {
            HandleBindingFailure::NotCurrentHandle { .. } => rule::HANDLE_NOT_CURRENT,
            HandleBindingFailure::NotAMember { .. } => rule::SUBJECT_NOT_A_MEMBER,
            // Both proof outcomes reach a client through `InclusionFailed` below, which is where
            // they are classified by the claimed leaf count. Seeing one here would mean the
            // pipeline stopped folding them and the set lost that classification.
            HandleBindingFailure::LeafIndexOutOfRange { .. }
            | HandleBindingFailure::ProofDoesNotVerify { .. } => panic!(
                "an inclusion failure must arrive classified, not as a bare handle-binding failure"
            ),
            HandleBindingFailure::MmrStateInconsistent => {
                panic!("internally inconsistent host state is not a class of this set")
            }
        },
        AuthorizationFailure::InclusionFailed { .. } => rule::INCLUSION_PROOF_DOES_NOT_VERIFY,
        AuthorizationFailure::Scope { .. } => rule::DOMAIN_NOT_ALLOWED,
        AuthorizationFailure::Delegation { source, .. } => match source {
            DelegationFailure::Absent { .. } => rule::DELEGATION_ABSENT,
            DelegationFailure::Revoked => rule::DELEGATION_REVOKED,
            DelegationFailure::Expired { .. } => rule::DELEGATION_EXPIRED,
            DelegationFailure::NewerThanObservation { .. } => {
                rule::DELEGATION_NEWER_THAN_OBSERVATION
            }
            DelegationFailure::TupleMismatch { .. } => rule::DELEGATION_TUPLE_MISMATCH,
            DelegationFailure::ForeignOwner { .. } => rule::DELEGATION_FOREIGN_OWNER,
            DelegationFailure::NotADelegationRecord { .. } => rule::DELEGATION_WRONG_ACCOUNT_TYPE,
            DelegationFailure::NoLiveGrant { .. } => rule::DELEGATION_NO_LIVE_GRANT,
            DelegationFailure::Snapshot(_) => panic!("a record carries one observation"),
        },
    }
}

fn class_name(class: ConnectorClass) -> FailureClass {
    match class {
        ConnectorClass::Terminal => FailureClass::Terminal,
        ConnectorClass::Transient => FailureClass::Transient,
        ConnectorClass::Retryable => FailureClass::Retryable,
    }
}

/// Rebuilds a record's inputs and authorizes it — from the record, not from the scenario that
/// produced it, so what is under test is what the file says.
async fn replay(record: &ConnectorAuthVector, file: &ConnectorAuthVectorFile) -> Outcome {
    let permit = &record.request.permit;
    let wire = SolanaUserDecryptRequestWire {
        permit: PermitWireFields {
            user_pubkey: from_hex(&permit.user_pubkey).expect("hex"),
            transport_key: record
                .transport_key_bytes(file)
                .expect("the record names a key in the table"),
            allowed_acl_domain_keys: permit
                .allowed_acl_domain_keys
                .iter()
                .map(|key| from_hex(key).expect("hex"))
                .collect(),
            start_timestamp: permit.start_timestamp.parse().expect("decimal"),
            duration_seconds: permit.duration_seconds.parse().expect("decimal"),
            verifying_program_id: from_hex(&permit.verifying_program_id).expect("hex"),
            chain_id: permit.chain_id.parse().expect("decimal"),
            extra_data: from_hex(&permit.extra_data).expect("hex"),
        },
        signature: from_hex(&record.request.signature).expect("hex"),
        handles: record
            .request
            .handles
            .iter()
            .map(|entry| SolanaHandleEntryWire {
                handle: from_hex(&entry.handle).expect("hex"),
                subject: from_hex(&entry.subject).expect("hex"),
                encrypted_value_id: from_hex(&entry.encrypted_value_id).expect("hex"),
                proof_leaf_count: entry.proof_leaf_count.parse().expect("decimal"),
                access_proof: from_hex(&entry.access_proof).expect("hex"),
            })
            .collect(),
    };

    // The record's canonical bytes and its typed fields must be the same request under the
    // canonical codec, in both directions — this is what freezes the layout for every
    // implementation that consumes this set.
    let recorded_request = from_hex(&record.request.solana_request).expect("hex");
    assert_eq!(
        encode_solana_request(&wire).expect("the typed fields serialize"),
        recorded_request,
        "record {}: the typed fields do not encode to the recorded bytes",
        record.name
    );
    assert_eq!(
        decode_solana_request(&recorded_request).expect("the recorded bytes decode"),
        wire,
        "record {}: the recorded bytes do not decode to the typed fields",
        record.name
    );

    let world = World::from_accounts(
        record.observation.observed_slot.parse().expect("decimal"),
        record.observation.accounts.iter().map(|account| {
            let key: SolanaPubkeyBytes = from_hex(&account.pubkey)
                .expect("hex")
                .try_into()
                .expect("a 32-byte address");
            (
                key,
                SnapshotAccount {
                    owner: from_hex(&account.owner)
                        .expect("hex")
                        .try_into()
                        .expect("a 32-byte owner"),
                    data: from_hex(&account.data).expect("hex"),
                },
            )
        }),
    );

    let request = match SolanaUserDecryptRequest::decode(&wire) {
        Ok(request) => request,
        Err(form) => {
            let failure = AuthorizationFailure::Form(form);
            return Outcome::Rejected(rule_name(&failure), class_name(failure.class()));
        }
    };
    let reader = ScriptedReader::scripted(vec![world.clone(), world]);
    let deployment = deployment();
    let context = AuthorizationContext {
        deployment: &deployment,
        now_unix_seconds: record
            .observation
            .now_unix_seconds
            .parse()
            .expect("decimal"),
        // The vectors predate the gateway's typed declaration and do not probe it: every record
        // is replayed with the honest declaration (the signed list's actual length), so the
        // declaration rule never decides a vector's outcome.
    };
    match authorize_request(
        &reader,
        &DeclaredKmsPair(record.observation.kms_pair_status),
        context,
        &request,
    )
    .await
    {
        Ok(_) => Outcome::Authorized,
        Err(failure) => Outcome::Rejected(rule_name(&failure), class_name(failure.class())),
    }
}

// ---------------------------------------------------------------------------
// The tests
// ---------------------------------------------------------------------------

fn committed_file() -> ConnectorAuthVectorFile {
    let path = vector_path();
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "the committed vector file at {} could not be read ({error}). Generate it with \
             `bash solana/scripts/update-connector-auth-vectors.sh` once the authorization path is \
             implemented.",
            path.display()
        )
    });
    let file: ConnectorAuthVectorFile =
        serde_json::from_str(&raw).expect("the committed vector file parses");
    assert_eq!(file.schema, CONNECTOR_AUTH_VECTOR_SCHEMA);
    file
}

/// The committed file is the build. Under the update gate it is rewritten from it instead — the
/// generator and the runner are one code path, so the file cannot agree with neither.
#[test]
fn committed_vectors_match_the_generator() {
    let built = build_file();
    let serialized = serde_json::to_string_pretty(&built).expect("the set serializes") + "\n";

    if std::env::var(UPDATE_ENV).is_ok() {
        std::fs::write(vector_path(), &serialized).expect("the set is written");
        return;
    }

    let committed = committed_file();
    assert_eq!(
        committed, built,
        "the committed set and the generated set differ; regenerate with \
         `bash solana/scripts/update-connector-auth-vectors.sh`"
    );
}

/// Every record behaves as declared, replayed from the file.
#[tokio::test]
async fn every_vector_behaves_as_declared() {
    let file = committed_file();

    for record in &file.vectors {
        let outcome = replay(record, &file).await;
        match record.result {
            VectorResult::Valid | VectorResult::Acceptable => assert_eq!(
                outcome,
                Outcome::Authorized,
                "record '{}' is declared {:?} but was rejected",
                record.name,
                record.result
            ),
            VectorResult::Invalid => {
                let declared_rule = record
                    .rule
                    .as_deref()
                    .expect("a rejecting record names a rule");
                let declared_class = record.class.expect("a rejecting record names a class");
                assert_eq!(
                    outcome,
                    Outcome::Rejected(
                        rule::ALL
                            .iter()
                            .copied()
                            .find(|name| *name == declared_rule)
                            .unwrap_or_else(|| panic!(
                                "record '{}' names rule '{declared_rule}', which is not in the \
                                 dictionary",
                                record.name
                            )),
                        declared_class
                    ),
                    "record '{}' must be rejected by '{declared_rule}' as {declared_class:?}",
                    record.name
                );
            }
        }
    }
}

/// A rejecting record's base must be authorized. Without this, "the request is rejected" could be
/// true for a reason unrelated to the mutation the record describes.
#[tokio::test]
async fn the_base_of_every_rejecting_record_is_authorized() {
    let file = committed_file();

    for record in &file.vectors {
        let Some(base_name) = record.derived_from.as_deref() else {
            continue;
        };
        let base = file
            .vectors
            .iter()
            .find(|candidate| candidate.name == base_name)
            .unwrap_or_else(|| {
                panic!(
                    "record '{}' derives from '{base_name}', which is not in the set",
                    record.name
                )
            });
        assert!(
            matches!(base.result, VectorResult::Valid | VectorResult::Acceptable),
            "record '{}' derives from '{base_name}', which is not an accepted record",
            record.name
        );
        assert_eq!(
            replay(base, &file).await,
            Outcome::Authorized,
            "record '{}' derives from '{base_name}', which is not authorized — so its rejection \
             says nothing about the mutation",
            record.name
        );
    }
}

/// Every rule is exercised, and every rule the set declares is one the dictionary names. Both
/// directions: a regeneration that dropped a class would otherwise pass.
#[test]
fn the_set_covers_the_rule_dictionary_in_both_directions() {
    let file = committed_file();
    let declared: BTreeSet<&str> = file
        .vectors
        .iter()
        .filter_map(|record| record.rule.as_deref())
        .collect();
    let dictionary: BTreeSet<&str> = rule::ALL.iter().copied().collect();

    let uncovered: Vec<&&str> = dictionary.difference(&declared).collect();
    assert!(
        uncovered.is_empty(),
        "these rules are in the dictionary but no record exercises them: {uncovered:?}"
    );
    let unknown: Vec<&&str> = declared.difference(&dictionary).collect();
    assert!(
        unknown.is_empty(),
        "these rules are declared by records but are not in the dictionary: {unknown:?}"
    );
}

/// Structural requirements on the records themselves.
#[test]
fn records_carry_the_required_fields() {
    let file = committed_file();
    let mut names = BTreeSet::new();

    for record in &file.vectors {
        assert!(
            names.insert(record.name.clone()),
            "record name '{}' appears twice",
            record.name
        );
        assert!(
            !record.comment.trim().is_empty(),
            "record '{}' has no comment, and a record whose purpose is not written down is a record \
             nobody can review",
            record.name
        );
        match record.result {
            VectorResult::Invalid => {
                assert!(
                    record.rule.is_some(),
                    "record '{}' rejects without a rule",
                    record.name
                );
                assert!(
                    record.class.is_some(),
                    "record '{}' rejects without a class",
                    record.name
                );
                assert!(
                    record.derived_from.is_some() && record.mutation.is_some(),
                    "record '{}' rejects without naming its base and its mutation",
                    record.name
                );
            }
            VectorResult::Valid | VectorResult::Acceptable => {
                assert!(
                    record.rule.is_none() && record.class.is_none(),
                    "record '{}' is accepted and must name no rule",
                    record.name
                );
            }
        }
        assert!(
            !record.observation.accounts.is_empty()
                || record.name == "missing-encrypted-value-account",
            "record '{}' carries no accounts, which is only meaningful for an absence case",
            record.name
        );
    }
}

/// Every 64-bit field is a decimal string in the JSON. The typed form cannot tell the difference,
/// so this test reads the raw text.
#[test]
fn sixty_four_bit_fields_are_strings_in_the_json() {
    let raw = std::fs::read_to_string(vector_path()).expect("the committed file is readable");
    let json: serde_json::Value = serde_json::from_str(&raw).expect("valid JSON");

    for record in json["vectors"].as_array().expect("an array") {
        for field in ["start_timestamp", "duration_seconds", "chain_id"] {
            assert!(
                record["request"]["permit"][field].is_string(),
                "permit field '{field}' must be a decimal string"
            );
        }
        for field in ["observed_slot", "now_unix_seconds"] {
            assert!(
                record["observation"][field].is_string(),
                "observation field '{field}' must be a decimal string"
            );
        }
        for entry in record["request"]["handles"].as_array().expect("an array") {
            assert!(
                entry["proof_leaf_count"].is_string(),
                "a handle entry's proof leaf count must be a decimal string"
            );
        }
    }
    assert!(
        json["deployment"]["chain_id_decimal"].is_string(),
        "the deployment chain id must be a decimal string"
    );
}
