import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';

import {
  type ExportBlock,
  type ExportEntry,
  type ExportManifest,
  type ValueKind,
  loadExportManifest,
} from './export-manifest.ts';

export type GeneratedExportStatus = {
  readonly path: string;
  readonly status: 'identical' | 'missing' | 'different';
};

export type GenerateExportsOptions = {
  readonly manifestFile: string;
  readonly check: boolean;
};

type RenderedOutput = { readonly path: string; readonly content: string };

/**
 * Which test framework the output is written for.
 *
 * The consumer fixtures use `node:test` because a fixture that adds a framework stops representing a
 * consumer. The package's own harness project already runs vitest, and its config decides what runs — so
 * the same manifest has to render in both dialects rather than one being converted by hand.
 */
type Runner = 'node' | 'vitest';

type RunnerDialect = {
  readonly imports: string;
  readonly declare: (title: string) => string;
  readonly typeOf: (target: string, expected: string) => string;
  readonly isArray: (target: string) => string;
  readonly defined: (target: string) => string;
};

const dialects: Readonly<Record<Runner, RunnerDialect>> = {
  node: {
    imports: `import assert from 'node:assert/strict';\nimport test from 'node:test';`,
    declare: (title) => `void test('${title}', () => {`,
    typeOf: (target, expected) => `  assert.equal(typeof ${target}, '${expected}');`,
    isArray: (target) => `  assert.ok(Array.isArray(${target}), '${target} must be an array');`,
    defined: (target) => `    assert.notEqual(${target}, undefined);`,
  },
  vitest: {
    imports: `import { expect, test } from 'vitest';`,
    declare: (title) => `test('${title}', () => {`,
    typeOf: (target, expected) => `  expect(typeof ${target}).toBe('${expected}');`,
    isArray: (target) => `  expect(Array.isArray(${target}), '${target} must be an array').toBe(true);`,
    defined: (target) => `    expect(${target}).toBeDefined();`,
  },
};

export function generateExports(options: GenerateExportsOptions): readonly GeneratedExportStatus[] {
  const outputs = renderExportManifest(options.manifestFile);
  if (options.check) return compareOutputs(outputs);

  for (const output of outputs) {
    mkdirSync(dirname(output.path), { recursive: true });
    writeFileSync(output.path, output.content);
  }
  return outputs.map((output) => ({ path: output.path, status: 'identical' as const }));
}

export function renderExportManifest(manifestFile: string): readonly RenderedOutput[] {
  const absoluteManifestFile = resolve(manifestFile);
  const manifest = loadExportManifest(absoluteManifestFile);
  const root = dirname(absoluteManifestFile);
  const outputs: RenderedOutput[] = [];

  const exportPath = resolveOutputPath(root, manifest.outputs.exports);
  outputs.push({ path: exportPath, content: renderIndex(manifest, header(absoluteManifestFile, exportPath)) });

  for (const moduleSystem of ['cjs', 'esm'] as const) {
    const configuredPath = manifest.outputs.testConsumers[moduleSystem];
    if (configuredPath === undefined) continue;
    const outputPath = resolveOutputPath(root, configuredPath);
    outputs.push({
      path: outputPath,
      content: renderTest(manifest, 'node', header(absoluteManifestFile, outputPath)),
    });
  }

  if (manifest.outputs.test !== undefined) {
    const outputPath = resolveOutputPath(root, manifest.outputs.test);
    outputs.push({
      path: outputPath,
      content: renderTest(manifest, 'vitest', header(absoluteManifestFile, outputPath)),
    });
  }

  return outputs;
}

function compareOutputs(outputs: readonly RenderedOutput[]): readonly GeneratedExportStatus[] {
  return outputs.map((output) => {
    if (!existsSync(output.path)) return { path: output.path, status: 'missing' as const };
    return {
      path: output.path,
      status: readFileSync(output.path, 'utf8') === output.content ? ('identical' as const) : ('different' as const),
    };
  });
}

function resolveOutputPath(root: string, configuredPath: string): string {
  const output = resolve(root, configuredPath);
  const relativePath = relative(root, output);
  if (relativePath === '..' || relativePath.startsWith(`..${sep}`)) {
    throw new Error(`Export output escapes the manifest directory: ${configuredPath}`);
  }
  return output;
}

function header(manifestFile: string, outputFile: string): string {
  const source = displayRelative(dirname(outputFile), manifestFile);
  return (
    `// AUTOGENERATED by \`fhevm-npm generate-exports\` from ${source}.\n` +
    `// DO NOT EDIT — your changes will be overwritten.`
  );
}

function displayRelative(from: string, to: string): string {
  const path = relative(from, to).split(sep).join('/');
  return path.startsWith('.') ? path : `./${path}`;
}

function valueExports(manifest: ExportManifest): readonly ExportEntry[] {
  return manifest.blocks.filter((block) => !block.typeOnly).flatMap((block) => block.exports);
}

function renderExportStatement(block: ExportBlock, printWidth: number): string {
  const keyword = block.typeOnly ? 'export type' : 'export';
  const names = block.exports.map((entry) => entry.name);
  const singleLine = `${keyword} { ${names.join(', ')} } from '${block.module}';`;
  const inlineComments = block.exports.some((entry) => entry.comment !== undefined);
  if (!inlineComments && singleLine.length <= printWidth) return singleLine;

  const body = block.exports.flatMap((entry) => [
    ...(entry.comment ?? []).map((line) => `  // ${line}`),
    `  ${entry.name},`,
  ]);
  return [`${keyword} {`, ...body, `} from '${block.module}';`].join('\n');
}

function renderIndex(manifest: ExportManifest, generatedHeader: string): string {
  const blocks = manifest.blocks.map((block) => {
    const statement = renderExportStatement(block, manifest.printWidth);
    const comment = (block.comment ?? []).map((line) => `// ${line}`);
    return { text: [...comment, statement].join('\n'), wrapped: statement.includes('\n') };
  });
  const body = blocks.map((block, index) => (block.wrapped && index > 0 ? `\n${block.text}` : block.text)).join('\n');
  return `${generatedHeader}\n\n${body}\n`;
}

/**
 * How a fixture reaches the package — now identical whatever its module system.
 *
 * The CJS fixture used to need `require()` plus `with { 'resolution-mode': 'require' }`: the package
 * served one unconditional `types` entry whose declarations read as ESM, so a CommonJS importer got
 * TS1479 and even `import type` got TS1541. Per-condition `types` in the exports map fixed that at the
 * source, and a CommonJS consumer now writes the same plain `import` an ESM one does. Keeping the
 * workaround here would have hidden the packaging defect instead of surfacing it.
 */
function renderImports(manifest: ExportManifest, dialect: RunnerDialect): string {
  const names = manifest.blocks.flatMap((block) =>
    block.exports.map((entry) => `  ${block.typeOnly ? 'type ' : ''}${entry.name},`),
  );
  return `import {\n${names.join('\n')}\n} from '${manifest.packageSpecifier}';\n${dialect.imports}`;
}

function renderTest(manifest: ExportManifest, runner: Runner, generatedHeader: string): string {
  const dialect = dialects[runner];
  const preamble = manifest.dummies.preamble.flatMap((entry) =>
    renderBinding(`const ${entry.name}: ${entry.type}`, entry.expression),
  );
  const samples = manifest.dummies.values.flatMap((value) =>
    renderBinding(`const ${dummyName(value.type)}: ${value.type}`, value.dummy),
  );

  return `${generatedHeader}

${renderImports(manifest, dialect)}

${preamble.join('\n')}

////////////////////////////////////////////////////////////////////////////////
// One sample value per exported type. These are compile-time assertions: each binding resolves only if
// its type is still exported and still describes the value, so a renamed field fails the fixture's tsc.
////////////////////////////////////////////////////////////////////////////////

${samples.join('\n')}

const SAMPLES: readonly unknown[] = [
${manifest.dummies.values.map((value) => `  ${dummyName(value.type)},`).join('\n')}
];

////////////////////////////////////////////////////////////////////////////////

${dialect.declare('every value export arrives with the type a consumer relies on')}
${valueAssertions(manifest, dialect).join('\n')}
});

${dialect.declare('every type export still describes its sample value')}
  // The assertion already happened, at compile time. This keeps the bindings from being dead code.
  for (const sample of SAMPLES) {
${dialect.defined('sample')}
  }
});
`;
}

function valueAssertions(manifest: ExportManifest, dialect: RunnerDialect): readonly string[] {
  return valueExports(manifest).flatMap((entry) => {
    if (!('kind' in entry)) throw new Error(`Value export '${entry.name}' has no runtime kind`);
    if (entry.kind === 'array') {
      return [
        dialect.isArray(entry.name),
        ...(entry.element === undefined ? [] : [dialect.typeOf(`${entry.name}[0]`, entry.element)]),
      ];
    }
    const members = Object.entries(entry.member ?? {}).map(([member, kind]) =>
      dialect.typeOf(`${entry.name}.${member}`, kind),
    );
    return [dialect.typeOf(entry.name, entry.kind), ...members];
  });
}

function dummyName(typeName: string): string {
  return `dummy${typeName}`;
}

function renderBinding(declaration: string, body: string | readonly string[]): readonly string[] {
  const sourceLines = typeof body === 'string' ? [body] : body;
  const [first, ...rest] = sourceLines;
  const lines = [`${declaration} = ${first ?? ''}`, ...rest];
  return lines.map((line, index) => (index === lines.length - 1 ? `${line};` : line));
}

export function valueKind(value: ValueKind): ValueKind {
  return value;
}
