// Renders a shell tab-completion script from the LIVE commander registry, so the completion can never
// drift from the real command list: `fhevm-npm sh-completion zsh` re-renders it after any CLI change.

export type CompletionShell = 'zsh' | 'bash';

export type CompletionCommand = {
  readonly name: string;
  readonly description: string;
  /** Bare flag tokens, e.g. ['-o', '--out-dir', '--check']. */
  readonly flags: readonly string[];
  /** First positional argument's name ('package', 'manifest', 'shell'), when the command takes one. */
  readonly argument?: string;
};

export const GLOBAL_FLAGS = ['-r', '--root', '-v', '--verbose'] as const;

export function renderCompletionScript(
  shell: CompletionShell,
  commands: readonly CompletionCommand[],
  packageKeys: readonly string[],
): string {
  return shell === 'zsh' ? renderZsh(commands, packageKeys) : renderBash(commands, packageKeys);
}

// First clause only ('. ' ends a sentence, but 'package.json' must survive). Inside a single-quoted zsh
// string a quote is escaped by closing around it; `:` separates value from description in _describe.
function zshDescription(description: string): string {
  const clause = description.split(/\.\s|;|\s\(/, 1)[0] ?? '';
  return clause.trim().replace(/\.$/, '').replaceAll("'", `'\\''`).replaceAll(':', '\\:');
}

function renderZsh(commands: readonly CompletionCommand[], packageKeys: readonly string[]): string {
  const entries = commands.map((cmd) => `    '${cmd.name}:${zshDescription(cmd.description)}'`).join('\n');
  const flagCases = commands
    .filter((cmd) => cmd.flags.length > 0)
    .map((cmd) => `    ${cmd.name}) _opts+=( ${cmd.flags.join(' ')} ) ;;`)
    .join('\n');
  const packageCommands = commands.filter((cmd) => cmd.argument === 'package').map((cmd) => cmd.name);
  const fileCommands = commands.filter((cmd) => cmd.argument === 'manifest').map((cmd) => cmd.name);

  return `# zsh tab completion for fhevm-npm-cli — AUTO-GENERATED by \`fhevm-npm sh-completion zsh\`.
# Do not edit: to update it, regenerate it (hand edits are lost then anyway).
#
# This script does nothing until your shell loads it. Pick ONE of the two ways:
#
#   A. Always fresh — reruns the CLI at every new terminal. Add to ~/.zshrc, AFTER its \`compinit\` line
#      (compinit boots zsh completion; the \`compdef\` call below needs it):
#        source <(/path/to/sdk/fhevm-npm-cli sh-completion zsh)
#
#   B. Cached file — instant startup; rerun the two commands after fhevm-npm gains a command or option:
#        mkdir -p ~/.zfunc
#        /path/to/sdk/fhevm-npm-cli sh-completion zsh > ~/.zfunc/_fhevm-npm-cli
#      and in ~/.zshrc, BEFORE its \`compinit\` line (\$fpath is where compinit looks for completions):
#        fpath=(~/.zfunc \$fpath)

_fhevm_npm_cli() {
  local -a _commands _opts _pkgs
  _commands=(
${entries}
  )
  _pkgs=( ${packageKeys.join(' ')} )

  if (( CURRENT == 2 )); then
    _describe -t commands 'fhevm-npm command' _commands
    return
  fi

  _opts=( ${GLOBAL_FLAGS.join(' ')} )
  case "\${words[2]}" in
${flagCases}
  esac

  case "\${words[2]}" in
    ${packageCommands.join('|')})
      if [[ \${words[CURRENT]} != -* ]]; then compadd -- \$_pkgs; fi ;;
    ${fileCommands.join('|')})
      if [[ \${words[CURRENT]} != -* ]]; then _files -g '*.json'; fi ;;
    sh-completion)
      if [[ \${words[CURRENT]} != -* ]]; then compadd -- zsh bash; fi ;;
  esac
  compadd -- \$_opts
}

if (( \$+functions[compdef] )); then
  compdef _fhevm_npm_cli fhevm-npm-cli fhevm-npm
fi
`;
}

function renderBash(commands: readonly CompletionCommand[], packageKeys: readonly string[]): string {
  const names = commands.map((cmd) => cmd.name).join(' ');
  const flagCases = commands
    .filter((cmd) => cmd.flags.length > 0)
    .map((cmd) => `    ${cmd.name}) opts+=" ${cmd.flags.join(' ')}" ;;`)
    .join('\n');
  const packageCommands = commands.filter((cmd) => cmd.argument === 'package').map((cmd) => cmd.name);

  return `# bash completion for fhevm-npm-cli — AUTO-GENERATED by \`fhevm-npm sh-completion bash\`, do not edit.
# Install: source <(/path/to/sdk/fhevm-npm-cli sh-completion bash)   # in ~/.bashrc

_fhevm_npm_cli() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  if (( COMP_CWORD == 1 )); then
    COMPREPLY=( \$(compgen -W "${names}" -- "\$cur") )
    return
  fi
  local opts="${GLOBAL_FLAGS.join(' ')}"
  case "\${COMP_WORDS[1]}" in
${flagCases}
  esac
  case "\${COMP_WORDS[1]}" in
    ${packageCommands.join('|')}) opts+=" ${packageKeys.join(' ')}" ;;
    sh-completion) opts+=" zsh bash" ;;
  esac
  COMPREPLY=( \$(compgen -W "\$opts" -- "\$cur") )
}

complete -F _fhevm_npm_cli fhevm-npm-cli fhevm-npm
`;
}
