[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "BSD-3-Clause-Clear",
  "Zlib",
  "BSL-1.0",
]

unused-allowed-license = "allow"
