/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILayerZeroReadExecutor,
  ILayerZeroReadExecutorInterface,
} from "../../../../../@layerzerolabs/lz-evm-messagelib-v2/contracts/interfaces/ILayerZeroReadExecutor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_options",
        type: "bytes",
      },
    ],
    name: "assignJob",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_options",
        type: "bytes",
      },
    ],
    name: "getFee",
    outputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILayerZeroReadExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): ILayerZeroReadExecutorInterface {
    return new Interface(_abi) as ILayerZeroReadExecutorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILayerZeroReadExecutor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILayerZeroReadExecutor;
  }
}
