import { Message } from '@aws-sdk/client-sqs'
import { Inject, Injectable, Logger } from '@nestjs/common'
import { isAppDeploymentCommand, web3 } from 'messages'
import { SqsMessageHandler } from 'sqs'
import { DiscoverContract } from '#use-cases/discover-contract.use-case.js'
import { isAppError, type IPubSub } from 'utils'
import { MS_NAME, PUBSUB } from '#constants.js'

@Injectable()
export class SQSConsumer {
  private readonly logger = new Logger(SQSConsumer.name)

  constructor(
    @Inject(PUBSUB)
    private readonly pubsub: IPubSub<web3.Web3Event>,
    private readonly discoverSC: DiscoverContract,
  ) {}

  @SqsMessageHandler('web3', false)
  public async handleMessage(message: Message) {
    if (message.Body) {
      let body: Record<string, any>
      try {
        body = JSON.parse(message.Body)
      } catch (err) {
        this.logger.debug(`received message: ${message.Body}`)
        this.logger.warn(`❌ failed to parse body: ${err}`)
        return
      }

      if (!('Message' in body)) {
        this.logger.warn(`missing 'Message' in Body: ${message.Body}`)
      }

      let data: unknown
      try {
        data = JSON.parse(body.Message)
      } catch (err) {
        this.logger.debug(`Message: ${body.Message}`)
        this.logger.warn(`❌ failed to parse Message: ${err}`)
        return
      }

      // TODO: Rework the app-deployment process. It should use a web3 prefix
      // furthermore, it should publish to the pubsub instead of calling the use case
      if (isAppDeploymentCommand(data)) {
        if (data.type === 'app-deployment.discover-sc') {
          this.logger.debug(
            `executing discoverSc for ${JSON.stringify(data.payload)}`,
          )
          this.discoverSC.execute(data).fork(
            () => this.logger.debug(`discoverSC success`),
            err => this.logger.warn(`discoverSC failed: ${err}`),
          )
        } else {
          this.logger.warn(`type ${data.type} is not supported`)
        }
      } else if (web3.isWeb3Event(data)) {
        // Note: I should process only the messages generated by other
        // microservices, otherwise I could start an infinite loop
        if (message.MessageAttributes?.['Sender']?.StringValue === MS_NAME) {
          this.logger.debug(`⛔️ stopping ${data.type} propagation`)
          return
        }

        try {
          await this.pubsub.publish(data).toPromise()
        } catch (error: unknown) {
          if (isAppError(error)) {
            this.logger.warn(
              `Failed to process ${data.type}: ${error._tag}/${error.message}`,
            )
          } else {
            this.logger.warn(`Failed to process ${data.type}: ${error}`)
          }
          throw error
        }
      } else {
        this.logger.warn('data is not an app-deployment command')
      }
    }
  }
}
