import { Message } from '@aws-sdk/client-sqs'
import { Inject, Injectable, Logger } from '@nestjs/common'
import { web3 } from 'messages'
import { SqsMessageHandler } from '@ssut/nestjs-sqs'
import { isAppError, type IPubSub } from 'utils'
import { MS_NAME, PUBSUB } from '#constants.js'

@Injectable()
export class SQSConsumer {
  private readonly logger = new Logger(SQSConsumer.name)

  constructor(
    @Inject(PUBSUB)
    private readonly pubsub: IPubSub<web3.Web3Event>,
  ) {}

  @SqsMessageHandler('web3', false)
  public async handleMessage(message: Message) {
    const batchItemFailures: { itemIdentifier: string | undefined }[] = []
    if (message.Body) {
      let body: Record<string, any>
      try {
        body = JSON.parse(message.Body)
      } catch (err) {
        this.logger.debug(`received message: ${message.Body}`)
        this.logger.warn(`❌ failed to parse body: ${err}`)
        return
      }

      if (!('Message' in body)) {
        this.logger.warn(`missing 'Message' in Body: ${message.Body}`)
      }

      let data: unknown
      try {
        data = JSON.parse(body.Message)
      } catch (err) {
        this.logger.debug(`Message: ${body.Message}`)
        this.logger.warn(`❌ failed to parse Message: ${err}`)
        return { batchItemFailures }
      }

      if (web3.isWeb3Event(data)) {
        const messageAttributes:
          | Record<string, { Type: 'String'; Value: 'string' }>
          | undefined = body.MessageAttributes
        // Note: I should publish into the internal queue only the message
        // generated by other microservices
        if (messageAttributes?.Sender?.Value === (MS_NAME as string)) {
          this.logger.debug(`⛔️ stopping ${data.type} propagation`)
          return { batchItemFailures }
        }

        try {
          // Note: add a meta field to brand it as an incoming message
          data.meta[`${MS_NAME}-dir`] = 'in'
          await this.pubsub.publish(data).toPromise()
        } catch (error: unknown) {
          if (isAppError(error)) {
            this.logger.warn(
              `Failed to process ${data.type}: ${error._tag}/${error.message}`,
            )
          } else {
            this.logger.warn(`Failed to process ${data.type}: ${error}`)
          }
          this.logger.verbose(
            `pushing { itemIdentifier: ${message.MessageId} } into batchItemFailures`,
          )
          batchItemFailures.push({ itemIdentifier: message.MessageId })
        }
      } else {
        this.logger.warn('data is not an app-deployment command')
      }
    }

    return { batchItemFailures }
  }
}
