/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHEVMTestSuite5Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "add_euint128_euint16"
      | "add_euint128_uint128"
      | "add_euint16_euint32"
      | "add_euint32_euint8"
      | "add_uint128_euint128"
      | "and_euint16_uint16"
      | "and_euint256_euint16"
      | "and_euint256_uint256"
      | "and_euint32_euint64"
      | "and_euint32_uint32"
      | "and_euint64_euint64"
      | "and_uint32_euint32"
      | "eq_euint16_euint256"
      | "eq_euint256_euint32"
      | "eq_euint256_euint8"
      | "eq_euint32_euint256"
      | "eq_uint64_euint64"
      | "ge_euint32_euint128"
      | "ge_euint32_euint64"
      | "ge_euint64_euint8"
      | "gt_euint128_euint32"
      | "gt_euint32_euint16"
      | "gt_euint32_uint32"
      | "gt_euint64_euint8"
      | "gt_euint64_uint64"
      | "le_euint128_euint128"
      | "le_euint16_euint16"
      | "le_euint16_euint8"
      | "le_euint16_uint16"
      | "le_euint64_euint32"
      | "lt_euint16_euint64"
      | "lt_euint64_euint32"
      | "lt_euint64_euint8"
      | "lt_uint128_euint128"
      | "lt_uint64_euint64"
      | "max_euint128_euint128"
      | "max_euint128_euint64"
      | "max_euint128_euint8"
      | "max_euint16_euint32"
      | "max_euint64_euint32"
      | "max_euint64_euint64"
      | "min_euint16_euint16"
      | "min_euint64_euint128"
      | "min_euint64_euint64"
      | "min_uint8_euint8"
      | "mul_euint128_euint128"
      | "mul_uint128_euint128"
      | "ne_euint128_euint16"
      | "ne_euint128_euint8"
      | "ne_euint16_euint256"
      | "ne_euint16_euint8"
      | "ne_euint256_euint32"
      | "ne_euint64_euint64"
      | "ne_euint64_euint8"
      | "ne_euint64_uint64"
      | "ne_uint32_euint32"
      | "not_euint256"
      | "or_euint128_euint256"
      | "or_euint128_uint128"
      | "or_euint256_euint128"
      | "or_euint64_euint128"
      | "or_euint64_euint64"
      | "or_euint8_euint128"
      | "or_uint128_euint128"
      | "or_uint256_euint256"
      | "or_uint64_euint64"
      | "rem_euint128_uint128"
      | "resEbool"
      | "resEuint128"
      | "resEuint16"
      | "resEuint256"
      | "resEuint32"
      | "resEuint64"
      | "resEuint8"
      | "rotl_euint128_euint8"
      | "rotl_euint32_euint8"
      | "rotr_euint128_uint8"
      | "rotr_euint8_euint8"
      | "shl_euint16_euint8"
      | "shl_euint256_euint8"
      | "shl_euint64_euint8"
      | "shl_euint8_uint8"
      | "shr_euint32_euint8"
      | "sub_euint128_euint128"
      | "sub_euint16_euint16"
      | "sub_euint16_euint32"
      | "sub_euint16_euint8"
      | "sub_euint64_euint8"
      | "sub_uint128_euint128"
      | "xor_euint16_euint16"
      | "xor_euint16_euint64"
      | "xor_euint32_euint64"
      | "xor_euint64_euint32"
      | "xor_euint8_euint128"
      | "xor_euint8_euint64"
      | "xor_euint8_euint8"
      | "xor_uint64_euint64"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "add_euint128_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_euint16_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_euint32_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "add_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint256_uint256",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint32_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_euint64_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "and_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint16_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_euint32_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eq_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint32_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint32_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ge_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint128_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint32_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint32_uint32",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gt_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint16_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint16_uint16",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "le_euint64_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint16_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint64_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lt_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint128_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint128_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint16_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint64_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "max_euint64_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint16_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint64_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_euint64_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "min_uint8_euint8",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mul_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint128_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint128_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint16_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint256_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint64_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_euint64_uint64",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ne_uint32_euint32",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "not_euint256",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint128_euint256",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint256_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint64_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint64_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_euint8_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint256_euint256",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "or_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rem_euint128_uint128",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "resEbool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resEuint128",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint16",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint256",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint32",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resEuint64",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "resEuint8", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rotl_euint128_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotl_euint32_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint128_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotr_euint8_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint256_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shl_euint8_uint8",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shr_euint32_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint128_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint16_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint16_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint16_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_euint64_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sub_uint128_euint128",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint16_euint16",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint16_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint32_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint64_euint32",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint8_euint128",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint8_euint64",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_euint8_euint8",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "xor_uint64_euint64",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "add_euint128_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_euint16_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_euint32_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "add_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint256_uint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint32_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_euint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "and_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint16_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_euint32_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eq_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint32_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint32_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ge_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint128_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint32_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint32_uint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gt_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint16_uint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "le_euint64_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint16_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint64_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lt_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint128_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint128_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint16_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint64_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "max_euint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint64_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_euint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "min_uint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mul_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint128_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint128_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint16_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint256_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_euint64_uint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ne_uint32_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "not_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint128_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint256_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint64_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_euint8_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint256_euint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "or_uint64_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rem_euint128_uint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEbool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint16", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resEuint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resEuint32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resEuint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint128_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotl_euint32_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint128_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotr_euint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint256_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shl_euint8_uint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shr_euint32_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint16_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint16_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_euint64_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sub_uint128_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint16_euint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint16_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint32_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint64_euint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint8_euint128",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint8_euint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_euint8_euint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xor_uint64_euint64",
    data: BytesLike
  ): Result;
}

export interface FHEVMTestSuite5 extends BaseContract {
  connect(runner?: ContractRunner | null): FHEVMTestSuite5;
  waitForDeployment(): Promise<this>;

  interface: FHEVMTestSuite5Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add_euint128_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_euint16_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_euint32_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  add_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint256_uint256: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint32_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_euint64_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  and_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint16_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_euint32_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  eq_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint32_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint32_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ge_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint128_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint32_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint32_uint32: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  gt_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint16_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint16_uint16: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  le_euint64_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint16_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint64_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  lt_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint128_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint128_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint16_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint64_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  max_euint64_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint16_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint64_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_euint64_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  min_uint8_euint8: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  mul_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint128_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint128_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint16_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint256_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint64_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_euint64_uint64: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  ne_uint32_euint32: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  not_euint256: TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint128_euint256: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint256_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint64_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint64_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_euint8_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint256_euint256: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  or_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rem_euint128_uint128: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  resEbool: TypedContractMethod<[], [string], "view">;

  resEuint128: TypedContractMethod<[], [string], "view">;

  resEuint16: TypedContractMethod<[], [string], "view">;

  resEuint256: TypedContractMethod<[], [string], "view">;

  resEuint32: TypedContractMethod<[], [string], "view">;

  resEuint64: TypedContractMethod<[], [string], "view">;

  resEuint8: TypedContractMethod<[], [string], "view">;

  rotl_euint128_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotl_euint32_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint128_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  rotr_euint8_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint256_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shl_euint8_uint8: TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  shr_euint32_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint128_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint16_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint16_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint16_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_euint64_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  sub_uint128_euint128: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint16_euint16: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint16_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint32_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint64_euint32: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint8_euint128: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint8_euint64: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_euint8_euint8: TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  xor_uint64_euint64: TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add_euint128_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_euint16_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_euint32_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "add_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint256_uint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint32_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_euint64_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "and_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint16_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_euint32_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eq_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint32_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint32_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ge_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint128_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint32_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint32_uint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gt_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint16_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint16_uint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "le_euint64_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint16_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint64_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lt_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint128_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint128_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint16_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint64_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "max_euint64_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint16_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint64_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_euint64_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "min_uint8_euint8"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mul_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint128_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint128_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint16_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint256_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint64_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_euint64_uint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ne_uint32_euint32"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "not_euint256"
  ): TypedContractMethod<
    [a: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint128_euint256"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint256_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint64_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint64_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_euint8_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint256_euint256"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "or_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rem_euint128_uint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resEbool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint128"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint16"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint256"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint32"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint64"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resEuint8"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rotl_euint128_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotl_euint32_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint128_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotr_euint8_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint256_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shl_euint8_uint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BigNumberish, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shr_euint32_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint128_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint16_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint16_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint16_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_euint64_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sub_uint128_euint128"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint16_euint16"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint16_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint32_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint64_euint32"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint8_euint128"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint8_euint64"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_euint8_euint8"
  ): TypedContractMethod<
    [a: BytesLike, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "xor_uint64_euint64"
  ): TypedContractMethod<
    [a: BigNumberish, b: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
