services:

  kms-connector:
    container_name: kms-connector
    image: ghcr.io/zama-ai/kms-connector:v0.11.0-rc5
    environment:
      KMS_CONNECTOR_GWL2_URL: ${KMS_CONNECTOR_GWL2_URL}
      KMS_CONNECTOR_KMS_CORE_ENDPOINT: ${KMS_CONNECTOR_KMS_CORE_ENDPOINT}
      KMS_CONNECTOR_MNEMONIC: ${KMS_CONNECTOR_MNEMONIC}
      KMS_CONNECTOR_CHAIN_ID: ${KMS_CONNECTOR_CHAIN_ID}
      KMS_CONNECTOR_DECRYPTION_MANAGER_ADDRESS: ${KMS_CONNECTOR_DECRYPTION_MANAGER_ADDRESS}
      KMS_CONNECTOR_HTTPZ_ADDRESS: ${KMS_CONNECTOR_HTTPZ_ADDRESS}
      KMS_CONNECTOR_CHANNEL_SIZE: ${KMS_CONNECTOR_CHANNEL_SIZE}
      KMS_CONNECTOR_SERVICE_NAME: ${KMS_CONNECTOR_SERVICE_NAME}
      KMS_CONNECTOR_DECRYPTION_TIMEOUT_SECS: ${KMS_CONNECTOR_DECRYPTION_TIMEOUT_SECS}
      KMS_CONNECTOR_REENCRYPTION_TIMEOUT_SECS: ${KMS_CONNECTOR_REENCRYPTION_TIMEOUT_SECS}
      KMS_CONNECTOR_RETRY_INTERVAL_SECS: ${KMS_CONNECTOR_RETRY_INTERVAL_SECS}
      KMS_CONNECTOR_S3_CONFIG__REGION: ${KMS_CONNECTOR_S3_CONFIG__REGION}
      KMS_CONNECTOR_S3_CONFIG__BUCKET: ${KMS_CONNECTOR_S3_CONFIG__BUCKET}
      KMS_CONNECTOR_S3_CONFIG__ENDPOINT: ${KMS_CONNECTOR_S3_CONFIG__ENDPOINT}
      KMS_CONNECTOR_VERIFY_COPROCESSORS: ${KMS_CONNECTOR_VERIFY_COPROCESSORS}
      KMS_CONNECTOR_PRIVATE_KEY: ${KMS_CONNECTOR_PRIVATE_KEY}
    volumes:
      - ./config/connector/config.toml:/var/lib/kms-connector/config.toml
    entrypoint: >
      /bin/sh -c "
      kms-connector validate -c /var/lib/kms-connector/config.toml &&
      kms-connector start -c /var/lib/kms-connector/config.toml
      "
