# NOTE: Needs to be updated each time we re-gen the public material (i.e. relaunch docker compose locally)
[key_url]
[key_url.fhe_public_key]
data_id = "fhe-public-key-data-id"
url = "http://0.0.0.0:9000/kms-public/PUB/PublicKey/5c587d9a331bdbd1b0cedd5483bb847bf38a011da879392f931f10f2b8481885"
[key_url.crs]
data_id = "crs-data-id"
url = "http://0.0.0.0:9000/kms-public/PUB/CRS/fd15d4f6e82d3596b8f50469cb192e8ac370a09e8bc3f03830cce8256d24dd7b"

[[host_chains]]
decryption_oracle = "0xAb30999D17FAAB8c95B2eCD500cFeFc8f658f15d"
[host_chains.chain_config]
chain_id = 12345
ws_url = "ws://localhost:8546"
http_url = "http://localhost:8546"
[host_chains.chain_config.signer_config]
type = "LOCAL"
private_key_env = "HTTPZ_PRIVATE_KEY"

[gateway_chain]
zkpok_manager = "0x35760912360E875DA50D40a74305575c23D55783"
decryption_manager = "0xc9bAE822fE6793e3B456144AdB776D5A318CB71e"
[gateway_chain.chain_config]
chain_id = 54321
ws_url = "ws://localhost:8546"
http_url = "http://localhost:8546"

[gateway_chain.chain_config.signer_config]
type = "LOCAL"
private_key_env = "GATEWAY_PRIVATE_KEY"

[queues]
console_queue = "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/orchestrator-queue"
relayer_queue = "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/relayer-queue"
transaction_queue = "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/tx-manager-queue"
