mock_console = true

[key_url]
[key_url.fhe_public_key]
data_id = "fhe-public-key-data-id"
url = "http://0.0.0.0:9000/kms-public/kms/PUB/PublicKey/408d8cbaa51dece7f782fe04ba0b1c1d017b10880c538b7c72037468fe5c97ee"
[key_url.crs]
data_id = "crs-data-id"
url = "http://0.0.0.0:9000/kms-public/kms/PUB/CRS/a5fedad3fd734a598fb67452099229445cb68447198fb56f29bb64d98953d002"

[[host_chains]]
decryption_oracle = "0xAb30999D17FAAB8c95B2eCD500cFeFc8f658f15d"
[host_chains.chain_config]
chain_id = 12345
ws_url = "ws://localhost:8546"
http_url = "http://localhost:8546"
[host_chains.chain_config.signer_config.Local]
private_key_env = "HTTPZ_PRIVATE_KEY"

[gateway_chain]
zkpok_manager = "0x812b06e1CDCE800494b79fFE4f925A504a9A9810"
decryption_manager = "0x2Fb4341027eb1d2aD8B5D9708187df8633cAFA92"
[gateway_chain.chain_config]
chain_id = 54321
ws_url = "ws://localhost:8546"
http_url = "http://localhost:8546"
[gateway_chain.chain_config.signer_config.Local]
private_key_env = "GATEWAY_PRIVATE_KEY"

[queues]
console_queue = "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/orchestrator-queue"
relayer_queue = "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/relayer-queue"
transaction_queue = "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/tx-manager-queue"
