// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.24;

string constant DEPLOYER_PRIVATE_KEY_ENV = "DEPLOYER_PRIVATE_KEY";
string constant DEPLOYER_MNEMONIC_ENV = "DEPLOYER_MNEMONIC";

string constant EMPTY_UUPS_PRIVATE_KEY_ENV = "EMPTY_UUPS_PRIVATE_KEY";
string constant EMPTY_UUPS_MNEMONIC_ENV = "EMPTY_UUPS_MNEMONIC";

string constant FHE_TEST_USER_PRIVATE_KEY_ENV = "FHE_TEST_USER_PRIVATE_KEY";
string constant FHE_TEST_USER_MNEMONIC_ENV = "FHE_TEST_USER_MNEMONIC";

string constant NUM_COPROCESSORS_ENV = "NUM_COPROCESSORS";
string constant COPROCESSORS_MNEMONIC_ENV = "COPROCESSORS_MNEMONIC";

string constant NUM_KMS_NODES_ENV = "NUM_KMS_NODES";
string constant KMS_NODES_MNEMONIC_ENV = "KMS_NODES_MNEMONIC";

string constant NUM_PAUSERS_ENV = "NUM_PAUSERS";
string constant PAUSERS_MNEMONIC_ENV = "PAUSERS_MNEMONIC";

string constant CHAIN_ID_GATEWAY_ENV = "CHAIN_ID_GATEWAY";
string constant KMS_THRESHOLD_ENV = "PUBLIC_DECRYPTION_THRESHOLD";
string constant COPROCESSOR_THRESHOLD_ENV = "COPROCESSOR_THRESHOLD";
string constant HCU_CAP_PER_BLOCK_ENV = "HCU_CAP_PER_BLOCK";
string constant MAX_HCU_DEPTH_PER_TX_ENV = "MAX_HCU_DEPTH_PER_TX";
string constant MAX_HCU_PER_TX_ENV = "MAX_HCU_PER_TX";

string constant DECRYPTION_ADDRESS_ENV = "DECRYPTION_ADDRESS";
string constant INPUT_VERIFICATION_ADDRESS_ENV = "INPUT_VERIFICATION_ADDRESS";

string constant KMS_TX_SENDER_ADDRESS_ENV_PREFIX = "KMS_TX_SENDER_ADDRESS_";
string constant KMS_NODE_STORAGE_URL_ENV_PREFIX = "KMS_NODE_STORAGE_URL_";

string constant KMS_NODES_TX_SENDER_MNEMONIC_ENV = "KMS_NODES_TX_SENDER_MNEMONIC";
