name: anvil
services:
  anvil-httpz:
    container_name: anvil-httpz
    image: ghcr.io/foundry-rs/foundry:stable
    environment:
      MNEMONIC: ${MNEMONIC}
    entrypoint:
      [
        "anvil",
        "--block-time",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "8756",
        "--chain-id",
        "123456",
        "--accounts",
        "15",
        "--mnemonic",
        "${MNEMONIC}",
      ]
    ports:
      - "8756:8756"

  anvil-gateway:
    container_name: anvil-gateway
    image: ghcr.io/foundry-rs/foundry:stable
    environment:
      MNEMONIC: ${MNEMONIC}
    entrypoint:
      [
        "anvil",
        "--block-time",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "8757",
        "--chain-id",
        "654321",
        "--accounts",
        "15",
        "--mnemonic",
        "${MNEMONIC}"
      ]
    ports:
      - "8757:8757"


  gateway-sc-deploy:
    container_name: fhevm-gateway-sc-deploy
    image: ghcr.io/zama-ai/fhevm-gateway/contracts:46ce936
    env_file:
      - ./.env.gateway
    command:
      - npx hardhat task:deployGatewayMockContracts
    depends_on:
      anvil-gateway:
        condition: service_started