name: "Docker - HTTPZ Relayer"

on:
  pull_request:
    paths:
      - .github/workflows/docker_relayer.yml
      - src/**
      - config/**
      - Dockerfile
      - .hadolint.yaml
      - Makefile
      - Cargo.toml
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker_relayer.yml
      - src/**
      - config/**
      - Dockerfile
      - .hadolint.yaml
      - Makefile
      - Cargo.toml
      - Cargo.lock
  release:
    types:
      - published

concurrency:
  group: relayer-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-relayer:
    uses: zama-ai/httpz-templates/.github/workflows/docker_common.yml@58ddd70781d1456d7fe937efef501a7bc5ca2d8d # main
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "httpz-relayer"
      docker-file: "Dockerfile"
      arm-build: true