name: "Docker - HTTPZ E2E Tests"

on:
  pull_request:
    paths:
      - .github/workflows/docker_e2e.yml
      - hardhat/**
      - Makefile
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker_e2e.yml
      - hardhat/**
      - Makefile
  release:
    types:
      - published

concurrency:
  group: e2e-tester-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-e2e-tester:
    uses: zama-ai/httpz-templates/.github/workflows/docker_common.yml@58ddd70781d1456d7fe937efef501a7bc5ca2d8d # main
    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "httpz-test-suite/e2e"
      docker-file: "./hardhat/contracts/operations/Dockerfile"
      arm-build: true