name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Check formatting
      id: fmt
      continue-on-error: true
      run: cargo fmt --all -- --check
    
    - name: Clippy
      id: clippy
      continue-on-error: true
      run: cargo clippy -- -D warnings
    
    - name: Run tests
      id: test
      continue-on-error: true
      run: cargo test

    - name: Check for failures
      if: always()
      run: |
        if [[ "${{ steps.fmt.outcome }}" == "failure" ]] || \
           [[ "${{ steps.clippy.outcome }}" == "failure" ]] || \
           [[ "${{ steps.test.outcome }}" == "failure" ]]; then
          echo "One or more checks failed"
          exit 1
        fi

permissions:
  contents: read
  checks: write