name: "Relayer Docker Image"

on:
  pull_request:
    paths:
      - .github/workflows/relayer_image.yml
      - .github/workflows/common_docker.yml
      - src/**
      - config/**
      - Dockerfile
      - .hadolint.yaml
      - Makefile
      - Cargo.toml
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/relayer_image.yml
      - .github/workflows/common_docker.yml
      - src/**
      - config/**
      - Dockerfile
      - .hadolint.yaml
      - Makefile
      - Cargo.toml
      - Cargo.lock
  release:
    types:
      - published

concurrency:
  group: relayer-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  docker-relayer:
    uses: ./.github/workflows/common_docker.yml
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "."
      push_image: true
      image-name: "fhevm-relayer"
      docker-file: "Dockerfile"
      arm-build: true

    secrets:
      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}

  done:
    runs-on: ubuntu-latest
    name: Pipeline Done
    steps:
      - name: Success
        run: echo Pipeline Done
    needs:
      - docker-relayer
