name: Rust Unit Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
      with:
        toolchain: stable

    - name: Run Anvil nodes
      run: |
        make start-anvil-nodes
        
    - name: Verify Anvil nodes
      run: |
        docker ps
        docker logs anvil-httpz
        docker logs anvil-gateway
        curl -v http://localhost:8756/ || echo "Port 8756 not responding"
        curl -v http://localhost:8757/ || echo "Port 8757 not responding"

    - name: Deploy Gateway Smart Contracts
      run: |
        make setup-mock
        make deploy-gateway-smart-contracts

    - name: Setup config for relayer
      run: |
        make config-fhevm-relayer

    - name: Run tests
      run: cargo test
    
    - name: Stop Anvil nodes
      if: always()
      run: make stop-anvil-nodes

permissions:
  contents: read
  checks: write