#!/bin/bash

# Regular expression for Angular commit message convention
COMMIT_REGEX='^(feat|fix|docs|style|refactor|perf|test|chore|revert)(\([a-zA-Z0-9\-_ ]+\))?: [a-zA-Z0-9\-_ ]+'

# Path to the commit message file
COMMIT_MSG_FILE=$1

# Read the commit message
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check if the commit message matches the regular expression
if ! [[ "$COMMIT_MSG" =~ $COMMIT_REGEX ]]; then
  echo "ERROR: Commit message does not follow the conventional commit specs."
  echo "Here is a correct commit example:"
  echo "feat(scope): description"
  exit 1
fi
