import { COMPAT_MATRIX } from "./compat";

const MODERN_COMPANIONS = {
  CORE_VERSION: "v0.13.0",
  RELAYER_VERSION: COMPAT_MATRIX.externalDefaults.RELAYER_VERSION,
  RELAYER_MIGRATE_VERSION: COMPAT_MATRIX.externalDefaults.RELAYER_MIGRATE_VERSION,
} as const;

export const NON_NETWORK_COMPANIONS = {
  "latest-main": MODERN_COMPANIONS,
  "sha": MODERN_COMPANIONS,
} as const;
