common:
  address: '127.0.0.1'
  logLevel: 'debug'
  prettify: true
  port: 3001
aws:
  useConfigCredentials: true
  accessKeyId: 'test'
  secretAccessKey: 'test'
  region: 'eu-central-1'
  endpoint: 'http://console-aws:4566'
  orchestrator:
    queueUrl: 'http://console-aws:4566/000000000000/orchestrator-queue'
  back:
    queueUrl: 'http://console-aws:4566/000000000000/back-queue'
  relayer:
    queueUrl: 'http://console-aws:4566/000000000000/relayer-queue'
  web3:
    queueUrl: 'http://console-aws:4566/000000000000/web3-queue'
  email:
    queueUrl: 'http://console-aws:4566/000000000000/email-queue'
db:
  url: 'postgresql://postgres:postgres@console-postgres:5432/console?schema=orchestrator'
redis:
  host: 'console-redis'
  port: 6379
web3:
  chainIds:
    - 12345
  every: '1 hour'
