common:
  address: '127.0.0.1'
  logLevel: 'silent'
  prettify: true
  port: 3001
aws:
  accessKeyId: 'test'
  secretAccessKey: 'test'
  region: 'eu-central-1'
  endpoint: 'http://localhost:4566'
  orchestrator:
    queueUrl: 'http://localhost:4566/000000000000/orchestrator-queue'
  back:
    queueUrl: 'http://localhost:4566/000000000000/back-queue'
  relayer:
    queueUrl: 'http://localhost:4566/000000000000/relayer-queue'
  web3:
    queueUrl: 'http://localhost:4566/000000000000/web3-queue'
  email:
    queueUrl: 'http://localhost:4566/000000000000/email-queue'
db:
  url: 'postgresql://postgres:postgres@localhost:5434/console?schema=orchestrator'
redis:
  host: '127.0.0.1'
  port: 6379
web3:
  chainIds:
    - 123456
    - 11155111
  every: '1 hour'
