/**
 * Generates the threshold KMS cluster: a `core-threshold` compose override
 * (gen-keys + N cores + kms-init) plus one `compose_{i}.toml` per party.
 *
 * Used only when a scenario's `kms` block is `mode: threshold`. The centralized
 * path is untouched (single `kms-core` from `core-docker-compose.yml`).
 *
 * Design notes (kept deliberately close to how zama-ai/kms's own CI stands up a
 * threshold cluster — see ci/kube-testing + core/service/config/compose_1.toml):
 *   - Core-to-core MPC runs WITHOUT mTLS (the `[threshold.tls]` block is omitted;
 *     the field is optional). This matches the kind-CI test posture
 *     (`mtls.enabled: false`) and removes all cert generation / distribution /
 *     subject-matching. Peers reach each other by docker service name.
 *   - Per-party vaults live entirely in `compose_{i}.toml` (S3, prefixes
 *     PUB-p{i}/PRIV-p{i}); the cores take NO `KMS_CORE__*` env, only AWS creds
 *     (read from the shared minio-secrets volume in the entrypoint).
 *   - `[backup_vault]` is mandatory for threshold (the core's load path requires
 *     it), so it is always emitted.
 */
import path from "node:path";

import type { ComposeDoc } from "./compose";
import type { ResolvedKmsTopology } from "../types";
import { GENERATED_CONFIG_DIR } from "../layout";

/** Knobs the generator needs that come from the surrounding stack (S3, image tag). */
export type KmsRenderOptions = {
  coreImage: string; // e.g. ghcr.io/zama-ai/kms/core-service:${CORE_VERSION}
  s3Endpoint: string; // e.g. http://minio:9000
  s3Bucket: string; // e.g. kms-public
  s3Region: string; // e.g. eu-west-1
};

/** Render options from the resolved core image version + fhevm minio defaults. */
export const kmsRenderOptionsFor = (coreVersion: string): KmsRenderOptions => ({
  coreImage: `ghcr.io/zama-ai/kms/core-service:${coreVersion}`,
  s3Endpoint: "http://minio:9000",
  s3Bucket: "kms-public",
  s3Region: "eu-west-1",
});

/**
 * On-chain decryption/keygen consensus threshold for an n = 3t+1 cluster.
 * Reconstruction needs 2t+1 matching responses (KMS core-client `num_reconstruct`;
 * see zama-ai/kms core-client/src/lib.rs + ci/kube-testing kms values). For
 * n=4,t=1 this is 3.
 */
export const reconstructionThreshold = (threshold: number) => 2 * threshold + 1;

/** gRPC service port for party i (1-indexed): 50100, 50200, ... */
export const kmsServicePort = (partyId: number) => 50000 + partyId * 100;
/** MPC core-to-core port for party i (1-indexed): 50001, 50002, ... */
export const kmsMpcPort = (partyId: number) => 50000 + partyId;
/** Service / container name for party i. Party 1 keeps the bare `kms-core` name
 * so existing references (KMS_CORE_CONTAINER, connector endpoints, discovery)
 * keep working; parties 2..N are `kms-core-{i}`. Cores reach each other (and the
 * connector reaches them) by these names over the docker network. */
export const kmsCoreName = (partyId: number) => (partyId === 1 ? "kms-core" : `kms-core-${partyId}`);
/** Generated per-node config filename. */
export const kmsThresholdConfigName = (partyId: number) => `compose_${partyId}.toml`;

const partyIds = (parties: number) => Array.from({ length: parties }, (_, i) => i + 1);

/**
 * Renders the threshold config TOML for one party, including the full peer list.
 * Modeled on zama-ai/kms core/service/config/compose_1.toml, minus the
 * `[threshold.tls...]` block (mTLS disabled for CI).
 */
export const renderThresholdConfigToml = (
  partyId: number,
  topology: ResolvedKmsTopology,
  opts: KmsRenderOptions,
): string => {
  // No mTLS: peers connect plaintext by docker service name; no tls_cert / mpc_identity.
  const peers = partyIds(topology.parties)
    .map(
      (peer) => `[[threshold.peers]]
party_id = ${peer}
address = "${kmsCoreName(peer)}"
port = ${kmsMpcPort(peer)}`,
    )
    .join("\n\n");

  return `# Generated by fhevm-cli for party ${partyId} of ${topology.parties} (threshold ${topology.threshold}).
# Modeled on zama-ai/kms core/service/config/compose_1.toml (mTLS omitted for CI).
mock_enclave = true

[service]
listen_address = "0.0.0.0"
listen_port = ${kmsServicePort(partyId)}
timeout_secs = 360
grpc_max_message_size = 104857600 # 100 MiB

[aws]
region = "${opts.s3Region}"
s3_endpoint = "${opts.s3Endpoint}"

[public_vault]
[public_vault.storage.s3]
bucket = "${opts.s3Bucket}"
prefix = "PUB-p${partyId}"

[private_vault.storage.s3]
bucket = "${opts.s3Bucket}"
prefix = "PRIV-p${partyId}"

[backup_vault]
[backup_vault.storage.file]
path = "./backup_vault"
prefix = "BACKUP-p${partyId}"

[threshold]
listen_address = "0.0.0.0"
listen_port = ${kmsMpcPort(partyId)}

my_id = ${partyId}

threshold = ${topology.threshold}
dec_capacity = 10000
min_dec_cache = 6000
num_sessions_preproc = 2

decryption_mode = "NoiseFloodSmall"

${peers}

[threshold.core_to_core_net]
message_limit = 70
multiplier = 2.0
max_interval = 60
initial_interval_ms = 100
max_elapsed_time = 300
network_timeout = 20
network_timeout_bk = 300
network_timeout_bk_sns = 1200
max_en_decode_message_size = 2147483648
session_update_interval_secs = 60
session_cleanup_interval_secs = 86400
discard_inactive_sessions_interval = 10800
max_waiting_time_for_message_queue = 60
max_opened_inactive_sessions_per_party = 2000

[telemetry]
tracing_service_name = "kms-threshold-${partyId}"
tracing_otlp_timeout_ms = 10000
metrics_bind_address = "0.0.0.0:9646"

[rate_limiter_conf]
bucket_size = 50000
pub_decrypt = 1
user_decrypt = 1
crsgen = 100
preproc = 25000
keygen = 1000
new_epoch = 1
`;
};

/** Renders every per-node config keyed by generated filename. */
export const renderThresholdConfigs = (
  topology: ResolvedKmsTopology,
  opts: KmsRenderOptions,
): Record<string, string> =>
  Object.fromEntries(
    partyIds(topology.parties).map((partyId) => [
      kmsThresholdConfigName(partyId),
      renderThresholdConfigToml(partyId, topology, opts),
    ]),
  );

/** Shell for the signing-key setup container (loops over all parties). Generates ONLY each
 * party's signing key into S3 (PRIV-p{i}) via `--cmd signing-keys` — mirroring the KMS reference
 * threshold compose. The FHE key shares and CRS are NOT pre-generated here; they come from the
 * real on-chain DKG (keygen/crsgen). `--num-parties` must match the cluster size (the CLI rejects
 * a signing-key-party-id greater than num-parties; it also defaults to 4). No TLS certs are needed
 * (mTLS disabled), so nothing is fetched back locally. */
const genKeysCommand = (topology: ResolvedKmsTopology, opts: KmsRenderOptions) =>
  [
    "set -e",
    "export AWS_ACCESS_KEY_ID=$$(cat /minio_secrets/access_key)",
    "export AWS_SECRET_ACCESS_KEY=$$(cat /minio_secrets/secret_key)",
    `echo "=== generating signing keys for ${topology.parties} parties ==="`,
    `for i in $(seq 1 ${topology.parties}); do \\
  kms-gen-keys --aws-region ${opts.s3Region} \\
    --public-storage s3 --public-s3-bucket ${opts.s3Bucket} --public-s3-prefix PUB-p$$i \\
    --aws-s3-endpoint ${opts.s3Endpoint} \\
    --private-storage s3 --private-s3-bucket ${opts.s3Bucket} --private-s3-prefix PRIV-p$$i \\
    --cmd signing-keys \\
    threshold --signing-key-party-id $$i --tls-subject kms-core-$$i --tls-wildcard --num-parties ${topology.parties}; \\
done`,
  ].join("\n");

/** Entrypoint shell for a core: export AWS creds from the minio-secrets volume, then run kms-server. */
const coreEntrypoint = (partyId: number) =>
  `export AWS_ACCESS_KEY_ID=$$(cat /minio_secrets/access_key); export AWS_SECRET_ACCESS_KEY=$$(cat /minio_secrets/secret_key); exec kms-server --config-file config/${kmsThresholdConfigName(partyId)}`;

/**
 * Builds the threshold cluster compose doc: 1 gen-keys container + N cores +
 * kms-init. This is the generated override for the `core-threshold` component
 * (a dedicated component, so it never merges with the centralized `core`
 * template — no env/healthcheck conflicts to work around).
 */
export const buildKmsThresholdOverride = (
  topology: ResolvedKmsTopology,
  opts: KmsRenderOptions,
): ComposeDoc => {
  if (topology.mode !== "threshold") {
    throw new Error("buildKmsThresholdOverride called for a non-threshold topology");
  }
  const services: Record<string, Record<string, unknown>> = {};

  services["kms-core-gen-keys"] = {
    container_name: "kms-core-gen-keys",
    image: opts.coreImage,
    entrypoint: ["/bin/sh", "-c", genKeysCommand(topology, opts)],
    volumes: ["fhevm_minio_secrets:/minio_secrets"],
  };

  for (const partyId of partyIds(topology.parties)) {
    const name = kmsCoreName(partyId);
    services[name] = {
      container_name: name,
      image: opts.coreImage,
      entrypoint: ["/bin/sh", "-c", coreEntrypoint(partyId)],
      volumes: [
        `${path.join(GENERATED_CONFIG_DIR, kmsThresholdConfigName(partyId))}:/app/kms/core/service/config/${kmsThresholdConfigName(partyId)}`,
        "fhevm_minio_secrets:/minio_secrets",
      ],
      ports: [
        `${kmsServicePort(partyId)}:${kmsServicePort(partyId)}`,
        `${kmsMpcPort(partyId)}:${kmsMpcPort(partyId)}`,
      ],
      healthcheck: {
        // The core image ships no grpc_health_probe; probe the metrics port.
        test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:9646/metrics || exit 1"],
        interval: "3s",
        timeout: "3s",
        retries: 30,
        start_period: "5s",
      },
      depends_on: {
        "kms-core-gen-keys": { condition: "service_completed_successfully" },
      },
    };
  }

  // Once all cores are healthy, kms-init establishes the MPC context/epoch
  // across the parties (required before the cluster can serve requests).
  const initEndpoints = partyIds(topology.parties)
    .map((partyId) => `http://${kmsCoreName(partyId)}:${kmsServicePort(partyId)}`)
    .join(" ");
  services["kms-core-init"] = {
    container_name: "kms-core-init",
    image: opts.coreImage,
    entrypoint: ["/bin/sh", "-c", `kms-init -a ${initEndpoints}`],
    depends_on: Object.fromEntries(
      partyIds(topology.parties).map((partyId) => [
        kmsCoreName(partyId),
        { condition: "service_healthy" },
      ]),
    ),
  };

  return {
    services,
    volumes: { fhevm_minio_secrets: { external: true } },
  } as ComposeDoc;
};
