name: check-docs

on:
  pull_request:
    paths:
      - 'docs/**'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-docs:
    name: check-docs
    runs-on: ubuntu-latest
    container:
      image: python:3.10.17-bullseye@sha256:0b9be13617fed7d883b30e31a47371a8bdd60a4bb5e45fcda63cb4a3846f6d98
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - run: python3 -m pip install linkcheckmd
      - name: Check dead-link
        run: python3 ./ci/local_docs_link_check.py