name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

permissions:
  contents: read # required for repository checkout
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  rust:
    name: ci/rust (bpr)
    permissions:
      contents: read # required by the reusable workflow for checkout
      checks: write # reusable workflow needs to create check run summaries
    uses: ./.github/workflows/rust_ci.yaml
    secrets:
      DEVELOPER_PLATFORM_ACTIONS_TOKEN: ${{ secrets.DEVELOPER_PLATFORM_ACTIONS_TOKEN }}
      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}
