name: "Docker - Relayer"

on:
  pull_request:
    paths:
      - .github/workflows/docker_relayer.yml
      - apps/relayer/src/**
      - apps/relayer/config/**
      - apps/relayer/Dockerfile
      - apps/relayer/.hadolint.yaml
      - apps/relayer/Makefile
      - apps/relayer/Cargo.toml
      - apps/relayer/Cargo.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker_relayer.yml
      - apps/relayer/src/**
      - apps/relayer/config/**
      - apps/relayer/Dockerfile
      - apps/relayer/.hadolint.yaml
      - apps/relayer/Makefile
      - apps/relayer/Cargo.toml
      - apps/relayer/Cargo.lock
  release:
    types:
      - published

concurrency:
  group: relayer-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  docker-relayer:
    if: ${{ github.event_name != 'release' || startsWith(github.ref_name, 'relayer') }}
    uses: zama-ai/ci-templates/.github/workflows/docker_common.yml@4d722297aae4626adec8eb5d678dc00a2adc0a72 # main
    secrets:
      GHCR_ACTION_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      working-directory: "apps/relayer"
      docker-context: "apps/relayer"
      push_image: true
      image-name: "console/relayer"
      docker-file: "Dockerfile"
      arm-build: true
  docker-oracle:
    if: ${{ github.event_name != 'release' || startsWith(github.ref_name, 'relayer') }}
    uses: zama-ai/ci-templates/.github/workflows/docker_common.yml@4d722297aae4626adec8eb5d678dc00a2adc0a72 # main
    secrets:
      GHCR_ACTION_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
      GRAVITON_BUILDER_SSH_PRIVATE_KEY: ${{ secrets.GRAVITON_BUILDER_SSH_PRIVATE_KEY }}
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    with:
      ref: 
      working-directory: "apps/relayer/oracle"
      docker-context: "apps/relayer/oracle"
      push_image: true
      image-name: "console/relayer-decryption-oracle-contracts"
      docker-file: "Dockerfile"
      arm-build: true
