name: publish-solidity-oracle-contract

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Set to true for release tagging"
        required: false
        default: false

jobs:
  publish:
    name: publish-solidity-oracle-contract/publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/oracle
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Compile contracts
        run: pnpm run compile

      - name: Publish prerelease to npm
        if: ${{ inputs.release != 'true' }}
        uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3.1.1
        with:
          tag: prerelease
          token: ${{ secrets.DEVELOPER_PLATFORM_NPM_TOKEN }}
          provenance: false
          access: public

      - name: Publish release to npm
        if: ${{ inputs.release == 'true' }}
        uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3.1.1
        with:
          token: ${{ secrets.DEVELOPER_PLATFORM_NPM_TOKEN }}
          provenance: false
          access: public
