name: relayer-dependency-analysis

on:
  pull_request:
permissions:
  contents: read # required to fetch repository sources for analysis
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  dependencies-check:
    name: relayer-dependency-analysis/dependencies-check (bpr)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/relayer
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Rust setup
        uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203 # v1
        with:
          toolchain: stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@7691a5b29cda4f5499b819e5618012ba4b6c3334 # v1.17.5

      - name: Install cargo tools
        run: |
          cargo binstall --no-confirm --force \
            cargo-audit@0.22.0 \
            cargo-deny@0.16.2

      - name: Check that Cargo.lock is the source of truth
        run: |
          cargo update -w --locked || (echo "Error: Cargo.lock is out of sync. Please run 'cargo update' locally and commit changes" && exit 1)

# TODO: check the `cd part later`
      - name: License whitelist
        run: cargo-deny deny check license --deny license-not-encountered

      - name: Security issue whitelist
        run: cargo-audit audit
