name: Tests

on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  npm-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5434:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Checkout Console repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: |
          pnpm --filter messages build
          pnpm --filter utils build
      - name: Generate Prisma code
        run: pnpm prisma:generate
      - name: Test
        run: pnpm test

  compile-rust-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [apps/relayer]
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          token: ${{ secrets.RELAYER_TOKEN }}
          submodules: recursive

      # Rust toolchain setup
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1.10.1
        with:
          toolchain: stable
          components: rustfmt, clippy, llvm-tools-preview

      - name: Formatting
        run: cd ${{matrix.folder}} && cargo fmt --all -- --check
      - name: Linting
        run: cd ${{matrix.folder}} && cargo clippy --all-targets --all-features --workspace --exclude fhevm-relayer -- -D warnings

      - name: Run Tests with Coverage
        run: |
          export CARGO_INCREMENTAL=0
          export RUSTFLAGS='-Cinstrument-coverage'
          export LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw'
          # NOTE: Could be set with a matrix when we have multiple RUST services
          cd ${{matrix.folder}}
          RUST_BACKTRACE=full cargo test --workspace --exclude fhevm-relayer
          cargo install grcov
          mkdir coverage
          ~/.cargo/bin/grcov . --binary-path ./target/debug/deps/ -s . --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o coverage/ -t markdown
          ~/.cargo/bin/grcov . --binary-path ./target/debug/deps/ -s . --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o ./ -t lcov
          cat coverage/markdown.md
          cat coverage/markdown.md >> "$GITHUB_STEP_SUMMARY"
      - name: Report code coverage
        uses: romeovs/lcov-reporter-action@87a815f34ec27a5826abba44ce09bbc688da58fd # v0.4.0
        with:
          title: test-coverage
          lcov-file: lcov
