export const fheTestAbi = [
  {
    type: "function",
    name: "CONTRACT_NAME",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "confidentialProtocolId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "getCoprocessorConfig",
    inputs: [],
    outputs: [
      {
        name: "config",
        type: "tuple",
        internalType: "struct CoprocessorConfig",
        components: [
          { name: "ACLAddress", type: "address", internalType: "address" },
          {
            name: "CoprocessorAddress",
            type: "address",
            internalType: "address",
          },
          {
            name: "KMSVerifierAddress",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClearText",
    inputs: [{ name: "handle", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClearText",
    inputs: [{ name: "handle", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClearText",
    inputs: [{ name: "handle", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHandleOf",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "fheType", type: "uint8", internalType: "enum FheType" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasHandleOf",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "fheType", type: "uint8", internalType: "enum FheType" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "makePubliclyDecryptable",
    inputs: [{ name: "fheType", type: "uint8", internalType: "enum FheType" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initFheTest",
    inputs: [{ name: "force", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  ...[
    ["xorEbool", "externalEbool", "bool"],
    ["addEuint8", "externalEuint8", "uint8"],
    ["addEuint16", "externalEuint16", "uint16"],
    ["addEuint32", "externalEuint32", "uint32"],
    ["addEuint64", "externalEuint64", "uint64"],
    ["addEuint128", "externalEuint128", "uint128"],
    ["xorEuint256", "externalEuint256", "uint256"],
    ["eqEaddress", "externalEaddress", "address"],
  ].map(([name, externalType, clearType]) => ({
    type: "function",
    name,
    inputs: [
      { name: "input", type: "bytes32", internalType: externalType },
      { name: "inputProof", type: "bytes", internalType: "bytes" },
      { name: "clearValue", type: clearType, internalType: clearType },
      { name: "makePublic", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  })),
  ...[
    ["setEbool", "externalEbool", "bool", "ebool"],
    ["setEuint8", "externalEuint8", "uint8", "euint8"],
    ["setEuint16", "externalEuint16", "uint16", "euint16"],
    ["setEuint32", "externalEuint32", "uint32", "euint32"],
    ["setEuint64", "externalEuint64", "uint64", "euint64"],
    ["setEuint128", "externalEuint128", "uint128", "euint128"],
    ["setEuint256", "externalEuint256", "uint256", "euint256"],
    ["setEaddress", "externalEaddress", "address", "eaddress"],
  ].map(([name, externalType, clearType, encryptedType]) => ({
    type: "function",
    name,
    inputs: [
      { name: "input", type: "bytes32", internalType: externalType },
      { name: "inputProof", type: "bytes", internalType: "bytes" },
      { name: "clearValue", type: clearType, internalType: clearType },
      { name: "makePublic", type: "bool", internalType: "bool" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: encryptedType }],
    stateMutability: "nonpayable",
  })),
  ...[
    ["setClearEbool", "bool", "ebool"],
    ["setClearEuint8", "uint8", "euint8"],
    ["setClearEuint16", "uint16", "euint16"],
    ["setClearEuint32", "uint32", "euint32"],
    ["setClearEuint64", "uint64", "euint64"],
    ["setClearEuint128", "uint128", "euint128"],
    ["setClearEuint256", "uint256", "euint256"],
    ["setClearEaddress", "address", "eaddress"],
  ].map(([name, clearType, encryptedType]) => ({
    type: "function",
    name,
    inputs: [
      { name: "value", type: clearType, internalType: clearType },
      { name: "makePublic", type: "bool", internalType: "bool" },
    ],
    outputs: [{ name: "", type: "bytes32", internalType: encryptedType }],
    stateMutability: "nonpayable",
  })),
] as const;
